robertknight/rten

ocrs-cli/src/main.rs

Fix slow model downloads by moving models to a different bucket which has S3 Transfer Acceleration enabled. I couldn't enable this for the original bucket because AWS doesn't support S3TA for buckets with a period in their name.
With the original URL I was able to reproduce sporadic slow downloads when downloading with ureq, reqwest and curl.
Fixes https://github.com/robertknight/rten/issues/22

Fix slow model downloads by changing download source

---

src/gemm.rs
src/gemm/kernels.rs
src/gemm/kernels/aarch64.rs
src/iter_util.rs

This is just a copy of the base kernel that has been tweaked to take advantage of the extra available SIMD registers (32 instead of 16 as in SSE), use FMA instructions and unroll the inner loop.
On an AWS c6g.xlarge instance (Graviton 2, 4 vCPU) this achieves ~114 GFLOPS vs ~65 with the base kernel. For comparison OpenBLAS achieves ~150 GFLOPS.
Related issues: https://github.com/robertknight/rten/issues/18

Add an initial non-optimized ARM NEON kernel

---

rten-vecmath/src/lib.rs
rten-vecmath/src/simd_vec.rs
rten-vecmath/src/simd_vec/aarch64.rs

Tested on an M1 Mac. The speedup for the vectorized functions is 4-5x as expected. I have locally run the `*_exhaustive` tests manually to verify unary function results for all f32 values.

Add aarch64 implementations for rten-vecmath

---

src/gemm/kernels/aarch64.rs

Revise aarch64 kernel to use SIMD intrinsics. The structure is the same as the AVX 2 / FMA kernel, but the tile size is set to 8x8 as that performed best. I did not port the prefetching logic as `std::arch::aarch64::_prefetch` is currently nightly only :(
On an M1 Mac (AWS mac2.metal) performance for an M=N=K=1024 matmul increases from ~334 to ~418 GFLOPS.
On a Graviton 2 (AWS c6g.xlarge) performance for an M=N=K=1024 matmul increases from ~115 to ~136 GFLOPS.
One observation from my tests is that ARM performance is much more sensitive to whether unrolling is used than the AVX kernel. Performance drops ~40 GFLOPS without it on the M1 in this test.

Optimize aarch64 GEMM kernel

---

rten-tensor/src/iterators.rs
rten-tensor/src/layout.rs
rten-tensor/src/lib.rs
rten-tensor/src/ndtensor.rs
rten-tensor/src/tensor.rs
src/ops/conv.rs
src/ops/layout.rs
src/ops/mod.rs
src/ops/norm.rs
src/ops/pooling.rs
src/ops/reduce.rs

This PR contains some preparation for unifying the `TensorBase` and `NdTensorBase` structs, in order to enforce a more consistent API between them.
There are also some small API changes to the existing APIs of `NdLayout`/`DynLayout` and `TensorBase`/`NdTensorBase` to prepare for a unified API, including some removal of APIs that are no longer used internally.

Make various iterators generic over the tensor layout

---

rten-examples/Cargo.toml
rten-examples/README.md
rten-examples/src/depth_anything.rs
src/model.rs
src/model_builder.rs
src/ops/mod.rs
src/ops/norm.rs
src/ops/operators.rs
src/ops/resize.rs
src/schema.fbs
src/schema_generated.rs
tools/convert-onnx.py
tools/schema_generated.py

Implement the `LayerNormalization` operator, which is ubiquitous in all transformer models, but was decomposed into other operators by PyTorch until recently (I think).
This was added to get the [Depth Anything](https://github.com/LiheYoung/Depth-Anything) model working. Credit to https://github.com/fabio-sim/Depth-Anything-ONNX for the ONNX conversion.
TODO:

Add LayerNormalization operator, Depth Anything example

---

src/ops/gather.rs

Per the ONNX spec [1]:
> All index values are expected to be within bounds [-s, s-1] along axis of size s.
The implementation already supported negative values, only the bounds check preceding it did not.
[1] https://onnx.ai/onnx/operators/onnx__Gather.html
Fixes https://github.com/robertknight/rten/issues/46

Allow negative indices in `Gather` op

---

rten-cli/src/main.rs
src/lib.rs
src/model.rs
src/model_builder.rs
src/model_metadata.rs
src/schema.fbs
src/schema_generated.rs
tools/convert-onnx.py
tools/schema_generated.py

Add initial support for storing model metadata in RTen models. Metadata is accessed via `Model::metadata` in Rust and added to converted models by specifying a JSON file containing the metadata when running `convert-onnx.py`, using a new `--metadata` flag.
The ONNX spec is quite bare-bones with respect to standard metadata fields. RTen is a bit more prescriptive about what _should_ be included and the formats of those fields.
Summary of changes:
- Add `Metadata` table to FlatBuffers schema for `.rten` models
- Add support for writing `Metadata` table when converting ONNX models
- Add `Model::metadata` to access model metadata
- Print model metadata when running `rten-cli <model_path>`
Part of https://github.com/robertknight/rten/issues/20

Add initial support for model metadata in RTen models

---

.github/workflows/ci.yml

Add an M1 runner to CI to provide coverage of ARM-specific code.
See https://github.blog/changelog/2024-01-30-github-actions-introducing-the-new-m1-macos-runner-available-to-open-source/
Fixes https://github.com/robertknight/rten/issues/33

Add M1 runner to CI

---

src/ops/matmul.rs
src/test_util.rs

Previously batched matrix multiplication was handled by prepacking one or neither of the inputs, depending on how often each is re-used, and then performing one `gemm` call per matrix in the output shape. This is inefficient if the `A` input has only a small number of rows (as in #50). This PR implements a new strategy for the `MatMul` operator when `A` is a batch and `B` is a single matrix, by reshaping the inputs so that instead of many low-arithmetic intensity `gemm` calls, a single higher-arithmetic intensity call is performed. The output is then reshaped to restore the batch dimensions.
Testing with the benchmark added here and slight variations, the new method is a big improvement when M <= 8, a modest win for M ~ 8-24 and is roughly even, or a very slight win after that. The AVX …

Add alternative strategy for batched matrix multiplication

---

rten-convert/rten_convert/schema_generated.py
src/schema.fbs
src/schema_generated.rs

This increases the number of operator types that can be declared without resorting to a breaking change or negative enum values.
The current values are all <= 127 and the new type has the same size and alignment as the previous type, so this change is backwards compatible.
See also https://github.com/robertknight/rten/issues/54

Use `ubyte` for OperatorType enum

---

.gitignore
README.md
rten-convert/LICENSE
rten-convert/README.md
rten-convert/pyproject.toml

Update READMEs and rten-convert project metadata following the [Python packaging guide](https://packaging.python.org/en/latest/tutorials/packaging-projects/). The current version has now been [released](https://pypi.org/project/rten-convert/) and can be installed with:
```sh
pip install rten-convert
```

Update rten-convert project metadata and README for PyPI release

---

.github/workflows/ci.yml
src/lib.rs

The name of the feature changed in recent Rust nightly builds.

Update std features for AVX-512

---

Cargo.lock
Cargo.toml
rten-bench/Cargo.toml
rten-bench/src/lib.rs
rten-imageproc/Cargo.toml
rten-imageproc/src/contours.rs
rten-tensor/src/test_util.rs
src/gemm.rs
src/lib.rs
src/ops/conv.rs
src/ops/layout.rs
src/ops/matmul.rs
src/test_util.rs

Following some performance investigations in https://github.com/robertknight/rten/issues/42#issuecomment-1993700942:
- Add a simple benchmark for Transpose operations
- Extract the existing `run_bench` utility into an unpublished `rten-bench` crate, so it can be reused by different crates.

Add simple benchmark for Transpose ops, extract rten-bench crate

---

.github/workflows/ci.yml
src/gemm.rs

MatMul operations with with shapes like this come up frequently in transformer decoders. This runs at about 1/4 the speed of Accelerate on my Intel i5-1038NG7.
[1] https://gist.github.com/robertknight/3e7bf748b5435657ca671930c30e4ec7

Add benchmark for vector-matrix product

---

rten-vecmath/src/lib.rs
rten-vecmath/src/simd_vec.rs
rten-vecmath/src/simd_vec/aarch64.rs
rten-vecmath/src/simd_vec/x86_64.rs
src/gemm.rs
src/gemm/kernels.rs
src/gemm/kernels/aarch64.rs
src/gemm/kernels/x86_64.rs
src/iter_util.rs
src/ops/matmul.rs

When the LHS / "A" matrix argument to a matrix multiplication is a row vector,
use an optimized vector-matrix ("gemv" in BLAS terminology) function which avoids the overhead of
packing, as otherwise packing costs consume most of the execution time.
Vector-matrix multiplications are common in autoregressive transformers,
including LLMs.
Rather than implement the same algorithm separately for each architecture, the
generic SIMD wrappers in rten-vecmath are reused.
Tested on an Intel i5-1038NG7, this improves the performance of the
vector-matrix product in the `bench_gemm` benchmark by ~4x (5 -> 20 GFLOPS).
**TODO:**

Add optimized GEMM implementation for vector-matrix multiplications

---

rten-vecmath/src/simd_vec.rs
rten-vecmath/src/simd_vec/wasm.rs
tools/benchmarks/wasm-gemm.js

This PR contains a few changes that enable using explicit SIMD for WASM outside of the rten-vecmath crate.
- Inline all the `SimdFloat`/`SimdInt` impls for WASM SIMD vectors, as was done for other architectures in 9012d41cfacf751d1cb1c378f10b038072a0d415.
- Expose the `rten_vecmath::simd_vec::wasm` submodule so that other crates can access the `v128f` and `v128i` types, in order to instantiate a generic function using them as the `SimdFloat` type.
- Add a benchmark for vector-matrix products to the WASM GEMM benchmarks

Support using WASM impls of `SimdFloat`/`SimdInt` outside of the rten-vecmath crate

---

rten-vecmath/src/simd_vec.rs
rten-vecmath/src/simd_vec/x86_64.rs
src/gemm/kernels.rs
src/gemm/kernels/aarch64.rs
src/gemm/kernels/x86_64.rs
src/iter_util.rs

The current GEMM microkernels for all architectures had the same structure except for the intrinsics used and the tile size. As a result it is possible to unify them into a single generic implementation, parametrized by the vector register type and tile dimensions. An exception is AVX-512 since rten-vecmath is missing a `SimdFloat` implementation for that instruction set.
I verified that the performance for Intel / Arm is the same or slightly better than before when tested on my Intel laptop and AWS c6i / c6g instances.
It will probably be the case in future that one or more architectures does need some architecture-specific tweaks to get the best performance, but the generic implementation will at least provide a decent baseline.

Use generic implementation for GEMM microkernel

---

src/gemm.rs
src/gemm/kernels.rs
src/gemm/kernels/wasm.rs

Performance on Intel is slightly better than before due to a larger tile size (MR=8, NR=8 rather than MR=8, NR=4). Performance on Arm, tested on Graviton 2 (AWS c6g), is about 40% better.
Performance of TensorFlow.js is still noticeably better on Arm though:
Results on c6g before for M=N=K=512:
- Before (rten): ~7.75 GFLOPS
- After (rten): ~11 GFLOPS
- TF.js: ~14.5 GFLOPS
I suspect TF.js might be using fused multiply-add from the WASM relaxed SIMD instruction set, but I need to verify this.
WASM binaries containing WASM relaxed SIMD instructions are not yet supported by wasm-bindgen, but this change will make it easier to adopt once it is.

Add WASM GEMM microkernel

---

Cargo.toml
rten-vecmath/Cargo.toml
rten-vecmath/src/lib.rs
rten-vecmath/src/simd_vec/x86_64.rs
src/gemm/kernels/x86_64.rs

Update the AVX-512 GEMM microkernel to match the other microkernels by using the generic SIMD implementation. In the process implement SimdInt, SimdFloat traits for AVX-512 vectors. This is a step towards AVX-512 implementations of the various math functions in rten-vecmath.

Add AVX-512 implementations of SimdFloat, SimdInt. Use them for GEMM.

---

rten-convert/rten_convert/converter.py
rten-convert/rten_convert/schema_generated.py
src/model.rs
src/ops/rnn.rs
src/schema.fbs
src/schema_generated.rs

Fix an error when converting LSTM / GRU operators with a direction attribute of
"forward", or with no direction specified, as "forward" is the default. The
enum name was previously `Forwards`, so the conversion code expected an
attribute value of `forwards`.
The problem was spotted when converting the `decoder_iter.onnx` model from
https://github.com/xd009642/xd-tts/tree/master/models/tacotron2.

Align name of `Forward` enum variant for RNN ops with ONNX attribute value

---

Cargo.lock
Cargo.toml
rten-cli/Cargo.toml
rten-convert/rten_convert/converter.py
rten-convert/rten_convert/schema_generated.py
rten-examples/Cargo.toml
rten-vecmath/Cargo.toml
src/lib.rs
src/model.rs
src/model_builder.rs
src/ops/mod.rs
src/ops/random.rs
src/schema.fbs
src/schema_generated.rs

Implemented as part of getting Tacotron2 to work. See https://github.com/robertknight/xd-tts/tree/rten-inference.

Implement RandomUniform operator

---

src/gemm.rs
src/gemm/kernels.rs
src/gemm/packing.rs

Avoid overhead from zeroing memory when prepacking matrix inputs by allowing the packing functions to write to uninitialized memory. The packing functions guarantee that the entire buffer passed to them is initialized when they return.
In a TTS demo using Tacotron2 [^1], which uses an LSTM-based decoder, this reduces the "real-time factor" (degree of slowdown over real-time generation) from ~1.9x to ~1.65x.
TODO:
[^1]: https://github.com/robertknight/xd-tts

Avoid zero-initialization of packing buffers

---

src/ops/layout.rs

This demonstrates the issue in https://github.com/robertknight/rten/issues/66.

Add benchmarks / notes about transpose ops and power-of-2 sizes

---

Cargo.toml
rten-cli/Cargo.toml
rten-imageio/Cargo.toml
rten-imageproc/Cargo.toml
rten-tensor/Cargo.toml
rten-text/Cargo.toml
rten-vecmath/Cargo.toml

This prevents inclusion of test data and other scripts in the generated package.
Fixes https://github.com/robertknight/rten/issues/76

Add `include` field to Cargo.toml files

---

rten-bench/src/lib.rs
rten-imageproc/src/contours.rs
rten-tensor/src/layout.rs
rten-tensor/src/tensor.rs
rten-tensor/src/transpose.rs
src/gemm.rs
src/ops/conv.rs
src/ops/layout.rs
src/ops/matmul.rs

Before this PR the transpose operation had a naive implementation which used nested for loops to generate all valid indices and the source/dest offsets, then copied the value from the permuted/transposed source view to the destination.
This actually worked quite well except for cases where the strides after permuting/transposing the source were a multiple of the cache line size, especially powers of 2. In that case cache conflicts caused performance to be much worse. Transposing a 1024x1024 matrix was ~8x slower than copying the data (excluding the time taken for memory allocation), whereas for a 1023x1023 matrix it was only ~1.5x.
This PR fixes the issue by adding a simple implementation of blocking and tiling for transpose operations. Initially this is only enabled for cases where the …

Add blocking / tiling for transpose operations

---

rten-tensor/src/index_iterator.rs
src/gemm.rs
src/gemm/kernels.rs
src/gemm/kernels/aarch64.rs
src/gemm/kernels/wasm.rs
src/gemm/kernels/x86_64.rs
src/gemm/packing.rs

Refactor the GEMM kernel traits to simplify aspects of the code and prepare for future improvements.
- Move the responsibility for checking for instruction set support from code calling `Kernel` trait methods, to the types that implement `Kernel`. These types are now only constructible if the kernel is usable, and all methods taking `&self` can then assume this has already been checked
- Make the `Kernel` trait object-safe, eliminating the need for the `GemmOps` wrapper trait
- As a side effect of the previous point, the tile size constants `MR` and `NR` are no longer associated constants of the kernel trait but dynamic values accessible via `Kernel::{mr, nr}`. This reduces generated code size for the outer GEMM loops, since they don't have to be generic any more, but also paves the way …

Refactor GEMM kernel traits

---

src/gemm/kernels/x86_64.rs
src/gemm/packing.rs

The packing functions benefit from being able to use newer instructions.

Enable AVX instructions in packing functions when using AVX-* kernels

---

src/gemm.rs
src/gemm/kernels.rs

When `gemm` was called with `beta == 0`, the results could be inconsistent depending on the output location if the output buffer contained NaN or Inf before the call. Loops handling full tiles would skip reading the initial value from the output buffer if `beta == 0`, but loops handling non-full tiles would read the existing value and multiply by beta. This could produce Inf/Nan values. Fix the issue by always ignoring the initial value when beta is zero.
This choice is consistent with BLAS libraries [1] and is also necessary if we want to support using uninitialized output buffers, which may contain NaN/Inf bit patterns.
[1] See eg. https://community.intel.com/t5/Intel-oneAPI-Math-Kernel-Library/Vector-vector-product-cblas-sgemm-problem/td-p/785743

Fix inconsistent outputs when beta == 0

---

rten-tensor/src/tensor.rs
src/gemm.rs
src/ops/matmul.rs

Following the fix in https://github.com/robertknight/rten/pull/81, it is now possible to skip zeroing the output buffer for the MatMul operator. In the process add some APIs to `Tensor` to support working with uninitialized buffers. This makes the Whisper ASR demo mentioned in https://github.com/robertknight/rten/issues/42 about ~4% faster.
In the process, fix an issue where `gemm` did not initialize outputs if the `K` dimension is zero.

Avoid zeroing output buffer for MatMul operator

---

src/gemm/kernels.rs
src/gemm/kernels/aarch64.rs
src/gemm/kernels/x86_64.rs

Make some simple optimizations to vector-matrix product microkernels:
- Unroll the inner loop over depth
- Increase the number of accumulator registers from 2 to 4 for AVX2 and Arm Neon
Tested on AWS c6g.xlarge and c6i.xlarge instances, this improved GFLOPS on the `bench_gemm` matrix-vector product case by 2-3 GFLOPS. In a Whisper decoder benchmark, this reduced decoding time by ~2.5%.

Tweak vector-matrix microkernel

---

src/gemm.rs
src/ops/matmul.rs
src/ops/rnn.rs

When packing the RHS input for matrix multiplication, `b.rows()` is the same as `a.cols()`, so this argument is redundant. More importantly, it removes an apparent dependence on knowing the size of the LHS matrix when prepacking the RHS.

Remove redundant `a_cols` argument from `prepack_b`

---

src/graph.rs
src/ops/mod.rs
src/ops/resize.rs

This eliminates some unnecessary allocations and copies in `Graph::run`:
- Avoid an unnecessary clone of operator inputs when creating an `InputList` for an operator
- Use `with_capacity` to correctly size allocations up-front
- Avoid adding all the graph constants to a NodeId -> Input hash map at the start of each `Graph::run`. Instead look up the constant node and produce an `Input` just before the operator is called

Reduce allocations / copies in `Graph::run`

---

Cargo.lock
Cargo.toml
rten-tensor/src/layout.rs
src/graph.rs

This is a collection of small optimizations for graph executions with many operations relative to compute. These were found by profiling main-thread execution time of the [whisper-rs](https://github.com/igor-yusupov/comparisons-rten/tree/main/whisper/whisper-rs) demo.

Optimize node ID hashing, `DynLayout` construction

---

Makefile
rten-vecmath/src/simd_vec.rs
rten-vecmath/src/simd_vec/aarch64.rs
rten-vecmath/src/simd_vec/wasm.rs
rten-vecmath/src/simd_vec/x86_64.rs
src/gemm.rs
src/gemm/kernels.rs

Add an alternate case where the matrix is transposed (unit row stride, non-unit column stride) as well as a general case when neither the row nor column strides are 1.
The immediate use case is a model which runs LSTM ops with a sequence length of 1. This results in a vector-matrix product operation where the weight matrix is transposed.
- Add `SimdFloat::sum` to horizontally sum SIMD vectors
- Generalize the vector-matrix product path to support B matrices with arbitrary strides. This is split into two cases, one for a transposed matrix, and one for when neither the row nor column stride is 1

Support matrices with non-unit column stride in vector-matrix products

---

src/ops/generate.rs

Just initialize the buffer once with the "off" value.

Avoid potentially redundant zeroing of buffer in OneHot

---

Makefile
rten-cli/Cargo.toml
rten-examples/Cargo.toml
rten-vecmath/src/lib.rs
rten-vecmath/src/simd_vec.rs
rten-vecmath/src/simd_vec/aarch64.rs
rten-vecmath/src/simd_vec/wasm.rs
rten-vecmath/src/simd_vec/x86_64.rs
src/gemm.rs
src/gemm/kernels/x86_64.rs
src/ops/conv.rs
src/ops/conv/im2col.rs

Re-implement the fused im2col transform (`VirtualIm2Col`) used by convolutions, with SIMD operations. This helps by:
1. Computing the source offsets, gathering and storing multiple elements at once.
2. Eliminating unpredictable branches to determine whether an element is in the padding region or not. Instead predication is used.
3. Enabling the compiler to unroll inner loops by providing statically known loop counts.
On an Intel i5, this reduced time in im2col operations in Ocrs by about 35%, of which 10% comes from (3). The remaining time is almost all in copying memory. It might be possible to reduce that with prefetching.
---
*TODO:*

Accelerate im2col transform using SIMD

---

rten-examples/src/jina_similarity.rs
rten-tensor/src/lib.rs
rten-tensor/src/tensor.rs
src/graph.rs
src/lib.rs
src/ops/binary_elementwise.rs
src/ops/concat.rs
src/ops/conv.rs
src/ops/convert.rs
src/ops/gather.rs
src/ops/generate.rs
src/ops/identity.rs
src/ops/layout.rs
src/ops/matmul.rs
src/ops/mod.rs
src/ops/non_max_suppression.rs
src/ops/norm.rs
src/ops/operators.rs
src/ops/pad.rs
src/ops/pooling.rs
src/ops/random.rs
src/ops/reduce.rs
src/ops/resize.rs
src/ops/rnn.rs
src/ops/slice.rs
src/ops/split.rs
src/ops/trilu.rs
src/ops/unary_elementwise.rs
src/ops/variadic_elementwise.rs
src/tensor_pool.rs

Graph execution often spends a significant amount of time allocating or freeing large buffers using the system allocator. So far this is mitigated for some operators by running them in-place on the first input, however there are many important operations which cannot run in-place, and many cases where operators that can run in place do not because an input is needed by a subsequent operation.
This PR introduces a tensor buffer pool (`TensorPool`), which is created at the start of the graph run, and used by operators as an allocator for their outputs. Once a value is no longer needed by subsequent steps of graph execution, the buffer is added to the pool and made available for use by subsequent steps. New output has been added to the timing report enabled by `RTEN_TIMING`, reporting the …

Add buffer pool/arena to enable re-use of temporary buffers during graph execution

---

src/ops/binary_elementwise.rs
src/ops/concat.rs
src/ops/conv.rs
src/ops/layout.rs
src/ops/matmul.rs
src/ops/operators.rs
src/tensor_pool.rs
src/wasm_api.rs

Convert the `Reshape`, `MatMul`, `Where`, `Tile` and `ConvTranspose` operators to allocate from the shared pool.
In the process, add some general new facilities to `TensorPool`:
- The ability to allocate an empty `Vec` with a given capacity
- A `PoolRef` smart pointer which wraps a tensor and returns it to the pool when it goes out of scope. This is useful for temporary buffers allocate within operators, such as the col2im matrix in `ConvTranspose`.

Convert operators to use tensor pool, part 2

---

src/ops/variadic_elementwise.rs

The typed `min` and `sum` functions worked correctly, but the `Min` and `Sum` types that wrapped them always called `max` (!).
This was noticed while converting these ops to allocate output buffers from the pool.

Fix `Min`, `Sum` operators and convert variadic reduction ops to use the pool

---

rten-tensor/src/tensor.rs
src/ops/convert.rs
src/ops/norm.rs
src/ops/unary_elementwise.rs

Add a `TensorBase::map_buf` API as a variant of `TensorBase::map` which allows an output buffer to be passed, and use it to convert unary operators to allocate from the pool.

Convert unary operators to allocate from pool

---

rten-examples/src/yolo.rs
rten-tensor/src/tensor.rs
rten-tensor/src/transpose.rs
src/ops/identity.rs
src/ops/norm.rs
src/ops/operators.rs
src/ops/slice.rs

Add `TensorBase::to_tensor_buf` API that makes it possible to create a contiguous copy of a tensor/view with a pre-allocated output buffer, and use it to convert the `Identity`, `BatchNormalization`, `Slice`, `Softmax`, `LogSoftmax` and `InstanceNormalization` ops to allocate from the pool.

Convert tensor copies to allocate from pool

---

src/ctc.rs
src/ops/generate.rs
src/ops/norm.rs
src/ops/operators.rs
src/ops/pad.rs
src/ops/random.rs
src/ops/reduce.rs
src/ops/trilu.rs

Continue converting operators to allocate from the pool instead of the global allocator.

Convert reduction ops, LayerNormalization, OneHot, Trilu, Pad, RandomUniform to allocate from pool

---

src/gemm.rs
src/ops/layout.rs
src/ops/matmul.rs

While converting the Gemm operator, also modify it to avoid redundant zeroing of the output buffer if `beta` is zero. The same optimization was applied to the MatMul operator previously.

Convert Gemm, Expand ops to use pool

---

src/ops/conv.rs
src/ops/norm.rs
src/tensor_pool.rs

Ensure the temporary values created in this op are added back to the pool instead of being de-allocated by the global allocator when no longer needed.
In the process I added some new APIs to make code using `PoolRef` more readable.

Return temporary tensors to pool in LayerNormalization op

---

src/graph.rs
src/ops/binary_elementwise.rs
src/ops/concat.rs
src/ops/convert.rs
src/ops/identity.rs
src/ops/layout.rs
src/ops/mod.rs
src/ops/norm.rs
src/ops/slice.rs
src/ops/unary_elementwise.rs

When an operator's `run_in_place` impl falls back to allocating a new tensor instead of mutating the input, allocate the new output buffer from the pool.
This was straightforward for most operators, but I left `TODO`s for a couple of the layout operations where modifying the fallback to use the pool is a bit more involved.
Part of https://github.com/robertknight/rten/issues/109.

Allocate from pool if needed in `Operator::run_in_place` impls

---

rten-tensor/src/lib.rs
rten-tensor/src/tensor.rs
src/ops/binary_elementwise.rs
src/ops/concat.rs
src/ops/convert.rs
src/ops/gather.rs
src/ops/generate.rs
src/ops/identity.rs
src/ops/layout.rs
src/ops/norm.rs
src/ops/operators.rs
src/ops/pad.rs
src/ops/reduce.rs
src/ops/slice.rs
src/ops/split.rs
src/ops/trilu.rs
src/ops/unary_elementwise.rs
src/ops/variadic_elementwise.rs
src/tensor_pool.rs

Overhaul the TensorPool implementation and related APIs to fix unsoundness, remove `Any` bounds that infected all the operators, and align more closely with how allocator APIs work in nightly std.
- Change TensorBase methods to have an `_in` suffix rather than `_buf` and take an
allocator as an argument rather than a buffer. The allocator is needed for
methods which conditionally allocate, and it avoids repeated code for other
cases to have the method determine the allocation size rather than the caller.
- Rework TensorPool for better soundness and more flexibility, by removing the
`T: Any + Copy` constraint.
Instead of storing `Vec<MaybeUninit<T>>`s in `Box<dyn Any>` wrappers in the
pool, extract the underlying parts of the `Vec` and store those in a `Buffer`
struct. When dropped, …

Overhaul tensor APIs that take an output buffer

---

rten-tensor/src/tensor.rs
src/graph.rs
src/ops/binary_elementwise.rs
src/ops/concat.rs
src/ops/conv.rs
src/ops/gather.rs
src/ops/generate.rs
src/ops/layout.rs
src/ops/matmul.rs
src/ops/non_max_suppression.rs
src/ops/pad.rs
src/ops/pooling.rs
src/ops/random.rs
src/ops/reduce.rs
src/ops/resize.rs
src/ops/slice.rs
src/ops/split.rs
src/ops/trilu.rs
src/ops/unary_elementwise.rs
src/ops/variadic_elementwise.rs
src/tensor_pool.rs

This PR refines the APIs and use of the tensor pool for allocations:
- The `TensorPool::{alloc, alloc_zeroed}` methods have been removed in favor of more `_in`-suffixed APIs on `TensorBase`: `zeros_in`, `uninit_in`, `full_in`
- Some uses of `TensorPool::add` have been replaced with `tensor.auto_return`, which is more ergonomic to use
- The docs and tests have been updated to reflect the now-preferred usage patterns

Refine tensor pool APIs and usage

---

src/env.rs
src/graph.rs
src/lib.rs
src/model.rs

Extract a helper function for testing the state of feature flags in env vars, and change the default for `RTEN_USE_POOL` to true.
The flag has been kept around rather than removing it entirely to make it convenient to measure its impact.
This is the last part of https://github.com/robertknight/rten/issues/109.

Enable `RTEN_USE_POOL` by default

---

tools/ort-infer.py

This script functions similarly to the rten-cli crate in that it prints some metadata about the model, evaluates it with randomly generated inputs and then prints some timing statistics.
I've left commented out code to toggle the various optimization flags. This is helpful to find out which are most impactful for a particular model.

Add Python script to run inference using ONNX Runtime

---

src/gemm.rs
src/graph.rs
src/ops/conv.rs
src/ops/matmul.rs
src/ops/rnn.rs
src/tensor_pool.rs

- Generalize `PoolRef` and associated traits to work with data containers other than `TensorBase`. `PoolRef` now works with any container that impls `ExtractBuffer` to extract its buffer as a `Vec<T>`
- Support allocating prepacked matrices from, and return them to, a pool by adding `GemmExecutor::{prepack_a_in, prepack_b_in}` and implementing `ExtractBuffer` for `PackedAMatrix` and `PackedBMatrix`
Fixes https://github.com/robertknight/rten/issues/128

Allocate buffers for prepacked matrices from pool

---

rten-vecmath/src/exp.rs
rten-vecmath/src/lib.rs
rten-vecmath/src/simd_vec.rs
rten-vecmath/src/simd_vec/x86_64.rs
rten-vecmath/src/softmax.rs

Support AVX-512 for Exp, Sigmoid, Tanh, Erf, Softmax and other operators which use SIMD-accelerated implementations in rten-vecmath.
The performance benefit is small because these operations are limited by memory bandwidth, but doing this revealed some issues with supporting different instruction sets on the same architecture. Usage of `#[inline]` and `#[target_feature]` had to be corrected to ensure that SIMD intrinics are actually inlined reliably. Otherwise the function call overhead negates the benefits of SIMD entirely.
The `SimdInt` and `SimdFloat` docs have been updated to explain the rules around inlining and target features.

Support AVX-512 for SIMD unary operators, softmax

---

rten-convert/rten_convert/converter.py
rten-convert/rten_convert/schema_generated.py
rten-tensor/src/tensor.rs
src/model.rs
src/model_builder.rs
src/ops/mod.rs
src/ops/reduce.rs
src/ops/unary_elementwise.rs
src/schema.fbs
src/schema_generated.rs
tools/ort-infer.py

This addresses a few issues I found while playing around with ONNX models from openpilot:
- Support the `Elu` activation operator
- The latest versions of the `Reduce*` operators take `axes` as a dynamic input rather than static attribute.
- Enable the `ort-infer.py` script to run with models that have `float16` inputs
For RTen, the original `supercombo.onnx` model fails to convert because the weights are in float16 format. However this hack works (at least for getting the model to run, I haven't verified the outputs):
```diff
diff --git a/rten-convert/rten_convert/converter.py b/rten-convert/rten_convert/converter.py
index 42b427a6..d4fe5f4e 100644
--- a/rten-convert/rten_convert/converter.py
+++ b/rten-convert/rten_convert/converter.py
@@ -426,6 +426,9 @@ def …
```

Support `Elu` operator, reading axes list from inputs rather than attribute in `Reduce*` ops

---

rten-vecmath/src/erf.rs
rten-vecmath/src/tanh.rs

Remove the `#[target_feature]` attributes from the generic erf, tanh functions. Previously they were being compiled with AVX2 instructions even when called from the fallback (non-AVX2) dispatch.
This change follows the pattern established in
https://github.com/robertknight/rten/pull/131, which fixed the issue for Exp, Sigmoid and Softmax operators.
Downstream issue: https://github.com/robertknight/ocrs/issues/52 (see my notes here for steps to reproduce)
Together with https://github.com/robertknight/rten/pull/131, this should fix https://github.com/robertknight/rten/issues/35.

Fix crash in `Erf`, `Tanh` operators under under pre-AVX2 x64 CPUs

---

tools/ort-infer.py

Example usage:
```
python tools/ort-infer.py convnext.onnx -d num_channels=3 -d height=224 -d width=224 -d batch_size=1
```

Support specifying dynamic dimension sizes in ort-infer.py

---

src/ops/pooling.rs

Generalize the existing parallel MaxPool implementation and use it to implement both MaxPool and AveragePool. This should generalize to LpPool in future too. The result is still far from optimal, but it serves as a starting point for implementing pooling ops for each reduction type (max, average, lp) and future data type.
On a Yolov9e ONNX model taken from [HuggingFace](https://huggingface.co/Xenova/yolov9-onnx/blob/main/yolov9-e.onnx) this reduces time in AveragePool ops by about 2x on my system (30ms -> 14ms with a 256x256 input).

Parallelize AveragePool op

---

Cargo.lock
Cargo.toml
rten-convert/rten_convert/converter.py
rten-convert/rten_convert/schema_generated.py
src/model.rs
src/model_builder.rs
src/ops/mod.rs
src/ops/operators.rs
src/ops/random.rs
src/schema.fbs
src/schema_generated.rs

`RandomNormal` uses the `RngExt::f32_normal` implementation from `fastrand-contrib`, which uses the Box-Muller transform [1] algorithm.
[1] https://en.wikipedia.org/wiki/Box–Muller_transform
**TODO:**

Implement RandomUniformLike, RandomNormal, RandomNormalLike

---

src/lib.rs
src/model.rs

Refactor deserialization of operators to reduce boilerplate.
Combine the separate `DefaultOperatorFactory` trait and function for deserializing the `schema_generate::OperatorNode` struct. There is now a single `ReadOp` trait with a method for deserializing an `OperatorNode`.

Refactor operator attribute deserialization

---

rten-convert/rten_convert/schema_generated.py
src/model.rs
src/model_builder.rs
src/ops/mod.rs
src/ops/unary_elementwise.rs
src/schema.fbs
src/schema_generated.rs

The ONNX spec states that the input must be 1D tensor, but that looks like a mistake [1] and the restriction is not implemented here.
The corresponding PyTorch operator [2] reverts to a linear function for inputs above a threshold, but the ONNX spec makes no mention of this and ONNX Runtime doesn't, so that is not implemented here either.
[1] https://github.com/onnx/onnx/issues/2563
[2] https://pytorch.org/docs/stable/generated/torch.nn.Softplus.html

Implement Softplus op

---

rten-tensor/src/storage.rs

This provides the missing `IntoStorage` impl for `Cow<'a, [T]>`, found while updating Ocrs for recent RTen API changes.

Add blanket `IntoStorage` impl for `T: Storage`

---

rten-vecmath/src/simd_vec.rs
rten-vecmath/src/simd_vec/aarch64.rs
rten-vecmath/src/simd_vec/wasm.rs
rten-vecmath/src/simd_vec/x86_64.rs
src/ops/conv/im2col.rs

- Add `SimdMask` trait for common operations on SIMD masks, eg. bitwise AND and OR.
- Make an assumption that the SIMD mask type is always the same for a particular architecture and lane size. eg. Assume that i32xN and f32xN will use the same mask type. This avoids the need for casting masks.
- Add `SimdVal` base trait which can house associated types and methods that are common to all SIMD vectors, regardless of element type.
Initially this just defines the associated mask type, but in future it could also provide operations such as loading and storing values, and bitwise operations.

Revise SIMD traits to make working with masks more ergonomic/efficient

---

rten-tensor/src/storage.rs
rten-tensor/src/tensor.rs

This is useful for code which needs to conditionally copy or create a tensor, and then get the results of the copying and non-copying code paths into the same type. See https://github.com/robertknight/ocrs/pull/57 for a downstream solution that can be replaced by this.

Add `TensorBase::{as_cow, into_cow}`

---

rten-convert/rten_convert/converter.py
rten-convert/rten_convert/schema_generated.py
rten-tensor/src/iterators.rs
rten-tensor/src/tensor.rs
src/model.rs
src/model_builder.rs
src/ops/gather.rs
src/ops/mod.rs
src/schema.fbs
src/schema_generated.rs

Add an unoptimized `GatherND` implementation, along with some new `TensorBase` methods to support the implementation.
This is one of three changes needed to run Piper TTS models, the others being support for 1D ConvTranspose with padding, and bug fixes for `ScatterND`.
**TODO:**

Implement `GatherND` operator

---

src/ops/gather.rs

From the [spec](https://onnx.ai/onnx/operators/onnx__ScatterND.html):
> updates is treated as a (q-1)-dimensional tensor of replacement-slice-values.
> Thus, the first (q-1) dimensions of updates.shape must match the first
> (q-1) dimensions of indices.shape. The remaining dimensions of updates
> correspond to the dimensions of the replacement-slice-values
The previous version was wrong, but by serendipity happened to work for existing test cases.
Fix fixes a crash in the `ScatterND` op I encountered when testing Piper TTS models (see https://github.com/robertknight/rten/pull/155).
**TODO:**

Fix `update_slice_len` calculation in ScatterND

---

rten-convert/rten_convert/converter.py
rten-convert/rten_convert/schema_generated.py
src/model.rs
src/model_builder.rs
src/ops/conv.rs
src/ops/mod.rs
src/schema.fbs
src/schema_generated.rs

- 1D ConvTranspose is handled the same way as for Conv, by inserting a dummy 1-sized height dimension, performing a 2D ConvTranspose and removing it afterwards.
- Padding for ConvTranspose has the effect of removing rows and columns from the output. This is handled by the col2im transform.
This is one of three changes needed to support Piper TTS models. See https://github.com/robertknight/rten/pull/155.

Support padding and 3D (NCW) inputs for `ConvTranspose` op

---

rten-convert/rten_convert/schema_generated.py
src/schema.fbs
src/schema_generated.rs

The default value of the `PadMode` enum is `Same`, so we need to override that to `Fixed` in `ConvTransposeAttrs` to preserve existing behavior in models converted before the `pad_mode` attr was added.
This is unfortunately a rather easy mistake to make. An alternative option would be to default `pad_mode` to `null`, which will map to `Option<PadMode>` in Rust.

Fix backwards compatibility of `ConvTranspose` deserialization

---

Cargo.lock
rten-examples/Cargo.toml
rten-examples/README.md
rten-examples/src/piper.rs

This uses Piper voice models to convert strings of phonemes to audio in .wav format. The demo takes phonemes rather than text as input to simplify creating this first version. The Piper project uses a non-trivial C++ library to handle text-to-phoneme conversion, which I didn't want to add as a dependency.
Sample output:
[tts-demo.zip](https://github.com/robertknight/rten/files/15258343/tts-demo.zip)

Add Piper text-to-speech demo

---

rten-tensor/src/storage.rs

For some reason I incorrectly assumed this was checked when a `Range` was constructed, but of course that isn't true since the `start` and `end` are just public fields.

Check storage start offset is in-bounds

---

rten-vecmath/src/erf.rs
rten-vecmath/src/exp.rs
rten-vecmath/src/lib.rs
rten-vecmath/src/softmax.rs
rten-vecmath/src/tanh.rs

Revise dispatch of SIMD-vectorized unary functions and softmax to be done using a function parameterized by an operator type, instead of using a macro. The operator type implements an `eval` method that is instantiated with the various different SIMD types available on the current platform, and the dispatch function picks the appropriate one at runtime.
The main reason for this is that it enables vectorizing unary and reduction/normalization ops that have additional attributes/parameters, as these can be added to the operator type. Generally functions are also just nicer to work with than a complex macro.

Change SIMD op dispatch to use functions rather than macros

---

rten-tensor/src/copy.rs
rten-tensor/src/lib.rs
rten-tensor/src/tensor.rs

Replace the slow iterator-based fallback in `TensorBase::copy_from` with a much faster version which uses nested loops over the innermost 4 dimensions.
This reduces time in the `Pad` operator from ~4.5ms to ~0.8ms in Piper TTS models. That operator used the fallback because it creates a non-contiguous view of the non-padded region into which it copies the source.

Optimize `TensorBase::copy_from` for non-contiguous `self`

---

src/gemm.rs
src/gemm/packing.rs
src/ops/conv/im2col.rs

This adds a couple of further optimizations for im2col:
- Avoid redundant zeroing.
If the packing buffer needed for im2col operations needs to be resized, avoid zeroing it, since the packing code will overwrite all elements.
As part of this change, change the callers of the packing functions in `gemm.rs` to always pass an output slice of exactly the correct size, avoiding the need for each packing function to zero unused space at the end, in order to fulfill the contract that the entire slice is initialized after the packing code returns. Previously gemm.rs would always pass an output slice of the same size for every block to be packed. However the last row/column block may be smaller, with unused space at the end.
- Improve efficiency of lookup table construction in `VirtualIm2Col::new`. …

Optimize im2col - avoid redundant zeroing of packing buffer, improve lookup table construction

---

src/ops/gather.rs
src/ops/reduce.rs

- Fix oversight where `Gather` op did not allocate from the pool in its fast path
- Make `NonZero` op allocate from the pool for its output. This operator is still not fully using the pool as it first builds up a `Vec` of all the non-zero entries, which it then transposes and copies into a contiguous tensor. Only the final copy is using the pool.

Allocate output from pool in `Gather`, `NonZero` ops

---

src/graph.rs
src/timing.rs

These allocations contributed to the un-accounted for ("[Other]") time during graph execution.

Avoid operator node/name cloning during record collection

---

rten-tensor/src/errors.rs
rten-tensor/src/layout.rs
rten-tensor/src/tensor.rs

Failing to check the requirements for length match or contiguity when reshaping
is a sure fire way to cause OOB reads.
- Change `TensorBase` to call `MutLayout::reshaped` to ensure the new
shape is checked for compatibility with the existing layout length
and contiguous-ness.
- Change reshaping methods in `layout.rs` to return results, as these
are more convenient to work with in tests.
- Remove unused mutating `Layout::reshape` methods

Add missing checks for length match in reshaping methods

---

rten-tensor/src/tensor.rs

This is a follow-up to https://github.com/robertknight/rten/pull/170 for in-place reshaping.
It will probably make sense to propagate the error to callers, even though most will `unwrap`/`expect` it. That's a potentially more disruptive API change however.

Check new shape length in `TensorBase::reshape`

---

rten-tensor/src/copy.rs
rten-tensor/src/iterators.rs
rten-tensor/src/layout.rs
rten-tensor/src/slice_range.rs
rten-tensor/src/tensor.rs
src/ops/reduce.rs
src/ops/rnn.rs
src/ops/slice.rs

Improve the efficiency of the `Slice` operator by:
- Allocating the output buffer from the pool. I missed this previously for the fast path, used when the slice ranges don't contain negative strides
- Rewriting the fallback implementation used when the range contains negative steps. This is now implemented by a new `TensorBase::slice_copy` API, which uses nested loops with a fixed number of inner dims (4) instead of external iteration with a dynamic number of dims.
In the process I found and fixed some bugs in the handling of negative steps in `SliceRange::resolve`, as well as a missing layout + data length compatibility check in `TensorBase::into_shape`.
Combined these reduce time in `Slice` ops in Piper TTS models from ~3.1ms to ~0.9ms.
**TODO:**

Improve `Slice` op efficiency

---

rten-vecmath/README.md
rten-vecmath/src/lib.rs

The main change since the initial release is that the SIMD types are now exported and used by other crates.

Update README and docs for the rten-vecmath crate

---

Cargo.lock
Cargo.toml
rten-cli/src/main.rs
rten-examples/Cargo.toml
rten-examples/src/bert_qa.rs
rten-examples/src/deeplab.rs
rten-examples/src/depth_anything.rs
rten-examples/src/detr.rs
rten-examples/src/imagenet.rs
rten-examples/src/jina_similarity.rs
rten-examples/src/piper.rs
rten-examples/src/wav2vec2.rs
rten-examples/src/yolo.rs
src/constant_storage.rs
src/graph.rs
src/lib.rs
src/model.rs
src/wasm_api.rs

Previously loading a model involved two steps, each of which copied the entire
model:
1. Reading the file from disk into a `Vec<u8>`, eg. using
`std::fs::read`
2. `Model::load` then received a `&[u8]` slice of this and would copy
the weights into individual owned tensors.
Usually callers would then not immediately free the buffer loaded in step (1),
so the program would use twice as much memory as needed for the weights.
This commit revises the model loading API to be more convenient to use for
common use cases and more efficient:
- The `Model::load` API now takes a `Vec<u8>` rather than `&[u8]`.
`Model` then puts this `Vec<u8>` into a reference-counted container and graph
nodes reference slices of this. This avoids an expensive copy of all the
model weights.
- Add a `Model::load_file` …

Revise model loading API for ease of use and efficiency

---

rten-cli/src/main.rs

This is useful to easily check whether the installed tool is current / in-sync with what a particular project is using.

Add `--version` flag to rten CLI

---

Cargo.lock
Cargo.toml
docs/performance.md
src/graph.rs
src/lib.rs
src/ops/operators.rs
src/threading.rs

Since RTen model execution is limited by CPU and memory bandwidth rather than IO, using more threads than there are physical cores is usually slower and always inefficient.
The thread pool is exposed via `rten::threading::thread_pool` so downstream crates can run their own tasks in this pool. 
Fixes https://github.com/robertknight/rten/issues/105
**TODO:**

Set number of threads to match physical rather than logical core count

---

src/ops/operators.rs

These impls had to be separate when `NdTensor` and `Tensor` were entirely separate types. Now that they share a common type parametrized by a layout, we can combine the corresponding trait impls in operators.rs.

Unify `Operators`, `FloatOperator` impls for static and dynamic-rank tensors

---

README.md
js-examples/image-classification/README.md
js-examples/image-classification/package-lock.json
src/graph.rs
src/lib.rs
src/ops/operators.rs
src/threading.rs

Make `threading::thread_pool` return a wrapper around the underlying `rayon::ThreadPool` which has a fallback for platforms where Rayon cannot build a thread pool, eg. WebAssembly.

Add fallback for platforms where Rayon cannot construct a thread pool

---

rten-vecmath/src/lib.rs
src/gemm/kernels/wasm.rs
src/ops/conv/im2col.rs

Attempting to use the WASM SIMD kernels if compiling without WASM SIMD enabled (`simd128` target feature) results in code that runs *very* slowly, because every single call to a WASM SIMD intrinsic becomes a non-inlined fallback function call.
Ideally I'd like to drop non-SIMD support, but support was added in Safari 16.4 which is still quite recent (March 2023), so I'm not sure if I should to that yet.

Don't use WebAssembly SIMD kernels if `simd128` feature is disabled

---

rten-tensor/src/tensor.rs
src/gemm.rs
src/graph.rs
src/ops/concat.rs
src/ops/conv.rs
src/ops/gather.rs
src/ops/matmul.rs
src/ops/rnn.rs
src/ops/unary_elementwise.rs
src/tensor_pool.rs

When operators conditionally copy inputs to make them contiguous via `Tensor::to_contiguous`, allocate buffers from and return them to the pool. This avoids the overhead of allocating / freeing these large buffers using the system allocator.
- Add `TensorBase<CowData<_>, _>::into_non_contiguous_data` and `TensorBase::to_continuous_in`
- Fix some comments in `tensor.rs` which referred to an earlier iteration of the `TensorBase` APIs that now accept an allocator
- Make `ExtractBuffer::extract_buffer` return an `Option<Vec<T>>` instead of a `Vec<T>` to support uses with maybe-owned storage types
- Change uses of `input.to_contiguous()` to `input.to_continuous_in(pool).auto_return(pool)`

Allocate buffers from the pool when conditionally copying them

---

src/gemm.rs
src/ops/rnn.rs

Apply a change similar to 2f0327c8fc3f41a772c2f5b9f7bec7a082efd725 by combining the separate matrix multiplications for the 3 gates into a single matmul. This reduces the total number of matmuls from `num_directions * seq_length * 6` to `num_directions * seq_length * 2`.
Using only two matmuls is only possible when `linear_before_reset=true`, as is the case all models I have worked with so far, since it is what PyTorch and cuDNN support and what TensorFlow uses by default. With the GRU formulation in the original paper, an additional matmul is required since the reset gate has to be computed before the `hidden_state @ hidden_weights[hidden_gate]` matmul can be done.
Fixes https://github.com/robertknight/rten/issues/85
**TODO:**

Combine matmuls for GRU gates

---

src/ops/rnn.rs

When the batch size is > 1, slices of the `gates` scratch space to extract specific gates are non-contiguous, which makes `sigmoid_in_place` and `tanh_in_place` much slower. See https://github.com/robertknight/rten/issues/192. The GRU op had a workaround by using the non-in-place `tanh` instead. This applies the same solution to the sigmoid activation in the GRU op and all activations in the LSTM op.

Copy gates in LSTM, GRU ops before applying activations

---

src/gemm.rs
src/gemm/packing.rs
src/ops/conv.rs
src/ops/conv/depthwise.rs
src/ops/conv/im2col.rs
src/ops/pooling.rs

Refactor depthwise convolution to make it easier to improve later.
- Extract depthwise conv into sub-module
- Remove `add_scaled_vector`, as it was only used in one place (the depthwise conv inner loop) and that has now been replaced
- Replace `div_ceil`, `round_up` utilities with stdlib methods (requires Rust >= 1.73)

Extract depthwise conv into separate module

---

Cargo.toml
rten-examples/Cargo.toml
rten-imageproc/Cargo.toml
rten-imageproc/src/math.rs
rten-imageproc/src/shapes.rs
rten-text/Cargo.toml

Adding "serde_traits" cargo feature to rten-imageproc to implement Serialize and Deserialize on the public-facing shape types.
Also synchronizing serde & serde json versions across sub-crates
This relates to https://github.com/robertknight/rten/issues/179
Thank you.

Adding "serde_traits" optional cargo feature to rten-imageproc

---

rten-convert/rten_convert/converter.py

A missing `perm` attr signals that the input dimensions should be reversed.  The converter translated a missing `perm` attr into an empty permuation list instead of `None`, causing the operator to fail with an "Invalid permutation" error.
Tested with the `decoder_model.onnx` model from https://huggingface.co/Mozilla/distilvit/tree/main/onnx.

Fix conversion of `Transpose` operator with missing `perm` attr

---

rten-cli/src/main.rs
src/graph.rs
src/timing.rs

- The `n_iters` flag is useful for assessing the initial run vs "warmed up" inference times for models
- The constant propagation step is useful to highlight where models have unnecessary operators in them that could be eliminated by a graph optimization (ORT does this automatically)

Add `--n_iters` flag to CLI and perform constant propagation before running model

---

src/ops/matmul.rs

The `MatMul` operator has an optimization for the case when the LHS is a batch and the RHS is a single matrix. In that case the LHS is reshaped into a single matrix, the matmul is done and the output is reshaped to re-add the batch dims. This is pointless if the LHS is a batch of size 1 though.
Change this so we decide based on batch sizes rather than dimension count. This doesn't have a meaningful performance impact as reshaping is cheap, it is just makes more sense conceptually.

Use reshape strategy in `MatMul` based on batch size rather than dims

---

rten-cli/src/main.rs
rten-tensor/src/copy.rs
rten-tensor/src/layout.rs
rten-tensor/src/storage.rs
rten-tensor/src/tensor.rs
src/ops/concat.rs

The `Concat` operator had a fallback to a slow iterator-based copy when the source was not contiguous. Extend the machinery for efficient copying of non-contiguous views in rten-tensor and use that instead.
- Add `TensorBase::split_at_mut` and make `TensorBase::init_from` work when `self` is a mutable view
- Change `Concat` to use `split_at_mut` + `init_from` to fill the output, instead of using an iterator

Optimize `Concat` for non-contiguous inputs

---

src/graph.rs
src/lib.rs

Export the error type returned by `Model::run`, so that consumers can match on it.

Export `RunError`

---

rten-tensor/src/iterators.rs
rten-tensor/src/storage.rs
rten-tensor/src/tensor.rs
src/ops/concat.rs

Re-implement `TensorBase::{axis_chunks, axis_chunks_mut}` on top of `TensorBase::{split_at, split_at_mut}`. This preserves the source view's layout type in the item type, is more efficient and avoids unsafe code in the implementation.
In the process `split_at_mut` was changed to take `self` rather than `&mut self`, to enable it to preserve the view lifetime in the result. This is convenient for the pattern in the `AxisIterMut` implementation where the tail is repeatedly split into `(current_chunk, remainder)`.

Make `TensorBase::{axis_chunks, axis_chunks_mut}` preserve layout

---

rten-tensor/src/layout.rs
rten-tensor/src/storage.rs
src/ops/resize.rs

The `Resize` operator was already parallel over groups of channels, but this doesn't help when resizing large greyscale/RGB/RGBA images. Improve this by making the operator parallel over rows as well.
When testing with Ocrs I found a problem with `TensorBase::split_at` when the dimension being split has a size of 1, the `mid` value is 1 and the stride is larger than the storage length. In this case `Layout::split` would return an out-of-bounds storage range for the right split, causing a panic in `ViewData::split`. Fix this by choosing a start/end offset for the empty right split that we know must be in-bounds.

Make `Resize` operator parallel over rows

---

Cargo.lock
Cargo.toml
rten-examples/Cargo.toml
rten-imageio/Cargo.toml

The latest release includes a much faster JPEG decoder, which makes loading images via `rten-imageio` helpers more efficient.

Update `image` dependency

---

rten-tensor/src/iterators.rs
rten-tensor/src/layout.rs
rten-tensor/src/tensor.rs
src/ops/conv.rs
src/ops/pooling.rs

Make the iterator returned by `axis_iter` yield static-rank views if `self` has a static rank. The implementation uses a specialized slicing implementation which is much more efficient than `TensorBase::slice`, especially for static-rank tensors.
These changes make it possible for operator implementations to use this iterator more in inner loops.

Make `TensorBase::axis_iter` yield static-rank views if receiver has static rank

---

tools/ort-infer.py

Add notes on more optimization controls that ORT has. The main one I noted doing some profiling is that it prepacks weights by default when a model is loaded.

Add more notes on ORT optimization controls

---

src/ops/binary_elementwise.rs
src/ops/variadic_elementwise.rs

Assuming that variadic operators like `Sum`, `Mean` etc. are most often called with two or a small number of operands, re-using the optimized code for binary operators will be much more efficient than iterators.
Part of https://github.com/robertknight/rten/issues/189.

Re-implement variadic ops as a series of binary ops

---

rten-tensor/src/iterators.rs
rten-tensor/src/lib.rs
rten-tensor/src/tensor.rs
src/ops/binary_elementwise.rs

Re-implement the slow path in the `Where` operator to use a code pattern similar to that added for binary ops in https://github.com/robertknight/rten/pull/190.
This replaces the last usage of the `TensorBase::broadcast_iter` method, so that code has been removed from rten-tensor. Any code outside the rten crates needing to broadcast tensors should be migrated to `TensorBase::broadcast`.
Fixes https://github.com/robertknight/rten/issues/189

Re-implement `Where` operator fallback

---

rten-tensor/src/iterators.rs
rten-tensor/src/lib.rs
rten-vecmath/src/lib.rs
src/number.rs
src/ops/mod.rs

- Remove `Offsets` type from the rten-tensor public API, as it isn't used by any other crates in this repo
- Address a few warnings and clippy suggestions after updating to Rust v1.78

Un-export `Offsets` type, address warnings from Rust v1.78

---

Cargo.lock
Cargo.toml
Makefile
src/schema_generated.rs

- Update flatbuffers crate
- Regenerate schema using a `flatc` version that matches the flatbuffers crate (`make schema`)
- Adjust `Makefile` so that `make schema` is no longer the default target
The main change to the generated code is the additional of an `Allocator` trait to various types.

Update FlatBuffers and regenerate schema

---

rten-convert/rten_convert/converter.py
rten-convert/rten_convert/schema_generated.py
src/model.rs
src/model_builder.rs
src/schema.fbs
src/schema_generated.rs

Rename the `pad_mode` attribute to `auto_pad` to match the corresponding
attribute in the ONNX specs. Also this avoids confusion with the `mode` property
for the `Pad` operator. This is backwards compatible since only the field and
enum names are changed, not the values.

Align `auto_pad` operator attribute name with ONNX

---

src/ops/binary_elementwise.rs

- Allocate output buffer from pool in non in-place variant
- Use the local `powf` function with fast paths for squaring and cubing when the exponent tensor is not a scalar
The first of these changes addresses the unexpected amount of time spent in `Pow` ops in https://github.com/robertknight/rten/pull/218.

Optimize `Pow` operator

---

rten-simd/src/arch/aarch64.rs
rten-simd/src/arch/scalar.rs
rten-simd/src/arch/wasm.rs
rten-simd/src/arch/x86_64.rs
rten-simd/src/lib.rs
rten-simd/src/vec.rs
src/gemm/kernels.rs
src/gemm/kernels/aarch64.rs
src/gemm/kernels/wasm.rs
src/gemm/kernels/x86_64.rs
src/ops/conv/im2col.rs

The im2col implementation had some constants with a non-obvious connection to the `NR` values used by GEMM kernels. Revise the code to make the connection more obvious. Also this makes it easier to experiment with different NR/MR sizes for microkernels. Changing these now requires updating the two constants in the GEMM kernel plus the corresponding const in `rten::ops::conv::im2col`.

Clarify where im2col panel width / `NR_REGS` values come from

---

rten-tensor/src/copy.rs
rten-tensor/src/iterators.rs
rten-tensor/src/overlap.rs
rten-tensor/src/tensor.rs

Replace iterators with a pattern that uses a fixed number of nested loops. The same approach was previously applied to binary and ternary ops.
Part of https://github.com/robertknight/rten/issues/192.
**Benchmark:**
```rs
let mut x = Tensor::arange(0., 1024., None).into_shape([32, 32]);
x.clip_dim(1, 2..30);
let start = std::time::Instant::now();
for _ in 0..1000 {
x.apply(|x| x + 0.001);
}
let elapsed = start.elapsed().as_secs_f64() * 1000.0;
println!("duration {}", elapsed);
```
Before: 2.95ms
After: 0.5ms
Without the `clip_dim` call (making it contiguous): 0.22ms

Improve slow-path performance for unary ops

---

rten-imageio/src/lib.rs
rten-tensor/src/errors.rs
rten-tensor/src/lib.rs

This PR contains a collection of improvements to the rten-imageio crate to make it a bit more flexible and allow loading images in another thread.
- Replace the `Box<dyn Error>` error types with enums. Aside from
allowing more detailed inspection, the new error types are also
`Send`. This is convenient if a program wants to read images in
parallel with loading a model for example.
- Add some basic crate-level documentation to rten-imageio
- Expose a function that converts a `DynamicImage` to an `NdTensor`.
This fixes https://github.com/robertknight/rten/issues/39.
- Remove an unnecessary `to_tensor` call in `read_image`. This isn't needed any more as the `TensorBase::map` implementation is now faster on non-contiguous tensors.

Revise rten-imageio error types and documentation

---

rten-tensor/src/tensor.rs

Support all the numeric primitive types that are <= 64 bits + bool. I left out u128/i128 only because I don't see a need yet.

Make `NdTensor::from(nested_array)` work with more element types

---

rten-examples/Cargo.toml
rten-examples/README.md
rten-examples/src/generator.rs
rten-examples/src/gpt2.rs
rten-examples/src/gpt2_reference.py
rten-examples/src/lib.rs

Add a text generation / completion example using GPT-2. This also includes the start of some utilities to implement the generation loop for auto-regressive transformer models.
The initial version uses simple greedy sampling from the output logits. As a result, completions are prone to being repetitive. I plan to replace this with top-K sampling soon.
Example usage:
```
$ cargo run -r -p rten-examples --bin gpt2 gpt2_medium_onnx/model.rten gpt2_medium_onnx/tokenizer.json "Once fine day, in the middle of"
```
Output:
> Once fine day, in the middle of the night, I was sitting in my room, watching TV, when I heard a knock on the door. I opened it and there was a man

Add GPT-2 text generation example

---

rten-examples/Cargo.toml
rten-examples/README.md
rten-examples/src/distilvit.rs
rten-examples/src/generator.rs
rten-examples/src/gpt2.rs

This adds an image captioning demo which demonstrates using a multi-modal encoder-decoder setup. This currently uses some draft models from [Mozilla Firefox's alt-text generation](https://hacks.mozilla.org/2024/05/experimenting-with-local-alt-text-generation-in-firefox-nightly/) ([Hugging Face repo](https://huggingface.co/Mozilla/distilvit/tree/main)).
In the process the shared utilities in `rten-examples/src/generator.rs` have been expanded to support encoder-decoder models. I plan to extract these into a separate crate in future for wider reuse.

Add DistilViT image captioning demo

---

Cargo.lock
Cargo.toml
rten-examples/Cargo.toml
rten-examples/src/distilvit.rs
rten-examples/src/gpt2.rs
rten-examples/src/lib.rs
rten-generate/Cargo.toml
rten-generate/src/generator.rs
rten-generate/src/lib.rs

Add a new create which contains utilities for running the decoding loop for transformer decoder-only and encoder-decoder models. It could also be adapted to support other kinds of auto-regressive models in future.
The initial implementation assumes the model input and output names match the conventions of the Hugging Face's [Optimum ONNX exporter](https://huggingface.co/docs/optimum/en/exporters/onnx/overview). This can be made more flexible in time.

Extract `Generator` and `GeneratorUtils` into `rten-generate` crate

---

Cargo.toml
Makefile
rten-text/src/tokenizers/bpe.rs

- Enable all features that don't require nightly Rust when building for docs.rs. This should fix the broken link for `Model::load_mmap`
- Enable the `random` feature for `Random*` operators when building docs
- Fix strings being treated as Markdown syntax in BPE tokenizer docs

Fix documentation warnings and broken link on `docs.rs`

---

rten-examples/src/gpt2.rs
rten-generate/src/generator.rs
rten-generate/src/lib.rs
rten-generate/src/metrics.rs

Add an API to rten-generate which makes it easy to collect and report timing metrics, and modify the GPT-2 demo to show how to use it.
The metrics separate out the initial _warmup_ step from subsequent steps. This is because the first step does additional work (eg. constant propagation) which is reused in subsequent steps. This warmup step will be slower for most models, but especially for transformer encoder-decoder models where the first step will compute various cross-attention related nodes in the graph.
```shellsession
$ cargo run -r -p rten-examples --bin gpt2 gpt2_medium_onnx/model.rten gpt2_medium_onnx/tokenizer.json "Once fine day, in the middle of"
Compiling rten-generate v0.10.0 (/Users/robert/projects/rten/rten-generate)
Compiling rten-examples v0.3.0 …
```

Add timing metrics API to rten-generate

---

Cargo.lock
rten-examples/src/gpt2.rs
rten-generate/Cargo.toml
rten-generate/src/generator.rs
rten-generate/src/lib.rs
rten-generate/src/metrics.rs
rten-generate/src/sampler.rs

Add an API for samplers in rten-generate and an implementation of top-K sampling, which is used in the GPT-2 demo.

Support top-K sampling in rten-generate

---

rten-generate/src/generator.rs
rten-text/src/tokenizers.rs
rten-text/src/tokenizers/bpe.rs
rten-text/src/tokenizers/json.rs
rten-text/src/tokenizers/wordpiece.rs
rten-text/tests/reftest.rs

This PR solves a few connected issues with token ID decoding during generation:
- Previously any decoding errors in `TextGenerator::next` would cause the iterator to loop, accumulating additional tokens under the assumption that decoding had failed because it had produced an incomplete UTF-8 sequence. Decoding can fail for other reasons however, in which case the text decoder just gets stuck looping until the source generator yields no more tokens. This PR fixes `TextGenerator::next` to yield an error if decoding fails for reasons other than an incomplete UTF-8 sequence.
- rten-text didn't provide an API specifically for decoding a sequence of token IDs. Instead it had an API for returning the canonical string representations of each token ID. For the BPE tokenizer, this encoded string …

Improve handling of decoding errors and special tokens in `TextGenerator::next`

---

rten-simd/src/arch/x86_64.rs
rten-simd/src/span.rs
rten-tensor/src/copy.rs
rten-tensor/src/iterators.rs
src/gemm.rs

This addresses warnings from clippy added in Rust v1.79. See https://rust-lang.github.io/rust-clippy/master/index.html#/missing_transmute_annotations.

Explicitly specify generic args for `transmute` calls

---

rten-cli/src/main.rs
rten-examples/src/bert_qa.rs
rten-examples/src/detr.rs
rten-examples/src/jina_similarity.rs
rten-examples/src/piper.rs
rten-examples/src/yolo.rs
rten-generate/src/generator.rs
rten-tensor/src/errors.rs
rten-tensor/src/layout.rs
rten-tensor/src/tensor.rs
src/graph.rs
src/lib.rs
src/model.rs
src/ops/concat.rs
src/ops/mod.rs
src/wasm_api.rs

This PR contains a series of changes that speed up transformer decoder models significantly by reducing the cost of extending the KV-cache at each iteration from `O(sequence_len)` to `O(1)`.
For a 300-token generation using the GPT-2 demo (GPT-2 medium model), this reduces runtime from ~28s to ~21s on my system. For comparison, GGML takes ~14s, but note that it is using FP16 weights.
The changes are as follows:
1. Add `Tensor::{with_capacity, append}` APIs. This enables creating an empty tensor with capacity to be extended to a given shape without reallocating. The extension must happen along a pre-specified axis.
2. Add an in-place implementation of the `Concat` operator, which will extend its first input in-place if possible, instead of copying all inputs to a new output.
3. Change …

Reduce KV-cache growth cost from `O(sequence_len)` to `O(1)`

---

src/graph.rs
src/ops/mod.rs
src/ops/random.rs

Allow operators to declare whether they are deterministic or not, make the `Random*` ops return `false`, and prevent `Graph::partial_run` from propagating values through non-deterministic operators.
With this change it should become safe to apply constant propagation as an optimization when models are loaded.
Fixes https://github.com/robertknight/rten/issues/90.

Prevent `Model::partial_run` from propagating values through random ops

---

rten-cli/src/main.rs
rten-generate/src/generator.rs
src/graph.rs
src/lib.rs
src/model.rs
src/optimize.rs

Add initial infrastructure to perform graph optimizations as part of loading a model, and implement constant propagation (pre-evaluating the parts of the graph that don't depend on dynamic input values) as the first graph-level optimization. This is an optimization that was already implemented downstream in `rten-cli` and `rten-generate` after the model was loaded. Those downstream implementations are also removed in this change. 
Optimization is performed by default when a model is loaded, but can be disabled using `ModelOptions`. This mirrors ONNX Runtime's approach of enabling optimizations unless the consumer opts out.
**TODO:**

Perform constant propagation when loading models

---

src/downcast.rs
src/graph.rs
src/lib.rs
src/ops/fused.rs
src/ops/matmul.rs
src/ops/mod.rs
src/ops/unary_elementwise.rs
src/optimize.rs

This fuses subgraphs of the form:
```
(Transpose(X), Y) -> MatMul
```
Where the MatMul operands can be in either order, but only either `X` or `Y` can be transposed.
The fused operation transposes the `X` view before invoking the `MatMul` op with
the transposed view. This avoids materializing the transposed matrix.
This fusion works because the `MatMul` operation can efficiently handle
transposed input views. Other operations could also support an extended version
of this fusion in future.
In the context of transformer models this fusion avoids materializing the transposed `K` matrix in the Scaled Dot Product Attention (SDPA) operation. In that context more sophisticated fusions are possible here, such as replacing the whole SDPA with a fusion that implements flash attention. That will …

Add Transpose + MatMul fusion

---

rten-tensor/src/layout.rs
src/graph.rs
src/ops/concat.rs
src/ops/gather.rs
src/ops/layout.rs
src/ops/mod.rs
src/ops/resize.rs
src/ops/slice.rs

This is a collection of micro-optimizations to reduce from overhead when executing a graph. Mostly this involves using `SmallVec` instead of `Vec` in cases where we expect the number of items will almost always be small.
Also I found that the overhead of creating tensor views could be reduced by implementing `Clone` manually for `DynLayout`, in order to use a `SmallVec` fast path for `Copy`-able items.
In the test scenario described in https://github.com/robertknight/rten/pull/239 this decreases time spent doing non-compute work on the "main" thread (the one where `Graph::run_plan` runs) by ~3%.

Reduce allocations during graph execution

---

src/graph.rs
src/ops/binary_elementwise.rs
src/ops/concat.rs
src/ops/conv.rs
src/ops/convert.rs
src/ops/fused.rs
src/ops/gather.rs
src/ops/generate.rs
src/ops/identity.rs
src/ops/layout.rs
src/ops/matmul.rs
src/ops/mod.rs
src/ops/non_max_suppression.rs
src/ops/norm.rs
src/ops/pad.rs
src/ops/pooling.rs
src/ops/random.rs
src/ops/reduce.rs
src/ops/resize.rs
src/ops/rnn.rs
src/ops/slice.rs
src/ops/split.rs
src/ops/trilu.rs
src/ops/unary_elementwise.rs
src/ops/variadic_elementwise.rs

Most operators only have one output, so we can avoid allocations for the output list by using `SmallVec<[Output; 1]>` for this.
With this change, it is now possible to execute some non in-place steps in a graph with no allocations from the system allocator at all, provided that the operator's output buffer can be allocated from the pool.

Use SmallVec for operator outputs

---

rten-vecmath/src/exp.rs
rten-vecmath/src/lib.rs
src/ops/mod.rs
src/ops/unary_elementwise.rs
src/optimize.rs

Add a fusion for the Sigmoid Linear Unit (SiLU) operation, which computes `x * sigmoid(x)`. This is the main activation in YOLOv8 among other models.
This makes YOLOv8 Small about 8% faster. Tested on a quad-core Intel i5 with f32 model.

Add fusion for SiLU activation

---

Cargo.lock
rten-examples/Cargo.toml
rten-generate/Cargo.toml
rten-generate/src/generator.rs
rten-generate/src/lib.rs
rten-generate/src/text_decoder.rs

This is a collection of changes needed to make rten-generate usable with a wider range of models.
- Enable customizing the names of the model inputs and outputs that the generator works with
- Support custom inputs whose values vary depending on the sequence position. This is useful to pass position embeddings if they are not computed internally by the model
- Support key-value caches that have shape `(batch, seq, chans)` instead of `(batch, heads, seq, chans)`. In the 3D case the heads are included in the `chans` dimension
- Make `rten-text` an optional dependency in rten-generate. Downstream projects may be using other tokenizer libraries or decoding into a non-text output mode. This change allows such projects to avoid rten-text and its larger dependencies (regex engine etc.)

Make rten-generate model inputs more flexible

---

rten-convert/rten_convert/schema_generated.py
rten-vecmath/src/erf.rs
rten-vecmath/src/lib.rs
rten-vecmath/src/testing.rs
src/model.rs
src/model_builder.rs
src/ops/mod.rs
src/ops/unary_elementwise.rs
src/schema.fbs
src/schema_generated.rs

Initially only the non-approximate version is implemented.
AFAIK the tanh-based approximation supported in the ONNX spec is a relic from when certain ML runtimes lacked an efficient implementation of the `Erf` operator, and is not frequently used in newer models.

Implement Gelu operator

---

src/graph.rs
src/ops/mod.rs

Make a few changes to streamline `run_plan` a little
- Avoid needing to `match` over different tensor dtypes by adding methods on the various enums that abstract over them (`Input`, `Output`, `Constant`)
- Extract logging code out of `run_plan` into separate methods

Clean up `Graph::run_plan`

---

rten-generate/src/generator.rs
rten-generate/src/lib.rs
rten-generate/src/model.rs

- Change the `Generator` type to work with a `Model` trait rather than `rten::Model` directly. This allows creating a fake model in tests which records its inputs and yields predefined outputs. It might have some other debugging etc. use cases in future.
- Add some simple tests for `Generator`

Add basic unit tests for rten-generate

---

rten-generate/src/generator.rs

Yesterday I added basic tests for the `Generator` struct. This adds some tests for the wrappers that handle profiling and stopping generation once an end-of-text token is reached.

Add tests for `GeneratorUtils::{stop_on_token, profile}`

---

src/gemm.rs

The kernel prefers the K dimension to be small if B has unit column stride or large if it has unit row stride. In the case of unit column stride, reducing the K dimension further helped.
These changes made GPT-2 medium fp32 about 10% faster on an Ice Lake i5.

Further tune vector-matrix product

---

rten-tensor/src/copy.rs
rten-tensor/src/tensor.rs
src/ops/concat.rs

This PR contains a few small optimizations to reduce the overhead of `Concat`, ie. the work other than actually copying the data.

Reduce Concat op overhead

---

src/ops/layout.rs

Optimize this common use of `Unsqueeze`:
- Use `TensorBase::insert_axis` to more efficiently insert new axes into the output
- Add fast path when `axes` vector has only one item, in which case we can skip testing the axes for uniqueness

Optimize use of `Unsqueeze` to add a single dimension to a tensor

---

src/ops/norm.rs

- Avoid parallelism entirely if the total number of output elements is small
- If the output is large enough to justify parallelism but the lanes are small, process multiple lanes in each parallel chunk
The smaller GPT-2 models for example have many small softmaxes, for which avoiding parallelism entirely is more efficient.

Tune parallelism in Softmax op

---

rten-tensor/src/iterators.rs
rten-tensor/src/storage.rs
rten-tensor/src/tensor.rs
src/constant_storage.rs

The slicing in each call to `next` was slow. Since these iterators yield views with the same layout each time, we can precompute the layout when the iterator is constructed. Each call to `next` then just has to compute the storage offset for the next view.
This optimization is not yet implemented for `inner_iter_dyn`, but in principle it could be.
**TODO:**

Make `TensorBase::{inner_iter, inner_iter_mut}` more efficient

---

docs/rten-file-format.md
rten-convert/rten_convert/converter.py
rten-convert/rten_convert/schema_generated.py
rten-convert/rten_convert/tensor_data.py
rten-convert/rten_convert/util.py
src/header.rs
src/lib.rs
src/model.rs
src/model_builder.rs
src/number.rs
src/schema.fbs
src/schema_generated.rs

This introduces a new version of the `.rten` model format. The main improvements are:
- The addition of a header containing file magic, format version and segment offsets
- Tensors can now be stored outside the FlatBuffers data, avoiding the 2GB limit of the FB format, and also providing more control over alignment of data
The overall structure of the new format is:
```
[header] [model_data] [tensor_data]
```
Where the `[model_data]` section is the FlatBuffers data that was the entire content of the file in the V1 format. More details are provided in the `docs/rten-file-format.md` document.
The `rten-convert` tool generates models in the V1 format by default, and uses the V2 format if the `--v2` flag is provided. The `rten` crate can consume both V1 and V2 format models.
With these …

Introduce version 2 `.rten` model format, with support for larger (> 2GB) models

---

src/op_registry.rs

Make the order of arguments more consistent: operator type, attribute getter, constructor.

Re-order `impl_read_op` arguments

---

src/model.rs
src/ops/mod.rs

This PR contains a couple of small improvements needed to use the latest version of RTen in the Ocrs project.
- Make `ModelLoadError` Sync again, so it can be converted into `anyhow::Error`
- Support conversion of tensor references to `InputOrOutput`, to match existing conversion from tensor references to `Input`

Make `ModelLoadError` Sync again, support `&Tensor` => `InputOrOutput` conversion

---

docs/rten-file-format.md

Previously it described the V2 format with a brief note about V1 at the bottom, which could be confusing since rten-convert still generates V1 by default (see https://github.com/robertknight/rten/issues/267).

Add better nodes on the different versions of the .rten model format

---

rten-convert/rten_convert/converter.py
rten-convert/rten_convert/schema_generated.py
src/model.rs
src/model_builder.rs
src/op_registry.rs
src/schema.fbs
src/schema_generated.rs

This is not currently used, but will make it easier to support the `approximate` attribute in future.

Add empty attrs table to `Gelu` operator

---

docs/rten-file-format.md
rten-convert/rten_convert/converter.py
src/model.rs
src/model_builder.rs

This allows converting large (> 2GB) models without needing to pass the `--v2` flag to `rten-convert`. There is a `--v1` flag to force creation of V1 models for use with older rten versions.
- Make rten-convert use the V2 format by default
- Change all tests to use the V2 model format, except for one test to check that loading and running V1 models still works

Generate rten models in V2 format by default

---

rten-examples/src/depth_anything.rs
src/ops/operators.rs
src/ops/random.rs
src/ops/reduce.rs

Move them from the `FloatOperators` to the `Operators` trait, with appropriate bounds.

Make `reduce_{max, min, sum}` methods more generic

---

src/graph.rs
src/ops/fused.rs
src/optimize.rs

Revise transpose fusion to be able to support additional operators. In this initial commit, only `MatMul(Transpose(X), Y)` is fused as before, but this will make it easier to support other operators in future.
In order to construct a `FusedTranspose` from an arbitrary operator, it was necessary to support cloning any operator. Since operators are stateless, the easiest way to do this is to make them reference counted in the graph, then they can be "cloned" just by creating a new `Arc`.

Generalize transpose fusion

---

src/graph.rs
src/optimize.rs
src/optimize/pattern_matcher.rs

Writing complex fusions was difficult using the existing APIs. Add tools to make writing and matching subgraph patterns easier. The existing SiLU fusion has been rewritten using them as a proof of concept.
With these new APIs, matching the subgraph pattern for SiLU looks like:
```rs
use pattern_matcher::{symbol, unary_op};
let x = symbol("x");
let silu_pattern = x.clone() * unary_op("Sigmoid", x.clone());
if let Some(silu_match) = silu_pattern.test(operator_node_id, graph) {
// Handle match
}
```
**TODO:**

Add graph pattern matcher, rewrite SiLU fusion using it

---

src/optimize.rs

This initial fusion is based on the ONNX export of PyTorch's `nn.GELU`, but can accomodate minor variations (eg. very small differences in constant values, swapped operands for add/mul ops). It won't fuse GELU approximations that some older models use.
**TODO:**

Implement GELU fusion

---

src/optimize.rs
src/optimize/pattern_matcher.rs

Generalize binary operations on patterns so that `some_pattern + constant(1.0)` can be simplified to `some_pattern + 1.0`. This will also make it easier to add constants with other data types in future.

Reduce need to use `constant` helper when writing graph patterns

---

src/graph.rs
src/optimize.rs
src/optimize/pattern_matcher.rs

This fuses subgraphs like below, excluding the "Add" in the top left corner, into a `LayerNormalization` operator:
So far this has been tested with BERT, GPT-2 and Whisper models.
This is a rather complex fusion and as a result, is liable to be brittle. That is, other equivalent ways of expressing the operator will not match. Also it doesn't help with operators which are variations of this such as RMSNorm (used in Llama etc.). In future it would probably make sense to break this up so that the individual sub-steps (centering, variance normalization, shift + scale) are fused separately.
**TODO:**

Implement LayerNormalization fusion

---

src/graph.rs
src/optimize.rs
src/optimize/pattern_matcher.rs

Move the `add_simple_op` trait method from `GraphTestUtils` in optimize.rs into the `Graph` struct and use it to simplfy existing tests in graph.rs.

Simplify adding operators in graph tests

---

rten-cli/src/main.rs
rten-examples/Cargo.toml
rten-examples/README.md
rten-examples/src/distilvit.rs
rten-examples/src/gpt2.rs
rten-examples/src/qwen2_chat.rs
rten-generate/src/generator.rs
rten-generate/src/sampler.rs
rten-text/src/tokenizers.rs
rten-text/src/tokenizers/json.rs
src/model.rs

Add a chatbot demo. This uses the Qwen2 model since it provides 0.5b and 1.5b sizes that are best-in-class, and the tokenization is conveniently a derivative of the GPT-2 tokenization which rten-text supports. Larger models would produce better results, but since RTen only supports fp32 precision at present, such models become slow due to the memory bandwidth requirements. 1.5b is about the largest size that produces "usable" speed on my Intel i5.
In the process it was necessary to add some capabilities to rten-generate and rten-text to better support chat-like applications:
- Support adding user input to the model input after the initial generation, via `Generator::append_prompt`
- Fix generation of the `attention_mask` input. It is supposed to have the length of the input sequence not …

Add chatbot example using Qwen2

---

Makefile
js-examples/image-classification/image-classifier.js
src/graph.rs
src/model.rs
src/timing.rs

- `std::time::Instant::now` panics on wasm32-unknown-unknown. Replace calls with a wrapper which is currently a no-op, but can be modified to use `performance.now()` in future.
- Fix test execution under wasm32 by skipping the `Model::load_mmap` test
- Add a note about how to modify the wasm build to get a useful stacktrace if a crash happens
See https://github.com/robertknight/ocrs/issues/93.

Avoid calling `std::time::Instant::now` on wasm32-unknown-unknown

---

rten-tensor/src/tensor.rs
src/graph.rs
src/model.rs
src/ops/binary_elementwise.rs
src/ops/concat.rs
src/ops/gather.rs
src/ops/pad.rs
src/optimize.rs
src/optimize/pattern_matcher.rs

`Tensor::from` previously supported creating tensors from 1-3D nested arrays. Extend this to scalar values..

Support creating scalar tensors using `Tensor::from`

---

rten-examples/src/piper.rs
rten-examples/src/wav2vec2.rs
rten-tensor/src/lib.rs
rten-tensor/src/macros.rs
src/graph.rs
src/model.rs
src/ops/binary_elementwise.rs
src/ops/concat.rs
src/ops/convert.rs
src/ops/fused.rs
src/ops/gather.rs
src/ops/generate.rs
src/ops/identity.rs
src/ops/layout.rs
src/ops/norm.rs
src/ops/reduce.rs
src/ops/resize.rs
src/ops/split.rs
src/ops/trilu.rs
src/ops/unary_elementwise.rs
src/ops/variadic_elementwise.rs

Replace `tensor!((shape); [elements])` with `nested_array.into()` (if type can be inferred) or `Tensor::from(nested_array)`. This is an effort to make the codebase more consistent by having fewer ways to create tensors from literals.

Deprecate `tensor!` and `ndtensor!` macros in favor of `{Tensor, NdTensor}::from`

---

rten-examples/src/gpt2.rs
rten-examples/src/qwen2_chat.rs
rten-generate/src/generator.rs
rten-generate/src/sampler.rs
rten-generate/src/text_decoder.rs
rten-text/src/tokenizers.rs
rten-text/src/tokenizers/bpe.rs
rten-text/src/tokenizers/json.rs
rten-text/src/tokenizers/wordpiece.rs
rten-text/tests/reftest.rs

Previously rten-text used `usize` for token IDs and rten-generate used `u32`, requiring extra conversions. Settle on `u32` everywhere since all tokenizers that I'm aware of have hundreds of thousands of tokens at most.

Use `u32` everywhere to represent token IDs

---

src/ops/convert.rs
src/ops/mod.rs

If the Cast operator is run in place but has to copy its input, return the original input to the pool, avoiding the overhead of freeing it with the system allocator.
Also refactor the cast to avoid constructing an `InputList` and unpacking an `OutputList`.

Return input to pool in `run_in_place` fallback for Cast operator

---

rten-tensor/src/iterators.rs
src/ops/norm.rs
src/ops/reduce.rs
src/slice_reductions.rs

This PR contains a series of optimizations to the LayerNormalization operator, which also benefit ReduceMean and ReduceSum:
- Use a more efficient method of extending the output Vec when reducing over non-unit stride axes in `Reduce*` operations. As part of this, impl ExactSizedIterator and FusedIterator for the `Lanes`/`Lane` iterators in rten-tensor
- Fuse the `1. / (mean(x^2) + epsilon).sqrt()` step ("inverse Root Mean Squared") in LayerNormalization. This will also be useful in a future RMSNorm operator.
- Use in-place operations to reduce the number of temporary buffers used in LayerNormalization
- Apply the technique used to improve ILP/vectorization for summing slices to summing of non-unit stride tensor lanes
Using the `vision_encoder.onnx` model from …

Optimize `LayerNormalization` using fusion, in-place operations and more efficient reductions

---

rten-tensor/src/overlap.rs

If a dimension has a size of 1, only index 0 is valid and since `0 * stride = 0` for all strides, we can ignore the stride when determining whether a tensor is contiguous.
This allows more code to use fast paths for contiguous tensors. In particular when new dimensions are inserted in the middle of a tensor by `Unsqueeze` operations in a model, they no longer become non-contiguous.

Ignore strides of size-1 dimensions when determining if tensor is contiguous

---

src/ops/binary_elementwise.rs
src/ops/layout.rs

Avoid allocations in most cases when computing the shape produced by broadcasting two tensors together.

Reduce allocations when broadcasting tensor shapes

---

rten-convert/rten_convert/converter.py
rten-convert/rten_convert/schema_generated.py
rten-examples/Cargo.toml
rten-examples/README.md
rten-examples/src/segment_anything.rs
src/model_builder.rs
src/op_registry.rs
src/ops/einsum.rs
src/ops/mod.rs
src/schema.fbs
src/schema_generated.rs

Add an initial version of the `Einsum` operator, and a Segment Anything model example, whose image encoder model requires it.
The initial Einsum implementation is limited to equations that can be efficiently executed as a single matrix multiplication, with permutations of the inputs and outputs if needed.
The example uses the [sam-vit-base](https://huggingface.co/facebook/sam-vit-base) model variant in its documentation, but I have also tested with [sam-vit-large](https://huggingface.co/facebook/sam-vit-large) and [slimsam](https://huggingface.co/nielsr/slimsam-50-uniform).

Add partial implementation of `Einsum` and Segment Anything example

---

rten-tensor/src/layout.rs
rten-tensor/src/tensor.rs
src/ops/einsum.rs

This expands the supported equations, however some cases are handled with a naive/inefficient implementation.
Support:
- Reducing a single input
- Equations that involve no reductions (eg. outer products)
- Equations that involve vector-vector or vector-matrix dot products
When we don't have a suitable dimension for the M or N inputs of a matmul,
insert temporary axes and them remove them afterwards.
- Equations that involve more than one reduced dimension or more than
two inputs.
These cases are currently handled by a naive implementation which is much
less efficient than matrix multiplication.

Expand supported equations in Einsum

---

src/ops/einsum.rs
src/tensor_pool.rs

Previously Einsum equations with more than two inputs were handled via a fallback to a naive implementation that was much less efficient than a matmul if a reduction was required. In this commit, equations are split into a path where each step handles one or two inputs. Each step will use matmul, multiply or reduce-sum as appropriate.
The generated path always processes inputs in left-to-right order. This can be much less efficient than the optimal contraction order. Using a better algorithm is left as a future exercise.
Part of https://github.com/robertknight/rten/issues/298.

Support using matmul for Einsum equations with 3 or more inputs

---

rten-tensor/src/tensor.rs
src/ops/einsum.rs
src/ops/mod.rs

Per the [`numpy.einsum`](https://numpy.org/doc/stable/reference/generated/numpy.einsum.html) docs, repeated labels in a single input term take the diagonal. The ONNX [Einsum](https://onnx.ai/onnx/operators/onnx__Einsum.html) docs don't mention this, but the reference implementation just calls `numpy.einsum`, so I assume this is supposed to be supported.

Take diagonals when labels are repeated in an Einsum input term

---

rten-generate/src/generator.rs

Using a model with a key-value cache is strongly recommended as decoding is much faster, but it should at least be possible to use a model that does not have one.

Support models without a key-value cache in rten-generate

---

rten-convert/rten_convert/converter.py
rten-convert/rten_convert/schema_generated.py
src/graph.rs
src/model.rs
src/model_builder.rs
src/op_registry.rs
src/ops/control_flow.rs
src/ops/mod.rs
src/schema.fbs
src/schema_generated.rs

Implement the [If](https://onnx.ai/onnx/operators/onnx__If.html#l-onnx-doc-if) operator. This is the first control flow operator that is being supported in RTen, so most of the changes are the infrastructure needed to support operators which run subgraphs as part of their execution.
**TODO:**
**Deferred to subsequent PRs**
- Ensure that constant propagation in rten-generate doesn't eliminate inputs that are needed as captured values on subsequent runs. This affects the `encoder_hidden_states` input in TrOCR (see https://github.com/robertknight/rten/pull/304).
- Investigate error when running Silero VAD model that uses the If operator extensively. From an initial glance it looks like the issue is that planning doesn't take into account dependencies an operator may have due to captures in …

Implement `If` operator

---

src/graph.rs
src/ops/control_flow.rs
src/ops/mod.rs

When timing reports or verbose logging is enabled, this causes the logging to be printed for subgraphs as well as the main graph.
`RunOptions` is currently a tiny 4-byte struct, so it is fine to just clone it.

Propagate graph run options to subgraphs

---

src/graph.rs
src/ops/control_flow.rs

Allow subgraphs to reuse buffers allocated by the main graph or other subgraphs by sharing the `TensorPool` between all graphs executed in a run.

Share tensor pool between main graph and subgraphs

---

src/graph.rs
src/ops/control_flow.rs
src/ops/mod.rs

When creating an execution plan and initializing and updating the ref counts for temporary values, consider operator dependencies arising from values captured by the operator's subgraphs in addition to the input node ID list.
This affects:
- Creation of the execution plan given a set of output IDs
- Initializing and updating ref counts for temporary values in `Graph::run_plan`
- Plan pruning during partial evaluation by `Graph::partial_run`

Account for operator dependencies due to subgraph captures in planning and temp value reference counting

---

rten-cli/src/main.rs
rten-examples/Cargo.toml
rten-examples/README.md
rten-examples/src/trocr.rs
rten-text/src/tokenizers/bpe.rs

This is a vision-to-text example with a very similar structure to the DistilViT example.
Different TrOCR model sizes use different tokenizers. This example works with the base model which uses a BPE tokenizer, but not the small model which uses a unigram tokenizer.
Compared to [Ocrs](https://github.com/robertknight/ocrs) the models are much larger and thus slower to execute. However being a bigger model it also has more capacity.
**TODO:**
- The problem is that the "shift and scale" pattern in `fuse_layer_norm` doesn't match because it expects arguments to the `Add` and `Mul` operators to be constants. However they are actually value nodes which capture values from constants defined in the parent graph.

Add TrOCR example

---

src/constant_storage.rs
src/graph.rs
src/model.rs
src/optimize.rs

Add a pass that converts captured values to local constants, if the capture
resolves to a constant node in a parent graph. This allows subsequent
optimizations which depend on values being constants to work.
In the TrOCR example that was recently added, the model is split into two
branches which each capture many weights as constants from the main graph.
This change allows LayerNormalization and Gelu fusion to work in the subgraphs.
This optimization could be done as part of model conversion instead, with the
constant nodes for the weights duplicated in each subgraph, but referencing the
same serialized weight data.

Add an optimization pass to convert captured values to constants

---

src/optimize.rs

Make it clearer what these values refer to. This will also make it easier to transition `NodeId` to u32 in future to align with the FlatBuffers schema.

Use `NodeId` type alias instead of `usize` in optimize.rs

---

rten-convert/rten_convert/converter.py

If a tensor shape was present for an ONNX value node but was an empty list, indicating a scalar value, no shape was saved in the rten model. This is because a falsy check was used and empty lists are falsy in Python.
The issue was encountered with the `sr` (sample rate) input to the [Silero VAD](https://github.com/snakers4/silero-vad/tree/master/src/silero_vad/data) models.

Fix conversion of shapes for scalar tensors

---

src/ops/conv.rs

Non-contiguous 1D views cannot be reshaped without a copy. However we only need to insert an axis, which can be done on non-contiguous views.
Both 1D and 2D convolution also failed if the kernel was not contiguous, except for the pointwise and depthwise cases.

Fix 1D conv failing with non-contiguous inputs

---

rten-tensor/src/layout.rs
rten-tensor/src/tensor.rs

If any dimension in a tensor has zero size, the data offset start and end for a slice should be zero.
The incorrect calculation led to panics when slicing empty tensors using various methods.
**TODO:**

Fix calculation of data offset range when slicing an empty tensor

---

rten-convert/rten_convert/converter.py
rten-convert/rten_convert/schema_generated.py
src/op_registry.rs
src/ops/mod.rs
src/ops/operators.rs
src/ops/pad.rs
src/schema.fbs
src/schema_generated.rs

For efficiency and simplicity, reflection padding is only supported for the last
2 dimensions of the input. Any additional dimensions are treated as batch
dimensions which must have the same size in the input and output.
PyTorch has a constraint that the amount of padding must be less than the size
of a dimension, which is useful since it avoids the need for padding to wrap
around by taking an expensive modulus of the dimension size. NumPy however
allows wrap-around, and the example in the ONNX spec relies on this. In this
implementation, wrap-around is supported but it might be necessary to split the
cases in future for efficiency, to avoid a modulus in the common case where the
padding size is less than the dimension size.

Support "reflect" padding mode

---

rten-cli/Cargo.toml
rten-cli/src/main.rs

This is useful for testing the performance of loading a model with mmap vs by reading the model into a buffer.

Add flag to rten CLI to load model using mmap

---

src/graph.rs

This makes the log output tidier, and microsecond-level precision is adequate.

Round timings to nearest microsecond in verbose log outputs

---

rten-convert/rten_convert/converter.py
src/schema.fbs

Fix a mistake from 917980b22 where the `auto_pad` attribute was only written to the model file if non-fixed padding was used. This caused operators to use "same" padding instead of "fixed" padding when the ONNX `auto_pad` attribute was set to `NOTSET`.
Fixes https://github.com/robertknight/rten/issues/332

Always set `auto_pad` attribute for pooling and convolution operators

---

src/ops/pad.rs

When reading the start padding values from the `padding` input, read the last 2 values from the first half of the vector, instead of the first two.
Issue found when testing rten in https://github.com/emotechlab/silero-rs.

Fix incorrect reflect padding in tensors with 3+ dims

---

src/ops/layout.rs

e56072e1e4092aa477b25e1c2e6c8a6aaca9450a revised the implementation to remove the use of `TensorBase::reshape`, which did require the input to be contiguous at the time (now it copies if needed) but didn't remove the use of `make_contiguous` which is not required for `insert_axis`.

Avoid copying input in in-place Unsqueeze op

---

rten-examples/src/deeplab.rs
rten-examples/src/depth_anything.rs
rten-examples/src/detr.rs
rten-examples/src/trocr.rs
rten-imageio/src/lib.rs
rten-imageproc/src/lib.rs
rten-imageproc/src/normalize.rs

Several examples need to normalize an image with a mean and standard deviation different from the ImageNet values. Add a function in rten-imageproc with this flexibility. The function has been added to the rten-imageproc crate because it doesn't have any dependencies on specific image formats.
In the process the implementation was also revised to make it more efficient.

Move `normalize_image` to rten-imageproc and make it customizable

---

rten-cli/src/main.rs
rten-convert/rten_convert/converter.py
rten-convert/rten_convert/schema_generated.py
rten-convert/rten_convert/tensor_data.py
src/graph.rs
src/model.rs
src/model_builder.rs
src/number.rs
src/ops/binary_elementwise.rs
src/ops/concat.rs
src/ops/convert.rs
src/ops/fused.rs
src/ops/gather.rs
src/ops/generate.rs
src/ops/identity.rs
src/ops/layout.rs
src/ops/mod.rs
src/ops/pad.rs
src/ops/reduce.rs
src/ops/slice.rs
src/ops/trilu.rs
src/ops/unary_elementwise.rs
src/ops/variadic_elementwise.rs
src/optimize.rs
src/schema.fbs
src/schema_generated.rs
src/wasm_api.rs

This is the first step in adding 8-bit quantization support. It adds support for u8 and i8 tensors in:
- RTen model files
- Operator inputs
- Operator outputs
Int8 support has not been added to most operators yet. Done naively this would require two instantiations of the code for u8 and i8 tensors even though many operators could use the same code for both. This could be addressed with https://github.com/robertknight/rten/issues/244. For the moment I am adding support for i8 and u8 tensors to operators on an as-needed basis.

Support u8 and i8 tensors in operator inputs, outputs and model files

---

rten-convert/rten_convert/converter.py
rten-convert/rten_convert/schema_generated.py
rten-tensor/src/lib.rs
src/model.rs
src/model_builder.rs
src/op_registry.rs
src/ops/convert.rs
src/ops/mod.rs
src/ops/quantize.rs
src/schema.fbs
src/schema_generated.rs

Implement the quantization operators used by the "[tensor oriented](https://onnxruntime.ai/docs/performance/model-optimizations/quantization.html)" quantization method.
In the initial implementation scalar and per-axis quantization are supported, but not blocked quantization.

Implement QuantizeLinear, DequantizeLinear, DynamicQuantizeLinear ops

---

rten-simd/src/arch.rs
src/gemm.rs
src/gemm/kernels.rs
src/ops/conv/im2col.rs

Fix an issue where SIMD instructions were present in WASM binaries even builds when the "simd128" target feature was not enabled.
Fix tested in the Ocrs repo with:
```
RUSTFLAGS="-C target-feature=+simd128" cargo build --release --target wasm32-wasi --package ocrs-cli
wasmtime -W simd=n -W relaxed-simd=n --dir . target/wasm32-wasi/release/ocrs.wasm --detect-model text-detection.rten --rec-model text-recognition.rten ocrs-cli/test-data/why-rust.png
```
See https://github.com/robertknight/ocrs/issues/113

Add missing conditionals for SIMD support in WASM builds

---

rten-examples/src/rmbg.rs
src/ops/gather.rs

This is used when gathering embedding vectors from quantized models.
Also fix a clippy warning that I missed in recent PRs.

Support u8 tensors in `Gather` operator

---

src/gemm.rs
src/gemm/kernels.rs
src/gemm/kernels/aarch64.rs
src/gemm/kernels/generic.rs
src/gemm/kernels/wasm.rs
src/gemm/kernels/x86_64.rs
src/gemm/packing.rs
src/number.rs
src/ops/conv/im2col.rs

Refactor the `GemmExecutor` and `Kernel` interfaces to be generic over the element types of the A and B input matrices and output matrix.
This allows reusing a lot of the code for matmul operations with different element types. Currently only f32 is supported, but in future this should be helpful for supporting f16, bf16, i8, u8 etc. For quantised matmul the interfaces will need to change since additional quantisation parameters will need to be passed, such as the zero-point and scale for inputs.
The architecture-specific kernels still have to be implemented separately for each combination of types, as well as the code that instantiates a `GemmExecutor` for such a combination.

Make GEMM implementation generic over input and output matrix element types

---

src/ctc.rs

Fix an error reported by `make docs` about unportable markdown in ctc.rs after upgrading to Rust v1.81.

Fix markdown error in ctc module

---

src/gemm/kernels/aarch64.rs
src/gemm/kernels/generic.rs
src/gemm/kernels/wasm.rs
src/gemm/kernels/x86_64.rs

Kernels are only supposed to be constructible via the `new` method which returns `None` if the kernel is not supported on the current system. Having a derived `Default` impl provided a way to instantiate the kernels even on systems where they are not supported.

Remove derived `Default` impl for GEMM kernels

---

rten-convert/rten_convert/schema_generated.py
src/model_builder.rs
src/op_registry.rs
src/ops/matmul.rs
src/ops/mod.rs
src/schema.fbs
src/schema_generated.rs
tools/ort-quantize.py

Add a non-optimized implementation of the `MatMulInteger` operator.
With this it is possible to run a quantized GPT-2 model ... very slowly. Optimized kernels will follow in subsequent PRs.

Add non-optimised `MatMulInteger` implementation

---

rten-simd/src/arch/aarch64.rs
rten-simd/src/arch/scalar.rs
rten-simd/src/arch/wasm.rs
rten-simd/src/arch/x86_64.rs
rten-simd/src/vec.rs
src/ops/conv.rs
src/ops/conv/im2col.rs

This is a step towards implementing `ConvInteger` and supporting non-f32 float types in convolution.
Part of https://github.com/robertknight/rten/issues/347.

Make im2col packing mostly generic

---

rten-generate/src/generator.rs
rten-generate/src/sampler.rs
rten-tensor/src/copy.rs
rten-tensor/src/layout.rs
rten-tensor/src/lib.rs
rten-tensor/src/tensor.rs
rten-tensor/src/type_num.rs
src/gemm.rs
src/gemm/kernels/simd_generic.rs
src/ops/conv.rs
src/ops/conv/depthwise.rs
src/ops/non_max_suppression.rs
src/ops/pooling.rs
src/ops/resize.rs
src/ops/rnn.rs

Add new slicing methods, `slice_with` and `slice_with_mut` that infer the rank of the returned views automatically at compile time. This is more ergonomic to use than the existing `slice` method and avoids the possibility of specifying the wrong dimension count, or changing the rank of the sliced type and forgetting to update the slicing operation.
Eventually this may replace both `slice` and `slice_dyn`, but it has been added as a new API initially to allow incremental adoption downstream and also allow some iteration on the details.

Add `TensorBase::slice_with` method

---

src/ops/rnn.rs

Use static-rank views where possible in RNN operators and `slice_with` to infer the rank of created views automatically.
This change is partly to test the new `slice_with` API but also to help catch mistakes in future refactoring.

Use `TensorBase::slice_with` in RNN operators

---

rten-imageproc/src/drawing.rs
rten-imageproc/src/normalize.rs
rten-tensor/src/tensor.rs
src/ops/conv.rs
src/ops/conv/depthwise.rs
src/ops/non_max_suppression.rs
src/ops/rnn.rs

Continue the work to use static-rank tensors and automatic inference of sliced view rank, where possible.

Replace remaining uses of `slice` with `slice_with`

---

rten-tensor/src/iterators.rs
rten-tensor/src/layout.rs
rten-tensor/src/tensor.rs
rten-tensor/src/type_num.rs
src/ops/reduce.rs
src/ops/split.rs

Support slicing tensors with ranges that have a runtime-determined index count in `TensorBase::slice_with`. In such cases the resulting view has a dynamic-rank layout. This allows this method to replace existing usage of `slice_dyn`.

Support ranges with unknown index count in `slice_with`

---

rten-imageproc/src/contours.rs
rten-imageproc/src/poly_algos.rs
rten-imageproc/src/shapes.rs
rten-tensor/src/layout.rs
rten-tensor/src/overlap.rs
rten-tensor/src/test_util.rs
src/graph.rs
src/ops/binary_elementwise.rs
src/ops/conv.rs
src/ops/gather.rs
src/ops/generate.rs
src/ops/layout.rs
src/ops/pooling.rs
src/ops/reduce.rs
src/ops/resize.rs
src/ops/rnn.rs
src/ops/slice.rs
src/wasm_api.rs

For stylistic consistency, use the `Iterator::zip` method instead of the standalone `zip` function everywhere.

Use `zip` method instead of standalone function

---

rten-tensor/src/errors.rs
rten-tensor/src/iterators.rs
rten-tensor/src/layout.rs
rten-tensor/src/tensor.rs
src/ops/gather.rs

Add fallible variants of the new `slice_with` method and use it to replace usage of the old `try_slice_*` methods in rten operators.
In the process the errors reported by fallible slicing methods have been improved to include more details about the problem.
These are now breaking changes since existing low-level layout methods exported by rten-tensor have been modified and so has `SliceError`.

Add fallible variants of `TensorBase::slice_with`

---

rten-tensor/src/tensor.rs

Update `TensorBase::slice_copy` to match `slice_with` by inferring the layout of the result based on the current tensor's layout and the slice range. Unlike `slice_with` a breaking change was made directly to the original API as it is much less widely used than `slice`.

Infer layout for `slice_copy` based on layout and range

---

rten-cli/src/main.rs

Add a flag that turns off graph optimizations when loading the model, thus providing a way to test their impact.

Add `--no-optimize` flag to rten CLI

---

src/optimize.rs

Given a graph structure like:
```
A -> B -> C -> D
```
When fusions are generated for `A -> B` and `C -> D`, the input for "C" needs to be replaced by the output of the fused `A -> B`.

Apply fusions correctly when fused ops are chained

---

rten-convert/rten_convert/converter.py

float16 is not supported natively yet, so widen it to float32 at conversion time. This will increase model size 2x, but it is better than not being able to run the model at all.

Widen float16 constants to float32 in model converter

---

.github/workflows/ci.yml

Fix `externally-managed-environment` error from pip in Linux CI by creating a virtualenv and installing packages there, as advised by the error messages.

Use a Python virtualenv in CI

---

rten-examples/README.md
rten-examples/src/yolo.rs

The example works with both YOLO v8 and YOLO v11. The v11 model runs about ~15% faster in RTen in my initial tests.
For more details on the v11 model, see https://www.ultralytics.com/blog/ultralytics-yolo11-has-arrived-redefine-whats-possible-in-ai.

Update YOLO example instructions to use YOLO v11

---

rten-tensor/src/impl_debug.rs
rten-tensor/src/iterators.rs
rten-tensor/src/lib.rs
rten-tensor/src/tensor.rs

Improve debug formatting of tensors by adding a custom `Debug` impl instead of using the derived one. The derived impl has been completely useless since views were changed to use custom storage types instead of slices. In the process an issue was resolved where the Clone impl for tensor iterators had an unnecessary `T: Clone` bound (where `T` is the element type). 
For the expression `NdTensor::full([2, 5, 5], 1.).view()`:
**Before:**
```
TensorBase { data: ViewData { ptr: 0x7fc9a0004080, len: 50, _marker: PhantomData<&f64> }, layout: NdLayout { shape: [2, 5, 5], strides: [25, 5, 1] } }
```
**After:**
```
[[[1.0, 1.0, 1.0, 1.0, 1.0],
[1.0, 1.0, 1.0, 1.0, 1.0],
[1.0, 1.0, 1.0, 1.0, 1.0],
[1.0, 1.0, 1.0, 1.0, 1.0],
[1.0, 1.0, 1.0, 1.0, 1.0]],
[[1.0, 1.0, 1.0, 1.0, 1.0],
[1.0, 1.0, 1.0, 1.0, …
```

Improve debug formatting of tensors

---

Cargo.lock
Cargo.toml
Makefile
rten-generate/Cargo.toml
src/model.rs

The rten and rten-generate crates had a self-dependency used to enable features when running tests. This caused rust-analyzer to complain about cyclic dependencies when running `rust-analyzer diagnostics` and it seems that there might be some issues in Cargo (see https://github.com/rust-lang/cargo/issues/2911) but I haven't read the whole thread yet.
See also https://github.com/rust-lang/rust-analyzer/issues/14167.

Remove self-dependency of crates in development

---

rten-generate/src/generator.rs
rten-generate/src/model.rs
src/graph.rs
src/timing.rs

Add a `Generator::with_run_options` API that sets the execution options passed to `Model::run`. This makes it possible to enable verbose logging for example.

Support setting `RunOptions` for model inference when using `Generator`

---

Cargo.toml
rten-generate/Cargo.toml

Avoid creating implicit features named after dependencies, as these implicit features are not used.
See https://doc.rust-lang.org/cargo/reference/features.html#optional-dependencies.
This should remove the fastrand, fastrand-contrib and memmap2 "features" shown on https://docs.rs/crate/rten/0.13.1/features.

Use "dep:" prefix to prevent implicit creation of features

---

rten-examples/src/jina_similarity.rs
src/graph.rs
src/model.rs
src/ops/binary_elementwise.rs
src/ops/conv.rs
src/ops/convert.rs
src/ops/generate.rs
src/ops/identity.rs
src/ops/layout.rs
src/ops/mod.rs
src/ops/norm.rs
src/ops/pad.rs
src/ops/resize.rs
src/ops/unary_elementwise.rs

Replace `Output::{into_int, into_float}` with generic `into_tensor` and `Output::{as_float_ref, as_int_ref}` with generic `as_tensor_view`.
This adds support for u8/i8 tensors and other types as they are added in future.

Generalize `Output` => `Tensor`/`TensorView` convenience methods

---

src/ops/concat.rs
src/ops/conv.rs
src/ops/generate.rs
src/ops/layout.rs
src/ops/matmul.rs
src/ops/mod.rs
src/ops/non_max_suppression.rs
src/ops/norm.rs
src/ops/pad.rs
src/ops/pooling.rs
src/ops/resize.rs
src/ops/rnn.rs
src/ops/slice.rs
src/ops/split.rs

Avoid having two different ways for an operator to check that an input has the expected number of dimensions.
In the process convert `static_dims` to a true crate-internal macro instead of a public-but-undocumented one.

Replace remaining uses of `check_dims` with `static_dims`

---

src/ops/mod.rs

The `Input`, `Output` and `InputOrOutput` types all had identical `Layout` impls. De-duplicate them with a macro.

Use a macro to de-duplicate proxy layout impls

---

src/ops/convert.rs

Follow up to https://github.com/robertknight/rten/pull/387.
- Optimize casts where the source/dest types are the same by using optimized tensor copy operations instead of `Tensor::map`, and skipping the copy altogether if the Cast op is run in-place
- Refactor tests to make adding new cases easier, and add some tests for i8/u8 conversions

Optimize Cast op when source and dest types are the same, add u8/i8 cast tests

---

rten-generate/src/filter.rs
rten-generate/src/generator.rs
rten-generate/src/lib.rs

Add support for modifying the raw model outputs before applying the sampler to select the next token. This can be used to adjust the probability that specific tokens are sampled.

Add API to rten-generate for filtering/processing logits

---

rten-generate/src/filter.rs
rten-generate/src/generator.rs

A very common use case for logit filters is to prevent certain token IDs from being sampled. Add a `token_id_filter` helper for this.
In the process `Generator` was modified to support samplers and logit filters with non-static lifetimes.

Add `token_id_filter` function to create logit filter from predicate

---

rten-generate/src/generator.rs

Support the `cache_position` input that was added to Hugging Face Whisper models as part of a revision of how it handles KV-caching.
This is like `position_ids`, but there is no batch dimension.
See https://github.com/huggingface/optimum/pull/1971 and https://github.com/huggingface/transformers/pull/31166.

Support `cache_position` inputs in Hugging Face models

---

rten-examples/src/wav2vec2.rs
src/ops/norm.rs

Improve the wav2vec2 example by:
- Normalizing audio samples to unit mean and variance, as described in the
wav2vec2 paper and linked issues. In the original fairseq source the
PyTorch `layer_norm` function is used, which does the same thing.
- Chunking the audio to improve performance when transcribing long audio
inputs (see also https://huggingface.co/blog/asr-chunking)
- Improving the readability of the output by lower-casing the raw char
predictions and replacing "|" with spaces.

Normalize and chunk audio inputs in wav2vec2 example

---

src/graph.rs
src/optimize.rs

When replacing a subgraph with a fused operator, reuse the output value node
from the subgraph instead of creating a new one. This preserves metadata such as
the name and shape associated with that value node. Also it simplifies the code
by removing the need to replace all references to the previous output node with
the new one.
This improves the runtime of the Whisper example using the whisper-base model by
~25% by fixing an issue where fused Transpose + MatMul operations did not get
used.

Reuse existing output node when replacing operator with a fusion

---

Cargo.lock
Makefile
rten-examples/Cargo.toml
rten-examples/data/dump_mel_filters.py
rten-examples/src/whisper.rs
rten-tensor/Cargo.toml
rten-tensor/src/copy.rs
rten-tensor/src/impl_serialize.rs
rten-tensor/src/lib.rs
rten-tensor/src/tensor.rs

Support (de-)serialization of `Tensor`/`NdTensor` using serde and use it in the Whisper example to deserialize the mel filters exported from librosa.
The JSON representation of a tensor looks like:
```json
{
"shape": [2, 2],
"data": [0.5, 1.0, 1.5, 2.0]
}
```
This can be deserialized to a `Tensor<f32>` or `NdTensor<f32, 2>`.

Support (de-)serialization of tensors using serde

---

rten-examples/src/whisper.rs

This allows comparing performance across different audio clip lengths. Also this is a number that is often reported for other inference engines.
As a data point, on my Intel i5 laptop I get:
- whisper-base: ~18x realtime
- whisper-small: ~5x realtime
- whisper-medium: ~2x realtime

Output transcription speed as a multiple of real-time in Whisper example

---

rten-generate/src/generator.rs
src/graph.rs

Simplify `node_id.as_u32() as usize` to `node_id.as_usize()`.

Streamline NodeId -> usize conversions

---

src/graph.rs

After creating the initial execution plan by traversing the graph backwards from the requested outputs, re-order it by traversing the plan forwards and choosing a preferred operator to run from the frontier of runnable operators at each step. The initial logic for picking the next operator is to choose the first non-in-place operator if there is one (eg. Shape) or the first operator otherwise.
This re-ordering increases the likelihood that an operator which can run in-place is able to do so, because its in-place input is less likely to be required by a non in-place op that runs later.
Fixes https://github.com/robertknight/rten/issues/98.
See also https://github.com/robertknight/rten/issues/399#issuecomment-2466625999.

Re-order execution plan to enable more operations to run in-place

---

src/graph.rs
src/model.rs
src/ops/control_flow.rs
src/ops/mod.rs
src/optimize.rs

When preparing the capture environment to pass to an operator with subgraphs, if a captured value is not going to be needed by subsequent operators in the current graph then it can be passed by value rather than by reference. In the subgraph, this allows the value to be (potentially) used as an in-place input.
- Pass `CaptureEnv` to `Graph::run_subgraph` by value rather than by reference
- Add map of by-value captures to `CaptureEnv`
- Add `CaptureEnv::child` method which creates a child environment with no captures of its own. This is not currently used but will be needed by loop operators which run a subgraph more than once and need to obtain a fresh capture environment for each iteration.
Part of https://github.com/robertknight/rten/issues/399.

Support passing captures by-value to subgraphs

---

rten-generate/src/generator.rs

Hugging Face models with separate branches for the first and subsequent iterations do not use the input KV cache buffer on the first run. Thus they did not benefit from the pre-allocated capacity and ended up re-allocating a new KV cache buffer on each run.
To resolve this, change the KV cache growth strategy to grow the buffer after the model runs, if the capacity limit has been reached. Also replace the hard-coded capacity with a growth strategy that doubles the capacity each time. This amortizes the costs of copying the old KV cache into the new buffer.
This impacts the Whisper and TrOCR examples. For the Whisper example, this reduced time for transcribing a 2-minute audio clip with the base model from ~6.1s to ~5.7s (~6%). With the larger models the benefit will be greater since the …

Reserve KV cache capacity after the first model run

---

rten-tensor/src/copy.rs

Improve code path for tensors with 5+ dimensions in `TensorBase::init_from`. Instead of falling back to slow iteration via `TensorBase::iter`, iterate over inner views of 4 dims and use the faster code path that handles this.
This was encountered while testing https://huggingface.co/briaai/RMBG-2.0.

Optimize copying of non-contiguous tensors with 5+ dimensions

---

src/ops/gather.rs

Optimize GatherND by:
- Avoiding redundant zeroing of the output buffer
- Adding a fast path for contiguous inputs. This allows skipping of expensive slicing of the input for each element. Instead we just compute the offset of the start of the gathered chunk for each index and copy to the output.
The fallback path for non contiguous inputs could be further optimized by creating the slice view once and just shifting the base offset on each iteration.
**TODO:**

Optimize GatherND by avoiding redundant zeroing of output and adding fast path for contiguous inputs

---

rten-tensor/src/iterators.rs
rten-tensor/src/tensor.rs
src/number.rs
src/ops/gather.rs
src/ops/operators.rs
src/ops/reduce.rs
src/ops/variadic_elementwise.rs

Add a fast path for the common case where the min/max index is taken along a contiguous (stride-1) axis.
- Add `Lane::as_slice` method for getting the remainder of a lane yielded by `tensor.lanes(axis)`, if the lane has stride 1
- Add fast path in `ArgMin`/`ArgMax` which leverages `Lane::as_slice`

Add fast path for ArgMin / ArgMax when axis is contiguous

---

src/gemm.rs
src/ops/conv/im2col.rs
src/ops/mod.rs

This allows for a wider range of kernel tile sizes, as long as the total number of elements is less than the maximum.

Use a single value for the maximum temporary GEMM tile size

---

rten-examples/Cargo.toml

This avoids the overhead of building and running an empty test binary for each example when running `cargo test --workspace`.

Disable tests for example binaries

---

rten-generate/src/generator.rs
rten-generate/src/text_decoder.rs
rten-imageproc/src/shapes.rs
rten-tensor/src/impl_debug.rs
rten-tensor/src/impl_serialize.rs
rten-tensor/src/iterators.rs
rten-tensor/src/layout.rs
rten-tensor/src/storage.rs
rten-tensor/src/tensor.rs
rten-tensor/src/type_num.rs
src/gemm.rs
src/model.rs
src/model_builder.rs
src/ops/conv/im2col.rs
src/ops/mod.rs
src/tensor_pool.rs
src/timing.rs

Remove various lifetimes in impl headers that were not necessary, as the body of the impl did not reference them.

Apply clippy fixes suggested in Rust v1.83

---

src/ops/matmul.rs

The ONNX spec states that the MatMul operator is a "Matrix product that behaves like numpy.matmul". TIL that `numpy.matmul` supports vector inputs:
> If the first argument is 1-D, it is promoted to a matrix by prepending a 1
> to its dimensions. After matrix multiplication the prepended 1 is removed.
> If the second argument is 1-D, it is promoted to a matrix by appending a 1
> to its dimensions. After matrix multiplication the appended 1 is removed.
Implement this behavior in RTen.

Support vector inputs in MatMul operator

---

rten-cli/src/main.rs
rten-convert/rten_convert/converter.py
rten-convert/rten_convert/schema_generated.py
src/graph.rs
src/lib.rs
src/model.rs
src/model_builder.rs
src/op_registry.rs
src/ops/mod.rs
src/optimize.rs
src/optimize/pattern_matcher.rs
src/schema.fbs
src/schema_generated.rs

Support storing and querying the expected runtime dtype of a value node in models, and convert the corresponding information from ONNX models in the rten-convert tool. In the RTen CLI, use this information to generate random data of the appropriate type for model inputs.
The dtype is not enforced at runtime, so you can still pass an f32 tensor for an input expecting i32. In that case you will probably get an inference operator from somewhere in the model.
As a test case, with this branch you can convert and run the [magika models](https://github.com/google/magika/tree/main/assets/models/standard_v2_1) using the rten CLI. Previously running the model with the CLI would fail because it always generated randomized inputs with `f32` elements, but this particular model has a `bytes` input of …

Add data type information to value nodes

---

src/graph.rs

The passed node count should only be used to reserve space in collections that will have an entry for all or most nodes. That doesn't include the lists of input, output and capture node IDs.

Fix excess capacity reservation in `Graph::with_capacity`

---

src/model.rs

In the existing test that runs all operators, run the model twice. The first time the operator's main input is passed as a view, the second time as an owned tensor. This enables running the operator in-place if supported. This is an easy way to gain some additional coverage of `Operator::run_in_place` implementations.

Test running all operators in-place

---

rten-generate/src/text_decoder.rs
rten-text/src/tokenizers.rs
rten-text/src/tokenizers/bpe.rs
rten-text/src/tokenizers/json.rs
rten-text/tests/reftest.rs
src/ops/resize.rs

Support a behavior in the CLIP tokenizer [1] where a suffix (`</w>`) is implicitly appended to each substring produced after regex splitting, before BPE tokenization is applied.
Extracted from https://github.com/robertknight/rten/pull/421.
[1] https://github.com/openai/CLIP/blob/main/clip/simple_tokenizer.py

Support `end_of_word_suffix` in BPE tokenizers

---

src/ops/concat.rs

If in-place Concat is not possible because the buffer doesn't have enough spare capacity, return it to the pool so it can be re-used for subsequent operations. This avoids the overhead of freeing it immediately using the system allocator.

Return input to pool if we can't append in Concat operator

---

rten-examples/src/gpt2.rs
rten-examples/src/jina_similarity.rs
rten-examples/src/qwen2_chat.rs
rten-examples/src/whisper.rs
rten-generate/src/text_decoder.rs
rten-text/src/tokenizers.rs
rten-text/src/tokenizers/bpe.rs
rten-text/src/tokenizers/wordpiece.rs
rten-text/tests/reftest.rs

- Allow an `&str` to be passed to `Tokenizer::encode` directly, instead of requiring the caller to use `str.into()` to construct an `EncoderInput`
- Make the options argument an `Option`. This makes it more obvious how to pass nothing, and easier.
- Add a `Tokenizer::decode` method which wraps `Encoder::decode` for symmetry with `Tokenizer::encode`
- Add `Encoded::into_token_ids` to make it easier to get the encoded token IDs as an owned vector and discard offset information

Improve ergonomics of encoding and decoding text with `Tokenizer`

---

rten-text/src/models/wordpiece.rs
rten-text/src/tokenizers.rs
rten-text/tests/reftest.rs

Move normalization logic from `<WordPiece as Model>::encode_with_offset` impl to `Tokenizer::encode`. This makes it work with all tokenization models.
Part of https://github.com/robertknight/rten/issues/427.

Move normalization from model into Tokenizer

---

rten-generate/src/text_decoder.rs
rten-text/src/lib.rs
rten-text/src/models/bpe.rs
rten-text/src/models/wordpiece.rs
rten-text/src/pre_tokenizers.rs
rten-text/src/pretokenizers.rs
rten-text/src/split.rs
rten-text/src/tokenizers.rs
rten-text/src/tokenizers/json.rs
rten-text/tests/reftest.rs

As part of https://github.com/robertknight/rten/issues/427, extract the input splitting logic out of the `WordPiece` and `Bpe` tokenization models and make it a separate pre-tokenization step in the pipeline executed by `Tokenizer`.
**TODO:**

Extract pre-tokenization out of tokenization models

---

rten-examples/src/qwen2_chat.rs
rten-examples/src/whisper.rs
rten-generate/src/text_decoder.rs
rten-text/src/models.rs
rten-text/src/models/bpe.rs
rten-text/src/models/wordpiece.rs
rten-text/src/normalizer.rs
rten-text/src/pre_tokenizers.rs
rten-text/src/tokenizers.rs

Re-organize the `Model` trait and associated error types in rten-text to align with the structure of traits and error types for other phases of tokenization. In the process add a dummy error type for normalization errors. None of the current normalizers are fallible, but additional ones added soon will be.
For consumers, there are breaking changes for pattern-matching errors and also `Model::get_token_id` now returns an `Option` rather than `Result`. Consumers can use `Tokenizer::get_token_id` instead which does return a result.

(rten-text) Re-organize `Model` trait and associated error types

---

rten-examples/Cargo.toml
rten-examples/README.md
rten-examples/src/nougat.rs
rten-text/src/tokenizer.rs
rten-text/src/tokenizer/json.rs

[Nougat](https://github.com/facebookresearch/nougat) is a model that performs OCR on images of academic PDFs and outputs markdown.
The example code is essentially the same as the TrOCR example with adjustments to the preprocessing (different image size, different normalization constants) and decoder input names. In fact this example could potentially be unified with TrOCR by taking the path to `preprocessor_config.json` as input.
Tokenization requires some normalizer and pre-tokenizer features which are not currently supported. However since the prompt is trivial (a single fixed token), the example works if we just use stub implementations of these.
The [paper](https://arxiv.org/pdf/2308.13418) mentions a repetition detection system they use to deal with one of the model's failure cases. …

Add Nougat OCR example

---

rten-examples/Cargo.toml
rten-examples/README.md
rten-examples/src/clip.rs
rten-examples/src/clip_reference.py

Add an example that matches images against text descriptions using the [CLIP](https://github.com/openai/CLIP) model.
**TODO:**
This requires adding some additional tokenizer features in rten-text:

Add CLIP example

---

rten-generate/src/text_decoder.rs
rten-text/src/models.rs
rten-text/src/models/bpe.rs
rten-text/src/tokenizer.rs
rten-text/tests/reftest.rs

In preparation for https://github.com/robertknight/rten/issues/453, do a pass over the BPE tokenizer to clean up outdated documentation and make passing configuration to `Bpe::new` more readable / easier to extend by using an options struct.

Clean up outdated comments in BPE tokenizer, pass configuration as a struct

---

src/ops/reduce.rs
src/slice_reductions.rs

Add a better implementation of sum-of-squares for a contiguous slice. This is used in the step that computes the inverse standard deviation of the input.
Tested on the encoder from [Donut](https://huggingface.co/naver-clova-ix/donut-base-finetuned-docvqa) this reduced time in the LayerNormalization operator by ~15%. There is still low-hanging fruit in this operator before parallelization: use of SIMD, fusion of the in-place binary operators, use of FMA.

Optimize inverse root-mean-squared sub-step in LayerNormalization

---

rten-simd/src/dispatch.rs
rten-vecmath/src/lib.rs
rten-vecmath/src/softmax.rs
rten-vecmath/src/sum.rs
src/ops/norm.rs
src/ops/reduce.rs

Vectorize these reductions for f32 inputs. For LayerNormalization under AVX2 this gives a modest speedup of ~13%. The ReduceSum and ReduceSumOfSquares ops don't benefit yet. Those ops are generic to support int tensors, so some additional work is required to support having both a generic and a specialized path.
A non-vectorized fast path for contiguous slices was added in ReduceSum though, since this is a trivial change.

Vectorize sum and sum-of-square reductions in ReduceMean, ReduceL2, InstanceNormalization, LayerNormalization ops

---

rten-simd/src/dispatch.rs
rten-simd/src/functional.rs
rten-simd/src/vec.rs
rten-vecmath/src/softmax.rs
rten-vecmath/src/sum.rs

- Add methods to simplify implementing tail handling in SIMD ops
- Make `SimdOp::eval` take `self` by value rather than immutable reference. This allows for ops which store a mutable slice in their fields which they write to

Add `SimdFloat::{load_partial, store_partial}`, make `SimdOp::eval` take self by value

---

rten-simd/src/arch.rs
rten-simd/src/arch/aarch64.rs
rten-simd/src/arch/scalar.rs
rten-simd/src/arch/wasm.rs
rten-simd/src/arch/x86_64.rs
rten-simd/src/functional.rs
rten-simd/src/lib.rs
rten-simd/src/vec.rs
rten-vecmath/src/exp.rs

Rename the base trait from `SimdVal` to `Simd` and move methods for functionality common to all element types (load, store, splat, blend etc.) there. This allows making some SIMD code generic over the element type, such as the `simd_map`, `simd_gather_mask` and `simd_fold` helpers.

Move common SIMD vector functionality to base trait

---

src/gemm.rs
src/graph.rs
src/ops/conv.rs
src/ops/matmul.rs
src/ops/mod.rs
src/optimize.rs

Fuse MatMul -> Add subgraphs where the second input to `Add` is a constant bias vector. Unlike earlier matmul + bias fusions, the bias is treated as a row rather than column vector in this case, so this also adds support for that in the GEMM implementation.
In the process I spotted an existing bug in the handling of matmul operations with k=0. In that case the bias was not added to the output.

Fuse `Add(MatMul(a, b), bias)` subgraphs

---

rten-tensor/src/type_num.rs

Impl `IndexCount` and `IsIndex` for SliceRange. This allows use of ranges with steps in `tensor.slice` calls. eg. `tensor.slice(SliceRange::new(0, None, 2))` returns a slice with every other item along the first axis.

Support using `SliceRange` in `TensorBase::slice` calls

---

rten-tensor/src/copy.rs
rten-tensor/src/tensor.rs
src/ops/reduce.rs
src/slice_reductions.rs
src/tensor_pool.rs

Each `Reduce*` op has two implementations of the main reduction loop: one optimized for contiguous inputs and one for non-contiguous inputs. This means that each reduction had to be implemented twice and the fallback's efficiency was worse by a varying amount.
Simplify this by making reductions of non-contiguous inputs pack slices of the input into a contiguous buffer before reducing. This means that only one implementation of the inner reduction loop is needed per `(operation, data type)` combination. It also means the cost of the fallback is more predictable. Also dynamic dispatch can now be used to dispatch the inner reduction loop. This trades off reduced code size at the cost of some overhead per call. The overhead of that depends on the size of reduced slices.

Use packing buffer when reducing non-contiguous tensors

---

rten-vecmath/src/lib.rs
rten-vecmath/src/shift_scale.rs
src/model.rs
src/ops/norm.rs
src/ops/reduce.rs

Optimize the LayerNormalization implementation by:
1. Re-organizing the process to be more cache efficient. Instead of applying each step in the process to the whole input before moving on to the next, apply the whole normalization process to each normalized slice individually. This means we only load each slice into cache once (assuming each slice fits in L1)
2. Fusing the steps that normalize the variance and apply the `bias` and `scale` into one vectorized pass
Tested on [docvqa](https://huggingface.co/naver-clova-ix/donut-base-finetuned-docvqa) this speeds up `LayerNormalization` in the encoder by 2.5-3x.

Optimize LayerNormalization for better cache efficiency + SIMD

---

rten-simd/src/arch/aarch64.rs
rten-simd/src/arch/scalar.rs
rten-simd/src/arch/wasm.rs
rten-simd/src/arch/x86_64.rs
rten-simd/src/vec.rs

This makes it available for float vectors as well. Not currently used, but may be useful for some upcoming work on MatMul with unpacked LHS inputs.

Move `to_array` method from `SimdInt` to `Simd` trait

---

rten-vecmath/src/shift_scale.rs
rten-vecmath/src/sum.rs
rten-vecmath/src/tanh.rs

Previously calling `vec_shift_scale_in_place` with slices of unequal length could lead to OOB reads. Now it will panic.

Add missing slice length checks for `vec_shift_scale_in_place`, better docs for other vectorized functions

---

rten-convert/rten_convert/converter.py
rten-convert/rten_convert/schema_generated.py
src/model.rs
src/model_builder.rs
src/op_registry.rs
src/ops/layout.rs
src/ops/mod.rs
src/schema.fbs
src/schema_generated.rs

Implement the [DepthToSpace](https://onnx.ai/onnx/operators/onnx__DepthToSpace.html#summary) operator (aka. [PixelShuffle](https://pytorch.org/docs/stable/generated/torch.nn.PixelShuffle.html)). Used by the EDSR models in [super-image](https://github.com/eugenesiow/super-image) and others.

Support DepthToSpace operator

---

rten-simd/src/vec.rs
rten-vecmath/src/lib.rs
rten-vecmath/src/shift_scale.rs
rten-vecmath/src/sum.rs
src/ops/norm.rs

InstanceNormalization has two steps:
1. Compute channel mean and variance
2. Shift and scale result to normalize the mean and variance, and then apply a per-channel scale and bias
BatchNormalization is similar but uses precomputed values for step 1. Previously part of step 1 was vectorized, but not the variance calculation. Add a vectorized kernel for step 2 and use it for BatchNormalization and InstanceNormalization.
This can be further improved in future by:
- Computing both the mean and variance in one pass over the input
- Unifying LayerNormalization and BatchNormalization / InstanceNormalization
Tested using the wav2vec example on x64, this made InstanceNormalization ~3x faster (~26ms -> ~8ms per run).

Vectorize InstanceNormalization and BatchNormalization

---

rten-tensor/src/tensor.rs
src/ops/conv.rs
src/ops/einsum.rs
src/ops/layout.rs
src/ops/matmul.rs

Remove a long-standing footgun where `TensorBase::reshaped` would panic if the caller failed to ensure that it was contiguous first. Instead it will now copy if needed. A variant `reshaped_in` has been added so an allocator can be provided as necessary. The related `reshaped_mut` method now returns an error instead of panicking if the result is not contiguous. It cannot copy since it is used in contexts where writing to a copy would be useless. This change at least makes the caller aware of the need to handle this case.
A downside of this change is that the lifetime of the result is shorter since it may be owned. That turned out not to be too inconvenient to deal with.

Make `TensorBase::reshaped` copy instead of panic if input is not contiguous

---

rten-simd/src/arch/aarch64.rs
rten-simd/src/arch/scalar.rs
rten-simd/src/arch/wasm.rs
rten-simd/src/arch/x86_64.rs
rten-simd/src/dispatch.rs
rten-simd/src/functional.rs
rten-simd/src/vec.rs
rten-vecmath/src/normalize.rs
rten-vecmath/src/softmax.rs
rten-vecmath/src/sum.rs

Simplify usage of these functions by removing the `pad` argument and always setting unused lanes to zero. This was already the case in most places, with a few exceptions for reductions where using zero as a padding value affected the
final result. Handle this instead by using the accumulator for the one-before-last update for the lanes that are unused in the final update.
As well as simplifying usage, this also allows for translating partial loads into masked loads.

Remove `pad` argument from `Simd::load_partial`, `simd_fold`, `simd_map`

---

rten-tensor/src/storage.rs

`Storage::slice` does a bounds check on the passed range, but we don't need to do this if we're using the full range of the `self` storage. This change in turn makes `TensorBase::storage` cheaper.

Avoid a redundant bounds check in `Storage::view` impls

---

src/gemm.rs
src/gemm/kernels.rs

When a matmul is performed using a prepacked input, verify that the input was prepacked with the same configuration that is later used during computation. This includes the block sizes and kernel ID.
Adding early checks avoids a harder-to-debug error later if the prepacked buffer doesn't have the expected length or worse, incorrect results.

Check that prepacked matmul inputs are using matching configuration

---

src/gemm.rs
src/gemm/kernels.rs
src/gemm/kernels/aarch64.rs
src/gemm/kernels/generic.rs
src/gemm/kernels/simd_generic.rs
src/gemm/kernels/wasm.rs
src/gemm/kernels/x86_64.rs

This avoids the overhead of packing, at the cost of potentially more expensive loads from the LHS in the kernel as rows are spaced further apart in memory.
Some [initial GEMM benchmarks](https://docs.google.com/spreadsheets/d/1d1pGSILVqGDwj9g5Lh2R4XuYXDrKI3c7SVC9wxXO2mc/edit?gid=1760158567#gid=1760158567) on my i5 laptop suggest that performance is unchanged for large matrices and very slightly better for small matrices. On real models I see a very slight win, but not statistically significant. What stands out much more are spikes for friendly and unfriendly sizes (M and N being multiples of MR and NR respectively).
See https://github.com/robertknight/rten/issues/415.

Avoid packing LHS input to GEMM kernel if column stride is 1

---

rten-bench/README.md
rten-generate/README.md
rten-imageio/README.md
rten-simd/src/README.md
rten-vecmath/README.md

Each crate directory root contains a short README summarizing what it is for. Update the rten-vecmath README that was out of date and add these files to other crates that were missing them.

Update crate READMEs

---

src/gemm.rs
src/gemm/kernels.rs
src/gemm/kernels/aarch64.rs
src/gemm/kernels/generic.rs
src/gemm/kernels/simd_generic.rs
src/gemm/kernels/wasm.rs
src/gemm/kernels/x86_64.rs

For performance the GEMM internals use raw pointers for output tiles, which may be uninitialized if `beta` is zero. Add lifetimes to `OutputTiles` and make more use of `MaybeUninit<OutT>` to track the initialization status of each output tile through the implementation.

Better track output buffer lifetime and initialized state via types in GEMM internals

---

src/gemm.rs
src/gemm/kernels.rs

In preparation for longer-lived pre-packed matrices, reduce the number of parameters that affect the packed layout and have to be kept the same at the time of pre-packing and later usage.
Previously the packed layout depended on the NC, KC, MC, MR and NR blocking parameters, plus the size of the input matrix. Change it so that it only depends on the MR and NR parameters for packed A and B matrices respectively. The NC parameter varied depending on the thread pool size, so prepacked buffers would become unusable if the thread pool size changed.
This is achieved by revising the packed layout so that packed A matrices with shape `M*K` are laid out as row panels of height MR and width K.  Packed B matrices with shape `K*N` are laid out as column panels of width NR and height K. Compared to …

Refactor GEMM prepacking to depend on fewer blocking parameters

---

rten-cli/src/main.rs
src/gemm.rs
src/graph.rs
src/lib.rs
src/model.rs
src/ops/control_flow.rs
src/ops/einsum.rs
src/ops/fused.rs
src/ops/matmul.rs
src/ops/mod.rs
src/ops/operators.rs
src/wasm_api.rs
src/weight_cache.rs

This reduces inference time for matmul operations at the cost of higher memory usage. Prepacking is initially disabled by default as there are common situations (single inference run, large transformer decoder models) where it isn't worthwhile. It is enabled via `ModelOptions::prepack_weights`:
```rs
let mut model_options = ModelOptions::with_all_ops();
model_options.prepack_weights(true);
let model = model_options.load_file(path)
```
To facilitate a quick comparison of the performance impact of prepacking, the rten CLI now has a `--prepacked` option to enable prepacking.
There are some caveats:
- Non-MatMul operations which use matmuls internally (Conv, ConvTranspose, LSTM, GRU etc.) currently don't prepack their weights.
- MatMul operations which turn out to be matrix-vector (gemv) …

Support pre-packing weights after model optimization

---

src/graph.rs

Return an error instead of panicking if an input ID or output ID passed to `Graph::run` is not a valid value node ID (or constant node ID for outputs).

Return planning error if input or output ID is an operator

---

src/ops/matmul.rs
src/ops/mod.rs
src/optimize.rs

A subgraph of the form `Mul(MatMul(Mul(A, c), Mul(B, d)), e)` where all of the `Mul`s are optional and c, d and e are constants can be rewritten as `MatMul(A, B, alpha = c * d * e)` where `alpha` is the scaling already handled by the `C = alpha * AB + beta * C` result that GEMM already computes. Such scaling is common in transformers as part of attention operations (SDPA).
The initial implementation only handles two specific cases of this form which have been seen in real models. This should be generalized to all possible cases.

Fuse MatMul + Mul/Div by constant

---

src/graph.rs
src/optimize.rs

Fuse all patterns of the form `Scale(MatMul(Scale(X), Scale(Y)))` where
`Scale(X)` is an optional `Mul` or `Div` operation where one of the arguments is
a scalar. Previously only two specific cases of this pattern were handled.
Fixes https://github.com/robertknight/rten/issues/488

Generalize scaled MatMul fusion

---

src/graph.rs
src/graph/capture_env.rs
src/graph/node.rs
src/graph/node_id.rs

The `graph` module had grown to over 3K lines. To make it a little less unwieldy, extract the types for graph nodes, node IDs and capture environments into submodules.

Extract submodules out of `graph.rs`

---

src/graph.rs
src/graph/planner.rs

Extract the execution planning methods out of `Graph` and into a separate `Planner` type in a `planner` submodule. Also move the associated `CaptureEnv` and `PlanOptions` types there.
This is another step in breaking down the large `graph` module into more manageable pieces.

Extract execution planner into a submodule

---

rten-vecmath/src/exp.rs
rten-vecmath/src/lib.rs
src/ops/mod.rs
src/ops/unary_elementwise.rs
src/optimize.rs

Add a vectorized implementation of the Swish activation function that computes `x * sigmoid(beta * x)` and a graph fusion. Swish is used by [CLIP](https://huggingface.co/openai/clip-vit-base-patch32). This function is a generalization of the existing SiLU operator, which is similar except there is no `beta` parameter. The `Silu` operator could potentially be replaced with `Swish { beta: 1 }` in future, with a fast path in the kernel to handle the `beta = 1` case.
A few aspects of the implementation are slightly different than other parallel, vectorized unary operators because this is the first such case where are parameters in addition to the input.
Related spec issue: https://github.com/onnx/onnx/issues/5853

Fuse Swish operations

---

rten-simd/src/dispatch.rs
rten-vecmath/src/erf.rs
rten-vecmath/src/exp.rs
rten-vecmath/src/lib.rs
rten-vecmath/src/normalize.rs
rten-vecmath/src/softmax.rs
rten-vecmath/src/sum.rs
rten-vecmath/src/tanh.rs
src/ops/norm.rs
src/ops/reduce.rs
src/ops/unary_elementwise.rs

Previously each operation in rten-vecmath was exposed as three functions: one for scalars, one that read/wrote different slices and one that mutated a slice in place. This led to quite a bit of boilerplate for each operation added.
Refactor this so that for unary functions rten-vecmath just exports a struct which implements the operation. Dispatch is then handled by the caller using trait methods of `SimdUnaryOp`.
As part of this, drop the `Simd*` prefix from type names and `vec_*` prefix from functions. They were not informative since most functions/types in the crate had them. The caller can rename the imports if they conflict.

Refactor rten-vecmath APIs to reduce boilerplate

---

rten-tensor/src/layout.rs
rten-tensor/src/lib.rs
rten-tensor/src/tensor.rs
src/ops/gather.rs

Optimize the Gather operator by:
- Adding a fast path for the case where `axis=0` and the input is contiguous. The output is then constructed by just copying contiguous chunks of the input to the output. This occurs when a transformer gathers embedding vectors from a `[token_id, d_embed]` matrix for example.
- Improving the general case by taking advantage of the fact that the layout of the gathered input slice and output slice is the same for each index, so we can construct the layout once and re-use them with different storage offsets on each iteration
Using the T5-small model, time spent in Gather ops for a sequence length of 512 goes from ~60ms to ~5ms using the fast path or ~25ms using the general path.
```
rten models/t5-small/encoder_model.rten -s encoder_sequence_length=512
```

Optimize Gather with fast path for axis=0 case and avoiding slicing in general case

---

src/ops/mod.rs
src/ops/norm.rs
src/optimize.rs

Fuse the simplified layer normalization subgraphs used in T5, Llama etc. Unlike LayerNormalization this doesn't center the mean and scales the input using the root mean squared rather than variance statistic.
Fixes https://github.com/robertknight/rten/issues/495.

Fuse RMSNorm subgraphs

---

src/graph.rs
src/graph/builder.rs
src/optimize.rs

Add a utility that makes it easier to generate graphs with a specific structure in tests by generating them from objects that read like math expressions. Use this to simplify some of the graph fusion tests.
```rs
// Gelu(x) = x * 0.5 * (1 + Erf(x / sqrt(2)))`
let x = Expr::value("x");
let sqrt_2 = Expr::constant((2.0f32).sqrt());
let one = Expr::constant(1.0);
let half = Expr::constant(0.5);
let expr = x.clone() * (Expr::unary(Erf {}, x / sqrt_2) + one) * half;
let gelu_graph: Graph = expr.build_graph(["x"]);
```
The above expressions are somewhat similar to the pattern matcher used by the graph optimizer, but there are differences because patterns have slots (eg. for constants) that can be filled by matched values, whereas expressions do not.

Add utility to simplify writing graph tests by generating graphs from expression objects

---

src/graph/builder.rs
src/optimize.rs

Use `graph::builder` to simplify how these graphs are constructed and make it easier to follow what the fusions match.

Simplify unfused layer norm graph construction in tests

---

src/graph/builder.rs
src/optimize.rs

Refine the `Expr` APIs and associated helpers in `optimize.rs` to be simpler to use. `Expr::{unary, binary}` are now methods, the helpers in `optimize.rs` are moved into an extension trait and binary operators for `Expr` accept any `Into<Tensor<f32>>` as the RHS, so `some_expr + 2.0` just works without having to first wrap up the constant as an expression using `some_expr + Expr::constant(2.0)`.

Refine `graph::build::Expr` APIs

---

src/gemm.rs
src/gemm/kernels.rs
src/gemm/kernels/aarch64.rs
src/gemm/kernels/generic.rs
src/gemm/kernels/wasm.rs
src/gemm/kernels/x86_64.rs

For tiles with fewer than NR columns, the GEMM impl creates a temporary tile on the stack, runs the kernel on that and copies the result into the real output tile afterwards. For architectures with masked loads and stores more efficient approaches are possible. As a step to enable this, move handling of non-full width tiles into the arch-specific kernels.

Push handling of non-full width tiles down into GEMM kernels

---

rten-simd/src/arch/x86_64.rs
rten-vecmath/src/softmax.rs

Fix a compile error in the `Simd::store` impl for `__m512i` and make the rten-vecmath tests pass by allowing a fractionally larger difference between the vectorized and scalar variants for softmax. This is expected since softmax involves sum reductions and those occur in a different order in the SIMD version.

Fix AVX-512 build

---

rten-simd/src/dispatch.rs
rten-vecmath/src/erf.rs
rten-vecmath/src/exp.rs
rten-vecmath/src/softmax.rs
rten-vecmath/src/tanh.rs

Previously the implementation of vectorized ops was split into two parts: a `simd_{op}` internal function and the `SimdUnaryOp::eval` impl which provided a way for SIMD dispatch to invoke `simd_{op}`. The main reason for the separation was so that one SIMD operation could invoke another easily by calling eg. `simd_exp(x)`.
Remove this separation by inlining the `simd_{op}` function into the `eval` impl. To assist with one SIMD op calling another, add a `SimdUnaryOp::apply` helper. This means that eg. softmax can calling exp using `Exp::apply(x)`.
An upside of this change is that consumers of the crate can more easily call the operations in their own vectorized ops. The downside is that it adds some indirection for the reader.

Inline `simd_{op}` functions into `SimdUnaryOp::eval` impls

---

src/gemm.rs
src/gemm/kernels.rs
src/gemm/kernels/aarch64.rs
src/gemm/kernels/generic.rs
src/gemm/kernels/simd_generic.rs
src/gemm/kernels/wasm.rs
src/gemm/kernels/x86_64.rs
src/gemm/packing.rs
src/number.rs

Previously the GEMM code assumed that data would be packed in the same format as the LHS / RHS input types, and with a fixed layout. To support new data types, especially int8, more flexibility will be needed.
- int8 matmuls using dot product rather than FMA instructions will use a different blocked layout
- For some architectures / data types it will make sense to expand inputs to a wider data type during packing rather than in the kernel
- For some architectures / data types the kernel can operate on an unpacked LHS matrix, if it has unit column stride. For others packing will always be required.
To enable this:
- Add `Kernel` methods which return descriptors specifying the size and alignment required for packing a particular A or B input.
- Modify kernel interface to use opaque `[u8]` …

Make packing of GEMM inputs more flexible

---

src/gemm.rs
src/gemm/kernels.rs
src/gemm/packing.rs

https://github.com/robertknight/rten/pull/510 noted that the layout of pre-packed matrices required the generic GEMM code to know about the layout of data within a packed panel. This revises the layout so that is no longer the case. See the last commit for details. After this change it will be possible to use different panel layouts for each kernel. int8 kernels for example will use dot product instructions that require a different block layout than f32 kernels using FMA instructions.
Along the way I also added some comments about where the cache and register blocking sizes come from. These are explained in the referenced paper, but it is useful to have them more immediately accessible.

Restructure pre-packed matrix layouts so generic GEMM code can be agnostic of panel layout

---

src/gemm/kernels/aarch64.rs
src/gemm/kernels/generic.rs
src/gemm/kernels/simd_generic.rs
src/gemm/kernels/wasm.rs
src/gemm/kernels/x86_64.rs

Make handling of tail tiles with fewer than MR rows more efficient by
instantiating ukernel bodies for each possible number of used rows. The entry
point for each kernel switches on the actual number of used rows and jumps to
the appropriate implementation. Adds ~32KB to the binary size of the CLI.

Instantiate main GEMM loop per number of used rows

---

src/gemm.rs
src/ops/conv.rs
src/ops/matmul.rs
src/ops/rnn.rs

Combine the `GemmExecutor` methods that take biases and those that don't. This streamlines the API a little. When new GEMM "extensions" are added in future, they should probably be part of an options struct to avoid having methods for the cross-product of GEMM extensions.
This highlights a few existing places where code calls `GemmExecutor::gemm` without a bias and then immediately adds one. This could likely be fused.

Unify gemm APIs with and without bias arguments

---

rten-cli/src/dim_size.rs
rten-cli/src/main.rs

This is a collection of improvements related to handling of dimension size arguments (`--size`/`-s`) in the CLI:
- Only print one message per unique dimension name for which no size is explicitly specified. This reduces the output noise in models which have a lot of KV-cache inputs with the same dimension names
- Error if an explicitly specified size is unused. This probably indicates a typo and may cause the model to fail to run or do much less work that intended (eg. if a batch size is changed from N > 1 to 1)
- If a dimension size is specified both with and without an input name, make the one with the input name take precedence
- If a dimension size is specified multiple times, make the last `--size` argument take precedence
- Add tests for dimension size spec parsing

Improve parsing of dimension size specs in CLI

---

src/gemm/kernels/simd_generic.rs
src/iter_util.rs

For most architectures the compiler unrolls the main GEMM loop as requested. For AVX-512 however it didn't. To fix this, swap out the unroll macro for one which uses a more aggressive method to force unrolling.
See https://gist.github.com/robertknight/948170d4edb048804105a99cb4831b4b for a before/after comparison of the assembly.

Use a more aggressive approach to unrolling in `simd_gemm`

---

rten-simd/src/arch/aarch64.rs
rten-simd/src/arch/scalar.rs
rten-simd/src/arch/wasm.rs
rten-simd/src/arch/x86_64.rs
rten-simd/src/vec.rs
src/gemm.rs
src/gemm/im2col.rs
src/gemm/kernels.rs
src/gemm/kernels/aarch64.rs
src/gemm/kernels/generic.rs
src/gemm/kernels/wasm.rs
src/gemm/kernels/x86_64.rs
src/ops/conv.rs
src/ops/conv/im2col.rs

im2col packing was done outside of the `gemm` module via the `VirtualMatrix` abstraction. This wasn't a good abstraction since im2col packing is deeply tied to the kernel implementation and needs to know about the packing buffer layout and NR / NR_REGS parameters.
Refactor this by splitting the im2col module into two parts:
- The code that builds the image <-> im2col row/column mappings, which has no unsafe code and minimal kernel-specific knowledge (just the step/increment which the column count must be a multiple of). This lives in `ops::conv::im2col`.
- The code that packs part of an image using the pre-built row/col mappings. This is now handled by the gemm module in `gemm::im2col`.
TODO:

Make im2col packing part of the gemm module

---

rten-examples/Cargo.toml
rten-examples/README.md
rten-examples/src/modernbert.rs
rten-examples/src/modernbert_reference.py
rten-text/src/tokenizer.rs

Add a basic BERT example that uses a base model for masked word prediction. It is specifically intended for use with ModernBERT but also works with the OG BERT model and DistilBERT.
The tokenization code is verbose because rten-text treats special tokens as ordinary text. That's good for safety when tokenizing untrusted user input, but awkward for contexts where the input is trusted. Also the `decode` API is missing an equivalent of `strip_special_tokens=True`.

Add masked word prediction example for BERT base models

---

src/ops/conv.rs

Consolidate tests for invalid Conv inputs into one table driven test and make the Conv operator return an error instead of panicking if the group count is zero.

Refactor tests for invalid Conv inputs, fix panic if group count is zero

---

rten-tensor/src/tensor.rs
src/gemm.rs

These tests originally used dynamic rank tensors because the static-rank ones were a separate and more limited type. That's no longer the case, so port the tests to use static rank tensors which is the more natural choice.
The line count grew by 50 lines due to formatting changes after `run_gemm(&mut result, &a, &b, ...)` -> `run_gemm(result.view_mut(),
a.view(), b.view(), ...)` - ¯\_(ツ)_/¯
Along the way I revised the old descriptions for `TensorBase` aliases to make the owned / view distinction clearer and simplify them.

Use static rank tensors in GEMM tests

---

src/gemm.rs

In a matmul where K=0, bias column vectors were being incorrectly broadcast as if they were a row vector. This went unnoticed for two reasons:
1. The test was missing a check for equality between actual and expected results.
2. The M and N sizes were the same in the only test where K=0, so no broadcast error occurred.

Fix handling of bias column vectors when K=0

---

src/gemm.rs
src/gemm/errors.rs
src/gemm/kernels.rs
src/gemm/kernels/aarch64.rs
src/gemm/kernels/generic.rs
src/gemm/kernels/wasm.rs
src/gemm/kernels/x86_64.rs
src/number.rs
src/ops/conv.rs
src/ops/matmul.rs
src/ops/rnn.rs

Add support for passing quantization parameters (ie. zero points) to the GEMM kernel and `GemmExecutor` and use this to implement a minimal (and still very slow) generic u8 x i8 -> i32 kernel. Then convert `MatMulInteger` to this instead of its temporary implementation. Also add tests that do int8 matmul for all square matrices up to 20x20 in size plus varying other "interesting" sizes.
After this will come work on optimized int8 kernels using the native dot product instructions on various platforms.
In the current design both quantized and non-quantized GEMMs share the same interface. f32 GEMMs just don't use the quantization parameters. This is convenient as it allows much of the existing logic and tests to be re-used, but it may end up not being the best design.
---
**TODO:**

Implement minimal u8 x i8 -> i32 quantized GEMM support

---

rten-simd/src/arch/aarch64.rs
rten-simd/src/arch/scalar.rs
rten-simd/src/arch/wasm.rs
rten-simd/src/arch/x86_64.rs
rten-simd/src/functional.rs
rten-simd/src/vec.rs
rten-vecmath/src/lib.rs
rten-vecmath/src/min_max.rs
src/gemm.rs
src/ops/quantize.rs

Combine the separate passes over the input to compute the min/max in DynamicQuantizeLinear with a single vectorized pass.
There is a caveat that the new implementation doesn't guarantee the same handling of NANs in the input as before, and this will vary by architecture. The ReduceMin / ReduceMax ops always propagate NANs, whereas this implementation just uses the obvious min/max intrinsic (eg. `_m256_min_ps`) which may do something else.

Compute input min/max with a single vectorized pass in DynamicQuantizeLinear

---

src/ops/quantize.rs

Add a couple of small and easy optimizations to QuantizeLinear. This also benefits DynamicQuantizeLinear.
- Replace division with multiplication by reciprocal
- Remove unnecessary `clamp`-ing as Rust's `as` operator does this for us
This is ~15% faster in a test with ModernBERT. It should be possible to do much better with SIMD, but that will come later.

Add small optimizations for QuantizeLinear

---

src/gemm.rs
src/gemm/kernels/x86_64.rs
src/gemm/packing.rs
src/gemm/packing/int8.rs

Add packing functions for kernels that use int8 x int8 -> i32 dot product instruction sequences, and a kernel for x86_64 that uses them with AVX2 intrinsics.
This doesn't include the GEMV kernel. I will add that separately.
This is the "baseline" kernel for x64 for systems that don't support VNNI ("DL Boost") instructions.
---
Performance numbers on  i5-1038NG7 comparing f32 matmul vs int8, excluding gemv. The int8 matmul is now faster, but other quantization overheads mean that eg. int8 ModernBERT is slightly slower than f32.
```
f32 x f32 -> f32
Testing kernel fma
m 512 n 512 k 512 iters 512. Duration 419.527ms (0.819ms/iter). GFLOPS 327.6
m 1024 n 1024 k 1024 iters 64. Duration 383.096ms (5.986ms/iter). GFLOPS 358.8
m 128 n 2048 k 512 iters 512. Duration 453.880ms (0.886ms/iter). …
```

Implement u8 x i8 -> i32 GEMM kernel for x86_64 using AVX2 intrinsics

---

.github/workflows/ci.yml
Cargo.lock
Cargo.toml
Makefile
rten-simd/src/arch/wasm.rs
src/gemm.rs

When building for WASM with the `relaxed-simd` target feature enabled, use `f32x4_relaxed_madd(a, b, c)` instead of `f32x4_add(f32x4_mul(a, b), c)`.
For softmax for example this makes the vectorized version ~3.1x faster than scalar instead of ~2.3x before, tested under wasmtime. In the process I discovered that the GEMM benchmark was always reporting 0 GFLOPs on 32-bit targets due to an overflow when calculating the total number of flops, so that is fixed as well.

Use fused multiply-add instructions when WASM relaxed-simd feature is enabled

---

rten-simd/src/arch/aarch64.rs
rten-simd/src/arch/scalar.rs
rten-simd/src/arch/wasm.rs
rten-simd/src/arch/x86_64.rs
rten-simd/src/isa_detection.rs
rten-simd/src/vec.rs
src/gemm.rs
src/gemm/kernels/generic.rs
src/gemm/kernels/simd_generic.rs
src/gemm/kernels/x86_64.rs
src/gemm/packing/int8.rs

This converts the recently added int8 GEMM kernel for AVX-2 into a portable SIMD version which takes the dot product function as an argument, then adds an AVX-512 int8 kernel using it. This kernel has two versions, one using the same sequence of 3 instructions for the dot product as the AVX-2 version and another using a single VNNI instruction.

Add AVX-512 int8 GEMM using VNNI

---

rten-simd/src/arch.rs
rten-simd/src/arch/aarch64.rs
rten-simd/src/arch/array.rs
rten-simd/src/arch/scalar.rs
rten-simd/src/arch/wasm.rs
rten-simd/src/arch/x86_64.rs
rten-simd/src/vec.rs
rten-vecmath/src/lib.rs
rten-vecmath/src/quantize.rs
src/ops/quantize.rs

Use SIMD operations for QuantizeLinear in the f32 -> u8 case, which also forms the second stage of DynamicQuantizeLinear. This makes DQL about ~3.5x faster under AVX2.

Vectorize QuantizeLinear, second stage of DynamicQuantizeLinear

---

src/gemm.rs

Make sure the kernel is passed the range of B zero points that correspond to the columns of B in the same call.

Fix wrong B zero points being passed to kernel in int8 gemv

---

Makefile
rten-simd/src/arch/aarch64.rs
rten-simd/src/arch/scalar.rs
rten-simd/src/arch/wasm.rs
rten-simd/src/arch/x86_64.rs
rten-simd/src/vec.rs
src/gemm.rs
src/gemm/kernels/generic.rs
src/gemm/kernels/simd_generic.rs
src/gemm/kernels/x86_64.rs

Add a gemv kernel for u8 x i8 -> i32 vector-matrix products using rten-simd primitives.
**TODO:**

Implement optimized int8 gemv kernel using portable SIMD

---

src/gemm.rs
src/gemm/kernels.rs
src/gemm/kernels/aarch64.rs
src/gemm/kernels/x86_64.rs

USDOT is only available in recent (Arm v8.6+) chips, but it does conveniently allow reusing the same kernel as used for x64 with no changes. With some small additional changes it should be able to work on older CPUs that have SDOT or UDOT instructions that are much more widely available.
I also note that this kernel isn't the best way to use i8mm for matrix multiplication, but again it allows reusing existing code.

Add initial aarch64 int8 kernel using USDOT

---

rten-simd/src/arch/aarch64.rs
rten-simd/src/arch/scalar.rs
rten-simd/src/arch/wasm.rs
rten-simd/src/arch/x86_64.rs
rten-simd/src/vec.rs
src/gemm/kernels.rs
src/gemm/kernels/aarch64.rs
src/gemm/kernels/simd_generic.rs
src/gemm/kernels/x86_64.rs
src/gemm/packing.rs
src/gemm/packing/int8.rs

Convert the Arm int8 kernels to use the more widely supported UDOT instruction
(mandatory from Arm v8.4) instead of USDOT (mandatory from Arm v8.6).
This change requires converting the B input from signed to unsigned while
packing by adding 128, thus preserving the position of each value within the
numeric range. Each column zero point is adjusted accordingly. This is
done with a bit flip trick I found in ORT.
In the process of testing the gemv changes, the `SimdInt::load_interleave_i8` baseline implementation for Arm was replaced with an optimized version.

Convert Arm int8 kernels to use UDOT instead of USDOT

---

src/gemm.rs
src/gemm/kernels/aarch64.rs
src/gemm/packing/int8.rs

This uses a sequence of instructions to emulate UDOT using widening multiplies and pairwise adds.
In the process the helpers for instantiating `GemmExecutor` with different kernels were refactored into a generic trait to make it easier to exercise each of the available kernels for a given set of input and output types.
With the changes on this branch I was able to successfully run the Whisper example on a Raspberry Pi Zero 2 (Quad-core Arm Cortex A53, 512MB RAM) using the base and tiny models, at ~0.9x real time for base and ~2.1x for tiny.

Add int8 fallback kernel for older Arm CPUs that don't support UDOT

---

.github/workflows/ci.yml

I have broken the AVX-512 build accidentally a few times. This should avoid that. We can't run tests with AVX-512 because GitHub Actions runners don't support that yet (https://github.com/actions/runner/issues/1069).

Add build with AVX-512 enabled in CI

---

src/ops/conv.rs
src/ops/conv/depthwise.rs

Following the pattern of `GemmExecutor` and its kernels, create a `DepthwiseConvExecutor` struct which abstracts the details of handling depthwise convolutions for different architectures and data types. The top-level convolution code then only needs a `DepthwiseConvExecutor<X, W, Y>: Default` bound to ensure than an executor is available for the combination of input and output types, instead of needing to have trait bounds that reflect the implementation details.

Refactor depthwise convolution to support arch/data type-specific kernels

---

README.md
docs/performance.md
src/lib.rs

- Change notes about data types to indicate that i8 and u8 tensors are supported
- Add a short note about quantized model support and the `tools/ort-quantize.py` script. A more detailed quantization guide will come later
- Add a note about using the rten CLI to test and benchmark models

Update notes about data type and quantization support in the docs

---

tools/ort-quantize.py

By default `quantize_dynamic` will replace `Conv` with `ConvInteger`.  RTen doesn't support this operator yet and ONNX Runtime doesn't support the operator with the particular combination of data types that `quantize_dynamic` generates (u8 input, i8 weights) (see issues mentioned in comments). Hence omit this from the quantized op types for now.

Exclude `Conv` op from quantization in ort-quantize.py

---

rten-simd/src/arch/aarch64.rs
rten-simd/src/vec.rs

This makes `DynamicQuantizeLinear` about ~34% faster in the Whisper base encoder.
Also add a test for this method for all architectures.

Optimize `SimdInt::saturating_cast_u8` for Arm

---

rten-simd/src/isa_detection.rs
src/threading.rs

On Apple Silicon systems with a mix of performance and efficiency cores,
performance is better if the number of threads is set to the performance core
count, rather than the total number of cores.
Fixes https://github.com/robertknight/rten/issues/342.

Set default number of threads to performance core count on macOS

---

.github/workflows/ci.yml
Makefile

The WASM test targets are also renamed for consistency with `make test`.

Run tests under WASM in CI

---

.github/workflows/ci.yml

The Python code is the same across all platforms so we only need to run linting on one, and it runs a lot faster in the Linux CI. From skimming the build logs [^1] it looks like an `onnx` wheel gets built in the macOS CI whereas Linux CI uses a pre-built wheel.
[^1]: https://github.com/robertknight/rten/actions/runs/12973539398/job/36182308596?pr=554

Skip Python lint on macOS CI

---

Makefile
rten-simd/src/arch/wasm.rs
src/gemm.rs
src/gemm/kernels/wasm.rs
src/threading.rs

This initial implementation performs about the same as f32 or slightly slower.
Faster kernels should be possible via one of:
- Upconverting to i16 during packing and using `i32x4_dot_i16x8`
- Using `i32x4.dot_i8x16_i7x16_add_s` if the `relaxed-simd` target feature is
enabled

Implement baseline int8 kernel for WASM

---

src/gemm.rs
src/gemm/kernels.rs
src/gemm/kernels/x86_64.rs

Range reduction in int8 GEMM tests was done in such a way that it was possible to write kernels which passed the tests but failed in real usage due to encountering saturation issues. Change range reduction in the tests to match how it is done in real models, where it is applied to the RHS inputs (ie. the weights) during quantization, not the LHS. Also only apply range reduction for kernels where we expect this to happen.

Revise range reduction in int8 GEMM tests to match real model inputs

---

rten-simd/src/arch/aarch64.rs
rten-simd/src/arch/scalar.rs
rten-simd/src/arch/wasm.rs
rten-simd/src/arch/x86_64.rs
rten-simd/src/vec.rs
src/gemm/kernels/simd_generic.rs

Previously the non-transposed int8 GEMV kernel iterated over the B matrix in blocks of `I32_VEC_LEN` columns, 4 rows.  At each step it loaded `I32_VEC_LEN` int8 values and sign-extended to i32. These were interleaved to give a 4x4 transposed tile of B and two dot product instructions were used to update `I32_VEC_LEN` dot products and column sums. This version reduces the number of loads from B by loading 4 rows of `I8_VEC_LEN` columns at a time, interleaving to give `I32_VEC_LEN` x 4x4 transposed tiles and using `I32_VEC_LEN * 2` dot product instructions to update `I8_VEC_LEN` dot products and column sums.
On M3 Pro (5 perf cores) this improves GEMV performance for the non-transposed case from 45 GF -> 61 GF. This compares to 90 GF for the case where B is transposed. For wasmtime (single …

Optimize non-transposed int8 GEMV kernel

---

rten-simd/src/arch/aarch64.rs
rten-simd/src/arch/wasm.rs
rten-simd/src/arch/x86_64.rs
rten-simd/src/vec.rs

As noted in various parts of the Rust docs (eg. docs for `__m256i`) the SIMD types have the same layout as `[T; N]` but may have greater alignment. Hence converting from SIMD to array requires just a transmute (but the converse is not true).

Make `Simd::to_array` impls a simple transmute

---

src/gemm.rs
src/gemm/kernels/simd_generic.rs

Fix int8 GEMV for the case where B is transposed and K is not a multiple of 4.
- Perform I8 -> U8 conversion for B in the tail loop
- Use correct fallback if there is no zero point

Fix I8 -> U8 conversion in int8 gemv transposed case

---

rten-tensor/src/layout.rs

Output a more helpful error in debug builds if the dimension index passed to the `size` or `stride` methods is invalid.

Make panic message more helpful if `Tensor::{size, stride}` arg is invalid

---

rten-simd/src/arch/x86_64.rs
rten-simd/src/vec.rs

- Simplify `zip_hi_i8` and `zip_hi_i16` for AVX2. The new code generates the same instructions as before, because LLVM was smart about optimizing the old code, but it is now simpler.
- Split tests for `zip_lo_i8` and `zip_hi_i8` and the same for the i16-variants. This makes debugging easier.
- Simplify and optimize the `zip_*` methods for AVX-512.
As a side note, these changes were made with the help of OpenAI o3-mini-high model. This seems like a notable step up from o1-mini.

Simplify and optimize i8/i16 interleaving SIMD ops for x64

---

rten-tensor/src/lib.rs
rten-tensor/src/tensor.rs

Add type aliases for maybe-owned tensors of dynamic and static rank respectively. Also update the front matter in the rten-tensor crate to mention maybe-owned types.

Add `CowTensor`, `CowNdTensor` type aliases

---

src/gemm.rs
src/gemm/reduced_range_rng.rs

- Export this utility so it can be reused outside GEMM tests
- impl the `RandomSource` trait so it can generate values of both i8 and u8 types
- Add links to relevant documentation on the x86_64 saturation problem

Expand `ReducedRangeRng` and make it reusable outside GEMM tests

---

rten-simd/src/arch/x86_64.rs
rten-vecmath/src/quantize.rs

Fix calls to SIMD intrinsics not being inlined reliably.
Also add `target_feature` to an AVX2 SIMD impl for consistency with other methods.

Add missing `#[inline(always)]` to `Quantize` SIMD op

---

.github/workflows/ci.yml

Installing wasmtime via the curl script failed in
https://github.com/robertknight/rten/actions/runs/13107387960/job/36564377746?pr=572.
To try and make it more reliable, download a tarball of a fixed wasmtime version and extract this manually.

Fix wasmtime install in CI

---

src/ops/matmul.rs

When a batched matmul `[A, M, K] x [K, N]` is converted to a non-batched matmul with LHS shape `[A * M, K]` the zero point needs to be broadcast to match the new row count.
This fixes an error when running the Segment Anything demo with a quantized image encoder.

Broadcast zero point vector when converting batched matmul to non-batched

---

rten-simd/src/vec.rs
src/gemm.rs
src/gemm/im2col.rs
src/gemm/kernels.rs
src/gemm/kernels/aarch64.rs
src/gemm/kernels/generic.rs
src/gemm/kernels/wasm.rs
src/gemm/kernels/x86_64.rs
src/gemm/packing/int8.rs
src/ops/conv.rs
src/ops/conv/im2col.rs

Implement a method similar to `Im2Col::pack_block` that packs the image using the different layout used by int8 kernels.
On non-x64 systems there is an unnecessary u8 -> i8 -> u8 double conversion that happens because the `Conv` operator will receive the image in u8 format, it will create a copy in i8 format and then the kernel will re-convert back to u8 when packing. When a native u8 x u8 -> i32 GEMM is added in future, this can be avoided.
**TODO:**

Implement im2col packing for int8 GEMM

---

rten-convert/rten_convert/converter.py
rten-convert/rten_convert/schema_generated.py
src/gemm/im2col.rs
src/lib.rs
src/model.rs
src/model_builder.rs
src/op_registry.rs
src/ops/conv.rs
src/ops/conv/depthwise.rs
src/ops/matmul.rs
src/ops/mod.rs
src/schema.fbs
src/schema_generated.rs
src/shift_cast.rs
tools/ort-quantize.py

Implement the [ConvInteger](https://onnx.ai/onnx/operators/onnx__ConvInteger.html) operator.
This follows the implementation of `Conv` for f32, with the addition of zero point inputs and the removal of the bias input.
In the process fix handling of padding elements in int8 im2col packing when conversion from i8 -> u8 is enabled.
**TODO:**

Implement `ConvInteger` operator

---

rten-convert/rten_convert/converter.py

VALID is another way of expressing "no padding", so map this to fixed padding of zeros with a size determined by the kernel shape.
Fixes https://github.com/robertknight/rten/issues/382

Support `auto_pad=VALID`

---

src/ops/split.rs

This was prompted by the [SmolVLM](https://huggingface.co/HuggingFaceTB/SmolVLM-500M-Instruct/tree/main/onnx) vision encoder, which applies `Split` to the output indices of a `NonZero` operation.

Support all input tensor types in `Split` operator

---

src/ops/layout.rs

Unlike most operators with an `axis` attribute, the value here can be equal to the tensor rank because it is a count of dimensions. Per spec [^1]:
> Indicate up to which input dimensions (exclusive) should be flattened to
> the outer dimension of the output. The value for axis must be in the range
> [-r, r], where r is the rank of the input tensor.
[^1]: https://onnx.ai/onnx/operators/onnx__Flatten.html#attributes

Support `axis` equal to tensor rank in `Flatten` operator

---

src/gemm/im2col.rs
src/gemm/kernels/aarch64.rs
src/gemm/kernels/simd_generic.rs
src/gemm/kernels/wasm.rs
src/gemm/kernels/x86_64.rs

Refactor int8 GEMM so that NR is not fixed to the i32 vector width (`S::LEN`) but can be a multiple (`NR_REGS`).
To test this, and also because it is improves performance, increase the accumulator tile size from MR=8, NR=4 to MR=8, NR=8 on Arm.
Before (M3 Pro, 5 P core):
```
Testing kernel arm-int8-udot
m 512 n 512 k 512 iters 512. Duration 227.909ms (0.445ms/iter). GFLOPS 603.0
m 1024 n 1024 k 1024 iters 64. Duration 159.544ms (2.493ms/iter). GFLOPS 861.4
m 128 n 2048 k 512 iters 512. Duration 252.584ms (0.493ms/iter). GFLOPS 544.1
m 2048 n 128 k 512 iters 512. Duration 232.714ms (0.455ms/iter). GFLOPS 590.6
m 1 n 4096 k 512 iters 512. Duration 34.840ms (0.068ms/iter). GFLOPS 61.6
m 1 n 4096 k 512 iters 512. Duration 23.628ms (0.046ms/iter). GFLOPS 90.9
```
After:
```
Testing kernel …
```

Support NR being a multiple of vector width in int8 GEMM

---

src/ops/gather.rs
src/ops/identity.rs
src/ops/layout.rs
src/ops/mod.rs
src/ops/pad.rs
src/ops/slice.rs
src/ops/split.rs

Add macros to simplify instantiating and invoking a generic operator function according to the type of an input. This initial version only supports the case where an operator supports all available tensor types.

Use macros to simplify invoking operators with different input types

---

src/model.rs
src/ops/matmul.rs

Generalize the `matmul_integer` implementation and reference implementation in preparation for supporting other int8 type combinations in future.
Also:
- Return a more specific error for combinations that are not currently supported
- Add missing test for MatMulInteger in `test_all_op_types`

Generalize MatMulInteger to support other int8 type combinations in future

---

src/gemm/kernels/aarch64.rs
src/gemm/kernels/wasm.rs

Following https://github.com/robertknight/rten/pull/580, bump up the tile size for the wasm32 and Arm fallback kernels as well.
On the `bench_gemm_mix` benchmark using wasmtime this is a ~20% improvement (37 => 44GF for M=N=K=1024, single thread). For Arm fallback about 6% (65 => 69GF for M=N=K=1024, single thread).

Bump tile size for wasm32 and Arm (non-dot product) int8 kernels

---

src/gemm/kernels/x86_64.rs

Make `NR` 2x the vector width instead of 1x. This follows a similar change in the Arm and wasm32 kernels. The tile sizes for the int8 -> int32 kernels now align with the f32 kernels.
For AVX2 this improves performance for M=N=K=1024 by ~10%. For AVX512 with VNNI the improvement is smaller (4% on a client Ice Lake i5).

Bump up x64 int8 tile size

---

rten-tensor/src/layout.rs
src/gemm.rs
src/ops/matmul.rs

This will make it easier to write tests that cover different data type combinations.
This also fixes a couple of issues I encountered while working on this:
- `GemmExecutor::gemm` would panic if the output row stride was larger than the minimum required (the output column count)
- Make `Tensor::broadcast` errors more helpful if the target shape is incompatible with the source shape

Unify reference implementations of `MatMul` and `MatMulInteger`

---

src/gemm.rs
src/gemm/prepack.rs
src/gemm/tiles.rs

Slim down `gemm.rs` a little by moving some functionality into submodules.

Move GEMM prepacking and output tile management into submodules

---

src/ops/binary_elementwise.rs
src/ops/concat.rs
src/ops/fused.rs
src/ops/generate.rs
src/ops/mod.rs
src/ops/reduce.rs
src/ops/trilu.rs
src/ops/unary_elementwise.rs
src/ops/variadic_elementwise.rs

Add support for specifying a list of supported tensor types in `map_input` and `map_output`, then use this to convert additional operators to use these macros for dispatching to the appropriate implementation.

Refactor more operators to use `map_input`/`map_output`

---

src/ops/reduce.rs

Fix regression introduced in fee3f09372e3d35abd70005c42c66a425c18ac33 where ArgMin dispatched to `arg_max` instead of `arg_min` 😔

Fix ArgMin op

---

src/gemm/packing.rs
src/ops/convert.rs
src/ops/einsum.rs
src/ops/fused.rs
src/ops/generate.rs
src/ops/norm.rs
src/ops/quantize.rs
src/ops/random.rs
src/ops/reduce.rs
src/ops/trilu.rs
src/ops/unary_elementwise.rs

Continue the refactoring started in https://github.com/robertknight/rten/pull/594.

Convert more table-driven tests to use `TestCases` utility

---

rten-imageproc/src/contours.rs
rten-imageproc/src/drawing.rs
rten-imageproc/src/poly_algos.rs
rten-imageproc/src/shapes.rs
src/gemm.rs
src/ops/binary_elementwise.rs
src/ops/conv.rs
src/ops/gather.rs
src/ops/layout.rs
src/ops/matmul.rs
src/ops/pooling.rs
src/ops/resize.rs
src/ops/rnn.rs
src/ops/slice.rs
src/ops/variadic_elementwise.rs

This (almost) finishes the work started in https://github.com/robertknight/rten/pull/594.

Convert more table-driven tests to use `TestCases`

---

rten-tensor/src/assume_init.rs
rten-tensor/src/lib.rs
rten-tensor/src/storage.rs
rten-tensor/src/tensor.rs
src/gemm.rs
src/ops/concat.rs
src/ops/conv/depthwise.rs
src/ops/quantize.rs

Refactor and export the internal `AssumeInit` trait from rten-tensor and use it to replace several `[MaybeUninit<T>] -> [T]` casts downstream in the rten crate. This makes it more obvious what those casts are doing and what the safety requirements are.

Refactor and export `AssumeInit` trait from rten-tensor and use it downstream

---

rten-simd/src/dispatch.rs
rten-simd/src/functional.rs
rten-simd/src/span.rs
rten-vecmath/src/min_max.rs
rten-vecmath/src/normalize.rs
rten-vecmath/src/softmax.rs
rten-vecmath/src/sum.rs

Vectorized operations can operate either in-place on a single mutable slice, or a pair of source and destination slices where the destination is uninitialized. To handle both cases with the same implementation, slice-like types without the aliasing guarantees were used. Replace this with a `SrcDest` type which models the possible cases better in the type system and is a step towards reducing unsafety in vectorized ops.
Part of https://github.com/robertknight/rten/issues/549.

Replace PtrLen/MutPtrLen with SrcDest for vectorized op inputs/outputs

---

rten-simd/src/arch/aarch64.rs
rten-simd/src/arch/array.rs
rten-simd/src/arch/scalar.rs
rten-simd/src/arch/wasm.rs
rten-simd/src/arch/x86_64.rs
rten-simd/src/functional.rs
rten-simd/src/vec.rs
rten-vecmath/src/normalize.rs
rten-vecmath/src/quantize.rs
rten-vecmath/src/softmax.rs
src/gemm/im2col.rs
src/gemm/kernels/aarch64.rs
src/gemm/kernels/generic.rs
src/gemm/kernels/simd_generic.rs
src/gemm/kernels/wasm.rs
src/gemm/kernels/x86_64.rs

Make `Simd::LEN` an `Option<usize>` to represent the possibility that the vector length is unknown at compile time, but a fixed size at runtime, and add a `Simd::len` method which returns either the compile or runtime-constant size.
Runtime-determined SIMD vector types (eg. Arm SVE, RVV) are not currently supported in Rust, but the expectation is that they will be eventually [^1]. This change is made in the hope that it will make it easier to support such types in future.
[^1]: https://github.com/davidtwco/rfcs/blob/sized-hierarchy/text/3729-sized-hierarchy.md

Make SIMD vector length a runtime rather than compile-time constant

---

rten-simd/src/arch.rs
rten-simd/src/arch/aarch64.rs
rten-simd/src/arch/array.rs
rten-simd/src/arch/scalar.rs
rten-simd/src/arch/wasm.rs
rten-simd/src/arch/x86_64.rs
rten-simd/src/functional.rs
rten-simd/src/vec.rs
rten-vecmath/src/erf.rs
rten-vecmath/src/exp.rs
rten-vecmath/src/softmax.rs
rten-vecmath/src/tanh.rs
src/gemm/im2col.rs

`Simd::select` has the same function but the opposite operand order.
The operand order and naming used by `blend` align with the x86-64 intrinsics. The order and naming used by `select` aligns more closely with the Arm, wasm32 and Rust `std::simd` functions, and to me feels more intuitive.

Replace `Simd:blend` with `Simd::select`

---

rten-simd/src/arch.rs
rten-simd/src/arch/aarch64.rs
rten-simd/src/arch/scalar.rs
rten-simd/src/arch/wasm.rs
rten-simd/src/arch/x86_64.rs
rten-simd/src/vec.rs

This operation stopped being used as it isn't performance portable. Currently only the AVX-512 implementation implements it using an intrinsic as opposed to scalar loads.

Remove `SimdFloat::gather_mask` operation

---

rten-examples/src/imagenet.rs

Update URLs to reflect current ONNX Model Zoo repository structure. Also add step-by-step instructions above the `main` function to run the example.

Update model file URLs in ImageNet example

---

rten-simd/src/lib.rs
rten-simd/src/safe.rs
rten-simd/src/safe/arch.rs
rten-simd/src/safe/arch/aarch64.rs
rten-simd/src/safe/arch/generic.rs
rten-simd/src/safe/arch/wasm32.rs
rten-simd/src/safe/arch/x86_64.rs
rten-simd/src/safe/dispatch.rs
rten-simd/src/safe/functional.rs
rten-simd/src/safe/iter.rs
rten-simd/src/safe/vec.rs
rten-vecmath/src/lib.rs
rten-vecmath/src/min_max.rs
rten-vecmath/src/normalize.rs
rten-vecmath/src/sum.rs
rten-vecmath/src/ulp.rs
src/ops/norm.rs
src/ops/quantize.rs
src/ops/reduce.rs

This PR is the first step in addressing https://github.com/robertknight/rten/issues/549, which will significantly reduce the amount of unsafe code overall in rten.
It introduces a new API for the rten-simd portable SIMD library in `rten_simd::safe`, which allows defining SIMD operations using safe code, and ports some of the simpler vectorized operations in rten-vecmath (Sum, SumSquare, SumSquareSub, MinMax, Normalize) to use it.
The basic idea behind the API design is to separate SIMD data types (which can always be constructed) and operations (which require hardware support), and enforce that the types implementing the operations can only be constructed if the ISA is supported. This is similar to [pulp](https://docs.rs/pulp/latest/pulp/), which appears to be a Rust-ified version of …

Introduce safe SIMD API, port some simple vectorized operations to use it

---

Makefile
rten-simd/src/safe/arch/aarch64.rs
rten-simd/src/safe/arch/generic.rs
rten-simd/src/safe/arch/wasm32.rs
rten-simd/src/safe/arch/x86_64.rs
rten-simd/src/safe/dispatch.rs
rten-simd/src/safe/vec.rs
rten-vecmath/src/erf.rs
rten-vecmath/src/exp.rs
rten-vecmath/src/lib.rs
rten-vecmath/src/softmax.rs
rten-vecmath/src/tanh.rs
src/ops/norm.rs
src/ops/unary_elementwise.rs

Convert the exponential (`Exp`) operation implementation to use the new portable SIMD API introduced in https://github.com/robertknight/rten/pull/604, as well as other operations built on top of it (Swish, Silu, Sigmoid, Gelu, Erf, Sigmoid, Tanh, Softmax).
In the process also add a few general SIMD operations (abs, reciprocal, poly_eval, fold_splat) that were missing from the new SIMD API.

Convert Exp and operations using it to safe SIMD

---

rten-simd/src/safe/dispatch.rs
rten-simd/src/safe/vec.rs
rten-vecmath/src/erf.rs
rten-vecmath/src/exp.rs
rten-vecmath/src/tanh.rs

Revise signature of `SimdUnaryOp::eval` so that it specifies the element type in the SIMD vector. Casting between the generic type and the concrete type used by the ISA is still required, but is now safer as the cast prevents accidental changing of the element type.
A bonus is that it now becomes slightly easier to implement an operation for different element types via a macro, as only the element type needs to varied for each impl in many cases.

Use stronger typing for `SimdUnaryOp` argument

---

rten-simd/src/safe.rs
rten-simd/src/safe/arch/aarch64.rs
rten-simd/src/safe/arch/generic.rs
rten-simd/src/safe/arch/wasm32.rs
rten-simd/src/safe/arch/x86_64.rs
rten-simd/src/safe/vec.rs

This works similarly to the `SimdOps` trait and sub-traits, but provides operations on masks. The only initial method is `and`, which is needed for im2col.
This change was extracted from https://github.com/robertknight/rten/pull/607.

Add trait for mask operations in new SIMD API

---

rten-simd/src/safe.rs
rten-simd/src/safe/arch/generic.rs
src/gemm/im2col.rs
src/gemm/kernels/aarch64.rs
src/gemm/kernels/generic.rs
src/gemm/kernels/wasm.rs
src/gemm/kernels/x86_64.rs

Port f32 im2col to use the new SIMD API, reducing the amount of unsafe code. Another change that was required is exporting the individual `Isa` implementations so that the architecture-specific GEMM constructors can use them.

Port f32 im2col to use new SIMD API

---

rten-simd/src/safe/vec.rs
src/gemm/im2col.rs
src/gemm/kernels/aarch64.rs
src/gemm/kernels/wasm.rs
src/gemm/kernels/x86_64.rs

Convert the im2col implementation for int8 GEMM kernels to the new SIMD API. This allows for much more limited use of `unsafe`.
Part of https://github.com/robertknight/rten/issues/549.

Convert int8 im2col to new SIMD API

---

rten-simd/src/safe/iter.rs
rten-simd/src/safe/vec.rs
src/gemm/im2col.rs

Add `SimdOps::{load, load_pad, store}` methods for loading/storing from a slice with length checks, as opposed to the existing unsafe `load_ptr`, `store_ptr` methods.
The safe methods are preferred in contexts where the length check cost is tolerable.

Add safe load/store methods in new SIMD API

---

rten-simd/src/safe/arch/x86_64/avx2.rs
rten-simd/src/safe/arch/x86_64/avx512.rs

These ISAs only have two SIMD types each for float and integer data respectively, but the SIMD abstraction APIs require a different type per SIMD element type. To support the addition of SIMD operations for non-32bit int/float elements, add wrappers.

Add wrapper types for AVX2 and AVX512 SIMD vectors

---

rten-simd/src/safe/arch/aarch64.rs
rten-simd/src/safe/arch/generic.rs
rten-simd/src/safe/arch/wasm32.rs
rten-simd/src/safe/arch/x86_64/avx2.rs
rten-simd/src/safe/arch/x86_64/avx512.rs
rten-simd/src/safe/vec.rs

Reduce the amount of arch-specific code slightly by defining the `le` and `lt` ops, for integer types, in terms of `ge` and `gt`.

Define less-than ops in terms of greater-than ops for int types

---

rten-simd/src/safe/arch/aarch64.rs
rten-simd/src/safe/arch/generic.rs
rten-simd/src/safe/arch/wasm32.rs
rten-simd/src/safe/arch/x86_64/avx2.rs
rten-simd/src/safe/arch/x86_64/avx512.rs
rten-simd/src/safe/vec.rs

The code is mostly copied and adjusted from i16 support, except that some
platforms do not have i8 multiply or shift-left instructions, so an
extend-transform-narrow sequence is used.
The test for the `sum` method overflows under AVX2 and AVX-512 with i8 inputs.
To ensure consistency between platforms, the `sum` method has been redefined to
use wrapping addition.
**TODO:**

Support i8 vectors in new SIMD API

---

rten-simd/src/safe/arch/generic.rs
rten-simd/src/safe/arch/wasm32.rs

This makes method signatures for mask-using/returning methods easier to follow. It will also make it easier to potentially use a smaller uint type as the representation for masks in future.

Use separate types for masks and SIMD vectors in wasm32 and generic ISAs

---

rten-simd/src/safe/arch/aarch64.rs
rten-simd/src/safe/arch/generic.rs
rten-simd/src/safe/arch/wasm32.rs
rten-simd/src/safe/arch/x86_64/avx2.rs
rten-simd/src/safe/arch/x86_64/avx512.rs
rten-simd/src/safe/vec.rs

For x64 there aren't specific intrinsics for operations on u16 values in many cases, but we rely on the fact that the i16 operations work. This is either because the operation only cares about the lane width (splat, select etc.) or that it works the same for signed/unsigned in two's complement (add, sub, low half of multiplication).
**TODO:**

Support u16 vectors in new SIMD API

---

rten-simd/src/safe/arch/aarch64.rs
rten-simd/src/safe/arch/generic.rs
rten-simd/src/safe/arch/wasm32.rs
rten-simd/src/safe/arch/x86_64/avx2.rs
rten-simd/src/safe/arch/x86_64/avx512.rs
rten-simd/src/safe/vec.rs

This completes basic SIMD support for all the types involved in int8 quantization. There is additional work to do to support narrowing vectors and converting between signed and unsigned.

Support u8 vectors in new SIMD API

---

rten-simd/src/safe.rs
rten-simd/src/safe/vec.rs
rten-simd/src/safe/writer.rs

Add additional APIs for loading and storing SIMD vectors. These will be useful in porting the `Quantize` operation to the new SIMD API:
- `SimdOps::load_many` loads N SIMD vectors from `N * v_len` consecutive elements of a slice, with only one bounds check
- `SimdOps::store_uninit` writes a `Simd<Elem=T>` vector to a `MaybeUninit<T>` slice and returns the initializes sub-slice
- `SliceWriter` is a utility for incrementally initializing a slice using vectorized stores

Add APIs for initializing slices with SIMD vector stores

---

rten-simd/src/safe.rs
rten-simd/src/safe/arch/aarch64.rs
rten-simd/src/safe/arch/generic.rs
rten-simd/src/safe/arch/wasm32.rs
rten-simd/src/safe/arch/x86_64/avx2.rs
rten-simd/src/safe/arch/x86_64/avx512.rs
rten-simd/src/safe/vec.rs
rten-vecmath/src/quantize.rs
src/ops/quantize.rs

Add a `NarrowSaturate` trait in the new SIMD API which narrows two input vectors with saturation and concatenates the results to form a full narrowed vector. Implement this for i32 -> i16 and i16 -> u8 narrowing, then use the new operations to port the `Quantize` op to the new SIMD API, with no `unsafe`.
This particular combination of narrowings was used because it maps directly to intrinsics in all platforms, especially AVX2 and wasm32 which have only a limited set of narrowing operations.
The new vectorized `Quantize` op is more efficient than the old one because it generates one u8 SIMD vector from 4x f32 vectors in each iteration, whereas the previous one converted one f32 vector to 1/4 of a u8 vector in each iteration.
There is also a commit that adds tests for `SimdOps::{min, max}` …

Add SIMD ops for i32 -> i16 and i16 -> u8 saturating narrow, port `Quantize` op to new SIMD API

---

rten-simd/src/dispatch.rs
rten-simd/src/functional.rs
rten-simd/src/safe/dispatch.rs
rten-simd/src/safe/functional.rs
rten-simd/src/span.rs
rten-vecmath/src/normalize.rs
rten-vecmath/src/softmax.rs

Use separate lifetimes for the source and destination buffers of vectorized ops, so that the compiler can understand that the source buffer is no borrowed after an operation is dispatched.
This change is an enabler for creating a safe API to update the length of a `Vec` after writing to the uninitialized portion.

Use separate lifetimes for source and destination of vectorized ops

---

rten-simd/src/safe.rs
rten-simd/src/safe/arch/aarch64.rs
rten-simd/src/safe/arch/generic.rs
rten-simd/src/safe/arch/wasm32.rs
rten-simd/src/safe/arch/x86_64/avx2.rs
rten-simd/src/safe/arch/x86_64/avx512.rs
rten-simd/src/safe/dispatch.rs
rten-simd/src/safe/functional.rs
rten-simd/src/safe/iter.rs
rten-simd/src/safe/vec.rs
rten-simd/src/safe/writer.rs
rten-vecmath/src/erf.rs
rten-vecmath/src/exp.rs
rten-vecmath/src/min_max.rs
rten-vecmath/src/normalize.rs
rten-vecmath/src/quantize.rs
rten-vecmath/src/softmax.rs
rten-vecmath/src/sum.rs
rten-vecmath/src/tanh.rs
src/gemm/im2col.rs
src/gemm/kernels/simd_generic.rs

Rename the SIMD operation traits to make the names more distinctive at a glance and avoid them all having the same `Simd*` prefix:
`SimdOps` -> `NumOps`
`SimdFloatOps` -> `FloatOps`
`SimdIntOps` -> `SignedIntOps`

Rename safe SIMD traits

---

rten-vecmath/src/extend_init.rs
rten-vecmath/src/lib.rs
src/ops/norm.rs
src/ops/quantize.rs

The non-in-place vectorized ops in rten-vecmath take uninitialized output slices so that the caller has the freedom choose how/where the buffer is allocated and avoid the overhead of zeroing a slice that the operation is going to initialize anyway. This means that the caller has to use an unsafe `Vec::set_len` call or similar afterwards to update the length of the buffer.
Add an `ExtendInit` trait in rten-vecmath which handles this for the common case of filling a `Vec` with the result of a vectorized operation, and convert a couple of operations in the rten crate to use it.
A limitation of the initial design is that it doesn't support the case where multiple threads are initializing separate chunks of the buffer in parallel. Solving that is left as a future exercise.

Add `ExtendInit` utility for updating length of destination buffers for vectorized ops

---

rten-simd/src/safe.rs
rten-simd/src/safe/arch/aarch64.rs
rten-simd/src/safe/arch/generic.rs
rten-simd/src/safe/arch/wasm32.rs
rten-simd/src/safe/arch/x86_64/avx2.rs
rten-simd/src/safe/arch/x86_64/avx512.rs
rten-simd/src/safe/vec.rs

This will replace uses of `load_extend_i8` in the old API. The new APIs are more efficient as they always expand one whole vec to two (1x 8-bit -> 2x 16-bit -> 4x 32-bit) whereas the previous API expanded 1/4 of an 8-bit vec to 1x 32-bit.

Support i8 -> i16 -> i32 extension in new SIMD API

---

rten-simd/src/safe.rs
rten-simd/src/safe/arch/aarch64.rs
rten-simd/src/safe/arch/generic.rs
rten-simd/src/safe/arch/wasm32.rs
rten-simd/src/safe/arch/x86_64/avx2.rs
rten-simd/src/safe/arch/x86_64/avx512.rs
rten-simd/src/safe/vec.rs

This replaces the `zip_{lo, hi}_{i8, i16}` methods in the old SIMD API.

Implement i8 and i16 interleave in new SIMD API

---

rten-simd/src/safe.rs
rten-simd/src/safe/arch/aarch64.rs
rten-simd/src/safe/arch/generic.rs
rten-simd/src/safe/arch/wasm32.rs
rten-simd/src/safe/arch/x86_64/avx2.rs
rten-simd/src/safe/arch/x86_64/avx512.rs
rten-simd/src/safe/vec.rs

Bitwise XOR is used in int8 GEMM ops, bitwise NOT is useful in tests.
**TODO:**

Implement bitwise NOT and XOR in new SIMD API

---

rten-simd/src/isa_detection.rs
rten-simd/src/safe/dispatch.rs

- AVX-512BW was tested for in `Avx512Isa::new`, but not enabled when dispatching. This resulted in intrinsics using these extensions not being inlined.
- AVX-512DQ is used by `_mm512_xor_ps`, but this feature was not tested for and the target feature wasn't enabled, so this intrinsic did not get inlined.
According to [^1] all CPUs that support the BW extension also support DQ, so this doesn't change which systems can use AVX-512.
[^1]: https://en.wikipedia.org/wiki/Advanced_Vector_Extensions#AVX-512_CPU_compatibility_table

Enable AVX-512BW and AVX-512DQ target features in AVX-512 dispatch

---

rten-simd/src/safe/arch.rs
src/gemm/kernels/aarch64.rs
src/gemm/kernels/generic.rs
src/gemm/kernels/simd_generic.rs
src/gemm/kernels/wasm.rs
src/gemm/kernels/x86_64.rs

Port int8 matrix multiplication and matrix-vector multiplication to the new SIMD API.
The `simd_int8_gemm` and `simd_int8_gemv` functions are still marked as `unsafe` at this stage, but this is a step towards more narrowly scoped use of `unsafe` in future.
**TODO:**

Port int8 GEMM to new SIMD API

---

rten-simd/src/arch/aarch64.rs
rten-simd/src/arch/generic.rs
rten-simd/src/arch/wasm32.rs
rten-simd/src/arch/x86_64/avx2.rs
rten-simd/src/arch/x86_64/avx512.rs
rten-simd/src/functional.rs
rten-simd/src/iter.rs
rten-simd/src/vec.rs
rten-simd/src/writer.rs
src/gemm/kernels/simd_generic.rs

Make the generic argument to `NumOps` independent of the SIMD ISA. For example `<Avx2Isa as Isa>::f32` now returns an `impl NumOps<f32>` instead of `impl NumOps<float32x4_t>`. This in turn will make it possible to add generic methods to get the `NumOps` impl for a given element type, enabling writing `SimdOp`s that are generic over the element type.
The downside is that a single struct can no longer implement `NumOps` for two different SIMD vectors with the same element type. This would prevent eg. `Avx2Isa` from implementing `NumOps` for both 256 and 128-bit f32 vectors. So far the need to half or quarter-width vectors has been avoided by defining operations in a way that avoids this.

Parametrize `NumOps` by element type instead of SIMD type

---

rten-tensor/src/copy.rs
rten-tensor/src/tensor.rs

This is more succinct, self-documenting and avoids a hazard where the lifetime of the slice is incorrectly changed, as opposed to just the initialization status.

Replace `MaybeUninit<T>` slice transmutes with `assume_init`

---

rten-simd/src/dispatch.rs
rten-simd/src/lib.rs
rten-simd/src/vec.rs

Add `Get{Num, Float, SignedInt}Ops` traits to rten-simd which are implemented for supported element types and return the `{Num, Float, SignedInt}Ops` impl for that type from a given SIMD `Isa`. These can be used to create SIMD operations which are generic over the element type.
The `SimdUnaryOp::{map, map_mut}` methods have been modified to use this traits, in order to support all element types.

Add traits to enable writing SIMD operations that are generic over element type

---

rten-simd/src/arch/aarch64.rs
rten-simd/src/arch/generic.rs
rten-simd/src/arch/wasm32.rs
rten-simd/src/arch/x86_64/avx2.rs
rten-simd/src/arch/x86_64/avx512.rs
rten-simd/src/vec.rs

In 001ce9b8aa61adab53967ef4f752b10c9faa2d6f the core SIMD traits (`NumOps` etc.) were changed to be parametrized by the element type rather than SIMD type.
Change the supplementary SIMD operation traits to also be parametrized by the element type, both for consistency and also to enable writing generic operations involving these traits.

Parametrize additional SIMD op traits by element rather than SIMD type

---

src/ops/quantize.rs
src/tensor_pool.rs

The contract of `TensorPool::alloc` is that it allocates a buffer with at least the requested capacity, but it may have more. The `Quantize` op in rten_vecmath requires the source and dest buffers to have the same size. Therefore we need to trim the slice passed to it.

Fix Quantize op failure if output has more capacity than requested

---

src/gemm/kernels.rs
src/gemm/kernels/aarch64.rs
src/gemm/kernels/simd_generic.rs
src/gemm/kernels/wasm.rs
src/gemm/kernels/x86_64.rs

Refactor the int8 GEMM kernels to use a trait to access dot product instructions. This trait is then implemented for witness types which ensure the availability of the instructions used, following the approach of the new SIMD API. This allows the `dot_product` method to be safe.
In the process the safety comments were updated for the SIMD GEMM / GEMV kernels to reflect the new responsibilities for the caller.

Refactor int8 GEMM kernels to use dot product instructions via a trait

---

src/gemm.rs
src/gemm/kernels.rs
src/gemm/kernels/aarch64.rs
src/gemm/kernels/generic.rs
src/gemm/kernels/simd_generic.rs
src/gemm/kernels/wasm.rs
src/gemm/kernels/x86_64.rs

Matrix-vector product kernels may be passed an uninitialized output if the beta/accumulate argument is zero/false, but must be passed initialized output otherwise. Replace the separate arguments for the output slice and beta in GEMV kernels with a single value which captures this relationship.

Represent matrix-vector output initialization status in types

---

src/gemm/kernels/aarch64.rs
src/gemm/kernels/simd_generic.rs
src/gemm/kernels/wasm.rs

Refactor the int8 GEMV implementation so that the entry point `simd_int8_gemv` is a safe function. Requirements are either enforced by the type system (SIMD ISA is supported, output is initialized) or checked as preconditions at the entry point. This entry point then dispatches to the unsafe helpers which handle the various cases, assuming the preconditions have been checked.
The float GEMV implementation has a similar structure, except there the helpers individually check their own preconditions as they are simpler (no quantization parameters) and can thus be safe.
In the process some outdated comments relating to the old SIMD API (references to `S::LEN`) were cleaned up or removed.

Make use of `unsafe` more narrowly scoped in int8 gemv

---

rten-simd/README.md
rten-simd/src/dispatch.rs
rten-simd/src/functional.rs
rten-simd/src/lib.rs

Improve the main documentation page for the rten-simd crate.
- Remove note at the top about the new SIMD API being in-development
- Add section on supported SIMD ISAs
- Add a section on defining generic operations
- Add a section on differences from `std::simd`
- Mention `Simd` and `Elem` traits in trait overview section
- Revise other sections
- Add a basic README for the rten-simd crate

Update main documentation page for rten-simd

---

rten-simd/src/arch.rs
rten-simd/src/arch/aarch64.rs
rten-simd/src/arch/generic.rs
rten-simd/src/arch/wasm32.rs
rten-simd/src/arch/x86_64/avx2.rs
rten-simd/src/arch/x86_64/avx512.rs
rten-simd/src/dispatch.rs
rten-simd/src/elem.rs
rten-simd/src/functional.rs
rten-simd/src/iter.rs
rten-simd/src/lib.rs
rten-simd/src/ops.rs
rten-simd/src/simd.rs
rten-simd/src/writer.rs
rten-vecmath/src/erf.rs
rten-vecmath/src/exp.rs
rten-vecmath/src/min_max.rs
rten-vecmath/src/normalize.rs
rten-vecmath/src/quantize.rs
rten-vecmath/src/softmax.rs
rten-vecmath/src/sum.rs
rten-vecmath/src/tanh.rs
src/gemm/im2col.rs
src/gemm/kernels/simd_generic.rs

- Extract the SIMD vector, mask and element type traits out of `vec.rs` and into separate modules.
- Rename `rten_simd/src/vec.rs` -> `ops.rs` as a more appropriate name for the functionality in the module.
- Un-export operations traits from the root of the `rten_simd` crate and export the whole `ops` module. This reduces the clutter of the crate root and gives imports of ops traits a more meaningful path like `use rten_simd::ops::Extend`.
- Add some module documentation to ops.rs

Re-structure rten-simd to put ops traits in a submodule

---

rten-simd/src/arch/aarch64.rs
rten-simd/src/arch/generic.rs
rten-simd/src/arch/wasm32.rs
rten-simd/src/arch/x86_64/avx2.rs
rten-simd/src/arch/x86_64/avx512.rs
rten-simd/src/ops.rs

The NOR and XOR operations were already implemented. Add AND and OR for completeness.

Add bitwise AND, OR ops for SIMD types

---

rten-simd/src/arch/aarch64.rs
rten-simd/src/arch/generic.rs
rten-simd/src/arch/wasm32.rs
rten-simd/src/arch/x86_64/avx2.rs
rten-simd/src/arch/x86_64/avx512.rs
rten-simd/src/lib.rs
rten-simd/src/ops.rs
rten-vecmath/src/exp.rs

Add a new trait in-between `NumOps` and `SignedIntOps` in the hierarchy which provides operations available on all integer types. Move the `shift_left` method from `SignedIntOps` to `IntOps` and implement `IntOps` for all integer types except u8, as that is more involved for some architectures (ie. x64).

Add `IntOps` trait for operations on SIMD vectors with integer elements

---

rten-convert/rten_convert/schema_generated.py
src/model_builder.rs
src/op_registry.rs
src/ops/resize.rs
src/schema.fbs
src/schema_generated.rs

Support the `pytorch_half_pixel` transform mode in the `Resize` operator. See https://onnx.ai/onnx/operators/onnx__Resize.html#attributes.

Support `pytorch_half_pixel` value for `coordinate_transform_mode`

---

rten-convert/rten_convert/converter.py
rten-convert/rten_convert/schema_generated.py
src/graph.rs
src/model.rs
src/model_builder.rs
src/op_registry.rs
src/ops/layout.rs
src/schema.fbs
src/schema_generated.rs

- Support attributes for `Shape` operator in rten model files. This is optional for backwards compatibility.
- Support `start` and `end` attributes in `Shape` op implementation
**TODO:**

Support `start` and `end` attributes for `Shape` operator

---

rten-convert/rten_convert/converter.py

During model conversion, if an unsupported operator is used by many nodes, only emit one message per operator type. This makes the output less noisy.
- Add `ConversionError` base class for all exceptions during conversion
- Add `UnsupportedOperatorError` subclass for unsupported operator
exceptions and use this to keep a memory of the unique operators for
which a warning has been emitted.

Only emit one error for each unsupported operator encountered

---

tools/export-timm-model.py

Add a `--dynamo` flag to export-timm-model.py to use the newer [TorchDynamo-based](https://pytorch.org/docs/stable/onnx.html#torchdynamo-based-onnx-exporter) ONNX exporter.
This provides a convenient way to test dynamo-exported versions of many popular vision models. See also https://github.com/robertknight/rten/issues/645.

Add option to use dynamo ONNX exporter in export-timm-model.py

---

rten-convert/rten_convert/converter.py
rten-convert/rten_convert/schema_generated.py
src/model.rs
src/model_builder.rs
src/op_registry.rs
src/ops/mod.rs
src/ops/random.rs
src/schema.fbs
src/schema_generated.rs

This operator requires the "random" crate feature to be enabled because it _may_ need to generate random numbers, although in most cases the operator will be a no-op when it appears in exported ONNX models, a vestige of the training process.

Implement Dropout operator

---

tools/export-timm-model.py

The un-optimized exported model contains ONNX functions which are not yet supported in RTen [^1]. Optimizing the model will (usually?) inline these functions, allowing the resulting model to be converted for use with RTen.
[^1]: https://github.com/robertknight/rten/issues/655

Apply model optimization when exporting timm models using TorchDynamo

---

rten-tensor/src/errors.rs
rten-tensor/src/layout.rs
rten-tensor/src/tensor.rs
src/ops/split.rs

The implementation of the `Split` operator was clunky and inefficient as it constructed a dynamically sized set of arguments for `TensorBase::slice`. Internally rten-tensor had a more ergonomic and efficient API for slicing a tensor along an axis. Expose and add tests for this API, and use it in the `Split` operator implementation.
This change will also make it easier to add support for the `num_outputs` attribute in the Split operator.

Improve `Split` operator implementation, add `TensorBase::{slice_axis, slice_axis_mut}`

---

rten-convert/rten_convert/converter.py
rten-convert/rten_convert/schema_generated.py
src/model.rs
src/model_builder.rs
src/op_registry.rs
src/ops/rnn.rs
src/ops/split.rs
src/schema.fbs
src/schema_generated.rs

This was encountered when testing a ViT model exported via:
```
python tools/export-timm-model.py --dynamo timm/vit_base_patch16_224.augreg2_in21k_ft_in1k
```
The [spec](https://onnx.ai/onnx/operators/onnx__Split.html#attributes) does not say how to handle the case where `num_outputs` is zero or exceeds the dimension size. For those cases I have opted to return an error.

Support `num_outputs` attribute in Split operator

---

src/ops/reduce.rs

Fix a bounds check error when slicing `tmp_buf` if multiple axes are reduced _and_ the reduced slices are non-contiguous. In this case the code expected capacity to have been reserved in `tmp_buf` but it was actually empty. Change how the buffer is allocated to ensure it is always allocated when needed.

Fix error when reducing multiple axes if reduced chunks are non-contiguous

---

src/ops/norm.rs

Since the tensor is contiguous and we only need the data for each chunk, we can replace N * C `slice_mut` calls with a much cheaper `chunks_mut` iterator.
This made BatchNormalization ~10% faster on a MobileNet v4 model where there are layers with many channels but a relatively small number of elements per channel.

Optimize BatchNormalization by avoiding tensor slicing

---

src/ops/norm.rs

Per the [spec](https://onnx.ai/onnx/operators/onnx__BatchNormalization.html), BatchNormalization should accept inputs of rank 1 and up. https://huggingface.co/timm/levit_128s.fb_dist_in1k for example applies batch norm to 2D inputs.
Normalization of 1D and 2D inputs is currently very inefficient due to the overhead of applying slice-oriented kernels to single-element slices, but at least it works now.

Accept 1D and 2D inputs in BatchNormalization

---

src/ops/unary_elementwise.rs

Refactor a small amount of duplication found while pondering how best to unify the different ways that unary ops are implemented.

Refactor some duplication in unary ops

---

src/ops/pooling.rs

Optimize MaxPool and AveragePool ops by splitting the inner loop into two parts depending on whether the current output position is affected by padding. This removes branches from the parts that are not affected by padding.
In ocrs's text detection model this makes MaxPool ops 35-40% faster.

Split pooling inner loops into pad and non-pad regions

---

src/gemm/kernels/aarch64.rs

Change f32 GEMM tile size on Arm from 8x8 to 4x16. Practical tests on a handful of devices (Apple M3, Raspberry Pi 5) found this to be faster and llvm-mca analysis of the main loop reported that this computes the same number of output elements in fewer cycles (tested across a range of `--mcpu` values)
The speedup varies by CPU. On an M3 this makes f32 MatMul ops about 8% faster.

Change Arm GEMM tile size to MR=4, NR=16

---

rten-examples/src/whisper.rs
rten-generate/src/sampler.rs

This is a collection of optimizations to spectrogram generation and logit processing in the Whisper example. See commits for details. Together these make transcription of a 2min audio clip using an int8-quantized base model ~8% faster on my system.

Optimize spectrogram generation and logit filtering/sampling in Whisper example

---

rten-convert/rten_convert/converter.py
rten-examples/src/whisper.rs
src/model.rs
src/model_builder.rs
src/op_registry.rs
src/ops/pooling.rs

Change AveragePool and MaxPool to support 3D inputs that have one spatial dim instead of two. Similar to the Conv operator, this is handled by inserting an extra spatial dim, invoking the 2D implementation and then removing the extra
spatial dim from the result.
Tested with https://huggingface.co/onnx-community/snac_24khz-ONNX.

Support 3D inputs in AveragePool and MaxPool

---

src/gemm/kernels/aarch64.rs

On macOS using `udot` in inline assembly works when the calling function doesn't have the `dotprod` target feature enabled. In a Linux arm64 build this is not the case, resulting in an error:
```
error: instruction requires: dotprod
--> src/gemm/kernels/aarch64.rs:462:18
|
462 |                 "udot {result:v}.4s, {a:v}.16b, {b:v}.16b",
|                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
|
```
Fix the problem by surrounding the instruction in a function with `target_feature` enabled, making sure that function is inlined into the surrounding GEMM kernel.
This fix was tested manually locally in Docker. https://github.com/robertknight/rten/pull/669 will add an Arm CI build.

Fix "instruction requires: dotprod" error in Arm Linux build

---

.github/workflows/ci.yml

Test Arm build under Linux in CI. See
https://github.blog/changelog/2025-01-16-linux-arm64-hosted-runners-now-available-for-free-in-public-repositories-public-preview/.
This would have caught the issue fixed in https://github.com/robertknight/rten/pull/670.

Add Arm Linux CI build

---

rten-simd/src/iter.rs
rten-vecmath/src/softmax.rs
rten-vecmath/src/sum.rs

Reduction operations in the Softmax (`max(x)`) and LayerNormalization (`sum(x)`, `sum((x-mean)^2)`) operations were vectorized but bottlenecked on data dependencies between iterations. Add a `fold_unroll` API to rten-simd for explicitly unrolled reductions and use this to improve ILP.
On an M3 this is a ~13% improvement for Softmax and ~40% improvement for LayerNormalization.

Improve instruction level parallelism in LayerNormalization, Softmax operations

---

rten-convert/rten_convert/converter.py

Deserialization of CastLike operators failed because the `ReadOp` implementation expected these operators to have attributes, but the converter was not adding them.
I think there was a mistake in 61ea8b1472597b578afc0f124ef7e8bfa52b59ab where changes to `converter.py` were not committed.
The fix here is to ensure the attributes are added by the converter. However for this operator and others where there are no _required_ attributes, the issue could also be handled by substituting a default value of the attributes struct during deserialization.

Fix deserialization of CastLike operators

---

src/model.rs
src/op_registry.rs

Add more details to the errors produced if deserializing an operator's attributes fails. In particular distinguish between a missing `attrs` field (or incorrect type of `attrs` field) versus an error deserializing a specific attribute.

Add more detail to operator attribute errors

---

rten-simd/src/iter.rs
rten-vecmath/src/min_max.rs

Apply a similar optimization to e60397a5506421166e17c175b9ed01f5fe936420 for the input min/max reductions in the DynamicQuantizeLinear operator. This improves performance by increasing ILP.
Tested using the int8-quantized Whisper medium encoder on an M3, this reduced time in DynamicQuantizeLinear from ~55ms to ~36ms per call (-35%).

Optimize min/max reductions in DynamicQuantizeLinear

---

Cargo.toml
rten-examples/Cargo.toml
rten-simd/src/arch/aarch64.rs
rten-simd/src/arch/x86_64/avx512.rs
rten-simd/src/ops.rs
rten-tensor/Cargo.toml
rten-text/Cargo.toml
src/gemm/im2col.rs
src/gemm/kernels/aarch64.rs
src/gemm/kernels/simd_generic.rs

Arm supports an FMLA instruction variant [^1] which multiples one _lane_ of a
vector by values in another vector and then accumulates into a destination.
This enables reducing the number of loads from A in each iteration of the GEMM
microkernel by a factor of 4. Instead of broadcasting one scalar value from A at
a time into a register used as an FMA operand, we can load a vector of 4
elements from A and then each FMA specifies which of the 4 elements to use.
The way this is implemented is by using `broadcast_lane` + `mul_add` generic
operations (`vdupq_laneq_f32` followed by `fmla`) which LLVM will fuse into a
single `fmla`.
[^1]: https://developer.arm.com/documentation/ddi0596/2021-03/SIMD-FP-Instructions/FMLA--by-element---Floating-point-fused-Multiply-Add-to-accumulator--by-element--?la …

Optimize Arm f32 GEMM using FMLA (by element)

---

src/gemm/kernels.rs
src/gemm/kernels/aarch64.rs
src/gemm/kernels/simd_generic.rs
src/gemm/kernels/wasm.rs
src/gemm/kernels/x86_64.rs

Similar to https://github.com/robertknight/rten/pull/679, use the by-element variant of UDOT [^1] to reduce the number of loads in the int8 GEMM microkernel. Instead of performing 4 scalar 32-bit loads and broadcasting these, perform one 128-bit load and use indexed UDOT to implicitly broadcast a 32-bit block, containing 4 8-bit elements, for each of the 4 rows.
[^1]: https://developer.arm.com/documentation/100069/0609/A64-SIMD-Vector-Instructions/UDOT--vector--by-element-

Optimize Arm int8 GEMM using UDOT-by-element

---

rten-vecmath/src/exp.rs
rten-vecmath/src/softmax.rs

The middle step of the softmax operation computes `exp(x - max(x))`.  Since we know the exp argument is <= 0, and this operation can tolerate a higher lower cutoff, we can use a simplified version of `Exp` with a reduced range which is
more efficient.
ONNX Runtime has a [similar optimization](https://github.com/microsoft/onnxruntime/blob/25c43c1fd66de00d3e7ebe58ecd4b37e060e5be5/onnxruntime/core/mlas/lib/compute.cpp#L312), as does [XNNPack](https://github.com/google/XNNPACK/blob/7cbb479fd61f01bc56045ac3a449274c78a68409/src/f32-raddstoreexpminusmax/avx2-rr2-p5.c.in#L18).
Tested on M3 Pro, this is approximately 20% faster.
```
cargo test -p rten-vecmath -r -- --ignored --nocapture bench_softmax
reference 193835 us vectorized 51013 us. reference / vectorized ratio 3.800
reference 194822 us …
```

Use simplified `Exp` with reduced domain in Softmax op

---

rten-simd/src/functional.rs
rten-vecmath/src/softmax.rs

Explicitly unroll the final loop in the Softmax kernel that divides elements by the sum of expontentials. This is another small (~3%) win on top of the changes in https://github.com/robertknight/rten/pull/682.

Unroll final scaling pass in Softmax kernel

---

src/ops/slice.rs

ONNX models use `i64::{MIN, MAX}` (`i32::{MIN, MAX}` in .rten files) in the `starts` and `ends` attributes of the Slice operator to represent ranges that extend all the way to the start or end of a range. This works as the `Slice` op clamps its ranges.
In rten_tensor, `TensorBase::slice_copy_in` has a fast path using `try_slice` which is supposed to be used for all ranges except those with negative steps. However `try_slice` also fails if the input range extends beyond the end of the axis. The non-fast path clamps its input range in `copy_range_into_slice` as a side-effect of calling `SliceRange::index_range`, so it works correctly.
As a result, some `Slice` operations with one-sided ranges represented this way, which could have used the fast path, ended up falling back to the regular …

Clamp ranges in Slice operator to enable slicing fast path

---

src/graph.rs
src/graph/planner.rs

Generate a better error when a call to `Model::run` fails because there isn't an operator in the graph which computes a requested output.
The issue was found testing `decoder_model.onnx` from https://huggingface.co/onnx-community/parakeet-tdt-0.6b-v2-ONNX/tree/main/onnx (commit [8802298](https://huggingface.co/onnx-community/parakeet-tdt-0.6b-v2-ONNX/commit/880229804d73bb700be355a7e4f7b294a4df3d2b)).
Before: "Missing output 21"
After: "Source node not found for output "prednet_lengths""

Generate better error if output cannot be computed

---

src/graph.rs
src/graph/planner.rs

Follow-up 9b2ac6225e93e1ad774e99f89405da55a44c4653 by adding node names to other planning errors. The capitalization styles have also been aligned across all the errors.

Add node names to more planning errors

---

src/graph.rs
src/ops/binary_elementwise.rs
src/ops/concat.rs
src/ops/control_flow.rs
src/ops/conv.rs
src/ops/convert.rs
src/ops/einsum.rs
src/ops/fused.rs
src/ops/gather.rs
src/ops/generate.rs
src/ops/identity.rs
src/ops/layout.rs
src/ops/matmul.rs
src/ops/mod.rs
src/ops/non_max_suppression.rs
src/ops/norm.rs
src/ops/pad.rs
src/ops/pooling.rs
src/ops/quantize.rs
src/ops/random.rs
src/ops/reduce.rs
src/ops/resize.rs
src/ops/rnn.rs
src/ops/slice.rs
src/ops/split.rs
src/ops/trilu.rs
src/ops/unary_elementwise.rs
src/ops/variadic_elementwise.rs

Replace the `(&TensorPool, InputList)` arguments to `Operator::run` with a single `&OpRunContext` argument. This allows for passing additional information to operator executions without needing to change the signature of `run` each time. This _may_ be useful in solving https://github.com/robertknight/rten/issues/689, although that issue notes some other ways the issue could be resolved.
This makes invoking `run` directly a little more complex. To avoid repeated boilerplate for calling operators in tests, add a new `OperatorExt` trait that provides some convenience methods to simplify this. These method  replace some existing utility functions that existed for the same purpose.

Replace `Operator::run` arguments with a single "context" argument

---

src/graph.rs
src/ops/mod.rs
src/ops/split.rs

Support `Split` operators that don't specify the expected number of outputs via the `num_outputs` attribute or `split` input.
- Add `OpRunContext::num_outputs` method which returns the number of output value nodes an operator has in the graph
- Use `OpRunContext::num_outputs` to get the number of outputs in the `Split` operator if the operator doesn't receive a `split` input or `num_outputs` attribute.
Fixes https://github.com/robertknight/rten/issues/689.

Support `Split` operators that don't specify expected number of outputs

---

rten-tensor/src/copy.rs

This trivial method was showing up in `copy_into_slice` calls (during eg. Transpose operations).

Inline `RangeChunksExact::remainder`

---

rten-tensor/src/layout.rs
rten-tensor/src/overlap.rs
src/ops/pad.rs

Address `clippy::manual_contains` lint warning after updating to Rust v1.87.

Use slice `contains` instead of `iter().any(...)`

---

src/graph/node.rs
src/optimize.rs

Lift the restriction that fused operators can only have a single output. This restriction might have simplified the code at an earlier point in time, but that is no longer the case. None of the current fused operators actually have multiple outputs, so this doesn't change what the optimizer does.

Support fusing subgraphs with multiple outputs

---

src/ops/mod.rs
src/ops/transform_inputs.rs
src/optimize.rs

Rework transpose fusion to support:
- Fusing subgraphs where multiple inputs to the same operator are transposed
- Transposing all supported input types
The new structure replaces the `FusedTranspose` operator with a `TransformInputs` operator which contains a list of `(input_index, transform)` tuples of transformations to apply to inputs. This structure should also make it easier to fuse other layout transformations (slicing, broadcasting etc.) in future. When matching Transpose operations, instead of finding a Transpose operator and then looking for its target, instead start with the potential target and look for all source nodes that are transposed.

Make transpose fusion more flexible

---

rten-examples/src/nougat.rs
rten-generate/src/metrics.rs

Add a convenient API for getting the total number of tokens generated by an `rten_generate::Generator`, plus an example usage on the Nougat OCR example.

Add `Metrics::token_count` API

---

src/ops/binary_elementwise.rs

If a binary operator's `run_in_place` method cannot run in place, make sure the input buffer is returned to the pool for re-use rather than freed by the OS.

Return input buffer to pool if binary op cannot run in-place

---

rten-tensor/src/test_util.rs
src/ops/binary_elementwise.rs
src/ops/mod.rs
src/ops/norm.rs
src/ops/rnn.rs
src/ops/slice.rs
src/ops/unary_elementwise.rs

As part of addressing https://github.com/robertknight/rten/issues/192, remove
the `*_in_place` variants for unary operators and instead test in-place
operations by calling the `Operator::run_in_place` implementation directly. This
will make it easier to change the behavior of `run_in_place` to fall back to a
non-in-place operation if the input is not contiguous.
The `*_in_place` functions for operators in other modules have also been
un-exported from the `ops` module, to allow for similar changes in future. This
is a breaking change since the `ops` module is public, but there are probably
very few if any downstream consumers of these.

Remove `x_in_place` functions for most unary operators

---

src/graph.rs
src/graph/noop_hash.rs

This will make it possible for the optimizer to remove unused nodes from the graph after fusion, or build a new graph with some node IDs omitted.
Using `FxHashMap<NodeId, Node>` resulted in a ~2% slowdown in the GPT2 example (base model) with more self time spent in `Graph::run_plan`. To mitigate that, use a custom hasher that uses the u32 node IDs directly as hash values.

Use a hash map instead of a vec to store graph nodes

---

src/graph.rs
src/graph/builder.rs
src/graph/node.rs
src/graph/planner.rs
src/optimize.rs

Don't fuse operations if intermediate values generated by sub-steps of the
un-fused operation are consumed by other operators in the graph or are used as
graph outputs. Previously such a situation could lead to both the fused and
un-fused versions of the operator being run, which could end up being slower
than just running the un-fused version.
Fixes https://github.com/robertknight/rten/issues/708
---
**TODO:**

Don't fuse subgraphs if intermediate values are used outside the subgraph

---

rten-cli/src/main.rs
src/graph.rs
src/threading.rs

Add an API (`RunOptions::thread_pool`) and CLI options (`-t, --num-threads`) to set the number of threads used by inference. The `RunOptions::thread_pool` field is an `Arc` to avoid needing to add a lifetime to `RunOptions` everywhere.
This is a breaking change for the CLI as several existing options have been renamed in order to give `--num-threads` a shorthand that matches `ort-infer.py`. See last commit.

Add API and CLI option to set number of threads

---

rten-convert/rten_convert/converter.py
rten-convert/rten_convert/schema_generated.py
rten-vecmath/src/erf.rs
rten-vecmath/src/lib.rs
rten-vecmath/src/tanh.rs
src/model.rs
src/model_builder.rs
src/op_registry.rs
src/ops/unary_elementwise.rs
src/optimize.rs
src/schema.fbs
src/schema_generated.rs

Support the tanh-based approximation of Gelu used when the `approximate="tanh"` for the ONNX `Gelu` operator, and add a fusion that matches the corresponding pattern.
The fusion was tested with the encoder model from https://huggingface.co/onnx-community/byt5-small-ONNX.
Approximate gelu is vectorized and parallelized the same as regular `Gelu`.

Support approximate Gelu

---

src/graph.rs
src/ops/binary_elementwise.rs
src/ops/concat.rs
src/ops/convert.rs
src/ops/identity.rs
src/ops/layout.rs
src/ops/mod.rs
src/ops/norm.rs
src/ops/resize.rs
src/ops/slice.rs
src/ops/unary_elementwise.rs

Update the `run_in_place` API to align with recent changes to `Operator::run` by taking an `&OpRunContext` rather than separate arguments for the pool and inputs. When additional services or information is exposed to operators via `OpRunContext` in future, this will make it possible to use that in in-place execution.

Make `Operator::run_in_place` take an `OpRunContext`

---

src/graph.rs
src/model.rs
src/ops/control_flow.rs
src/ops/mod.rs

Add input metadata (dtype, shapes) to execution errors for in-place operations. Since the main input is passed by value to `Operator::run_in_place` and thus not available afterwards, its shape and dtype has to be captured before the operator runs.
Example error when an operator receives an unsupported combination of input types:
Before:
```
Error: OperatorError { name: "/Pow", error: IncorrectInputType }
```
After:
```
Error: OperatorError { name: "/Pow", error: IncorrectInputType, inputs: [Some(InputMeta { dtype: Int32, shape: [] }), Some(InputMeta { dtype: Float, shape: [] })] }
```

Include input metadata in op errors for in-place operations

---

rten-convert/rten_convert/converter.py

When i64 values are truncated to i32 during model conversion, silence the warning if the i64 values are `i64::{MIN, MAX}` as these are commonly used to represent infinity when slicing to the end of a dimension with unknown size.

Remove warning when clamping `i64::{MIN, MAX}` to `i32::{MIN, MAX}`

---

.github/workflows/ci.yml

This might help with a recent CI failure on main: https://github.com/robertknight/rten/actions/runs/15250154351/job/42884956471
Edit: Nope, the failure was probably due to ongoing issues with GitHub Actions.

Upgrade to actions/checkout@v4

---

src/graph.rs
src/ops/mod.rs

When an operator is run in-place input indices passed to `InputList` methods are offset by one because the first input is passed separately.  Account for this when generating errors so that error messages reflect the real index of the input rather than the one passed to eg. `InputList::require`, which will be one lower.

Account for first input being omitted in `InputList` methods

---

src/ops/layout.rs

Make sure the input buffer is returned to the pool if not re-used in `<Expand as Operator>::run_in_place`. This avoids the overhead of freeing it (and subsequent re-allocation from the OS).

Return input to pool in `Expand` if not run in place

---

src/graph.rs
src/ops/mod.rs

- Add commas between input shapes
- Change formatting of the dtype/shape for an individual tensor to be less noisy
- Use parens for input list to be easier to distinguish from square brackets used for shapes
With the new format an error looks like:
```
Model run failed: operator "/deberta/encoder/layer.0/attention/self/Not" failed: expected tensor with type bool but has type i32. Inputs were (i32 [1, 1, 64, 64])
```

Refine formatting of tensor types and shapes in errors

---

src/ops/concat.rs

via OpenAI Codex (first commit) and Claude Code (second commit). Both worked, but Claude Code has been the more polished experience.

Refactor some more tests to be table driven

---

rten-tensor/src/tensor.rs
src/gemm.rs
src/gemm/errors.rs
src/ops/conv.rs
src/ops/matmul.rs
src/ops/rnn.rs

Refactor the GEMM APIs that accept uninitialized output buffers to fix safety hazards and make it possible to use the result without an unsafe uninitialized -> initialized cast:
- Require that the output buffer is exactly the right length, rather than just large enough. This avoids the need to deal with partially-initialized outputs.
- Make `GemmExecutor::gemm_uninit` return the initialized output. This can be combined with `ExtendInit` to safely update the length of a `Vec` after initialization.
- Fix a safety hazard where `gemm_uninit` would check for an output that "should" be empty and return early, before verifying that the actual length of the output buffer was zero. This could lead to callers incorrectly marking an uninit buffer as initialized.

Refactor internal GEMM APIs that accept uninitialized output buffers

---

src/gemm.rs
src/gemm/errors.rs
src/ops/matmul.rs

Add an API for batched matmuls to `GemmExecutor`. This will allow parallelism across batch, column and row dimensions of the output to be handled holistically in one place.
Part of https://github.com/robertknight/rten/issues/707.

Add internal batched GEMM API

---

docs/performance.md
rten-simd/src/lib.rs
src/lib.rs

AVX-512 is stable in nightly Rust, currently expected to land in Rust v1.89.

Remove `stdarch_x86_avx512` feature opt-in

---

rten-tensor/src/iterators.rs
rten-tensor/src/tensor.rs

Re-implement inner dimension iterators to be more efficient and use the same code to handle both static and dynamic-rank inner views. The new version uses the `Offsets` iterator to iterate over the start offset for each inner view. This is more efficient than iterating over outer indices and slicing the tensor at each step. This is beneficial mainly when the ratio of outer dimension steps is high relative to the number of inner dimension steps.

Optimize and refactor inner dimension iterators

---

src/lib.rs
src/ops/mod.rs

This makes migration to the newest release easier and also allows downstream projects to be compatible with a wider range of RTen versions.

Add type aliases with old names for value types

---

rten-tensor/src/iterators.rs
rten-tensor/src/layout.rs
rten-tensor/src/tensor.rs
src/ops/attention.rs
src/ops/mod.rs
src/ops/unary_elementwise.rs
src/optimize.rs

This sequence is common in attention operations, and we can get better cache efficiency by performing Add + Softmax in a lanewise fashion.

Implement Add -> Softmax fusion

---

rten-vecmath/src/erf.rs

This is a small clarity and performance improvement for Erf and derived ops (Gelu). On an M3 it makes Gelu about 6% faster.

Use native instruction for computing `abs(x)` in Erf op

---

rten-tensor/src/iterators.rs
rten-tensor/src/iterators/parallel.rs
rten-tensor/src/storage.rs
rten-tensor/src/tensor.rs
src/ops/attention.rs

Fix a regression from fusing Add + Softmax when the mask tensor is non-contiguous. This happens in [SmolLM](https://huggingface.co/onnx-community/SmolLM-135M-ONNX/tree/main) because the mask tensor is the output of a `Slice` operation. The changes in AddSoftmax are:
- Fix another mistake where a tensor was not released back to the pool
- Avoid requiring the mask tensor to be contiguous over the softmax-d lane. In order to avoid regressing performance for the common case where the mask tensor _is_ contiguous, it was necessary to make some changes to the `Lane` iterator implementation.
Another possible approach would be to pack non-contiguous lanes into a contiguous buffer before adding them.

Handle non-contiguous mask tensor efficiently in AddSoftmax

---

rten-tensor/src/layout.rs
rten-tensor/src/tensor.rs
src/ops/einsum.rs

The `NdLayout` and `DynLayout` types had many inherent methods that duplicated trait methods, from the `Layout`, `MutLayout` or other layout traits. This dates back to early versions of the library where static and dynamic rank tensors were unrelated types.
Remove these inherent methods in favor of the trait methods. In cases where the trait methods forwarded to the inherent methods, the bodies have been moved to the trait impls.
While doing this I found that `DynLayout` had some outdated documentation around strides and internal overlap. This has been moved to the `MutLayout` trait since it pertains to the `MutLayout::from_shape_and_strides` method.

Remove inherent methods on layouts that duplicate trait methods

---

Cargo.toml
rten-bench/Cargo.toml
rten-cli/Cargo.toml
rten-examples/Cargo.toml
rten-generate/Cargo.toml
rten-imageio/Cargo.toml
rten-imageproc/Cargo.toml
rten-tensor/Cargo.toml
rten-testing/Cargo.toml
rten-text/Cargo.toml

Disable stylistic lint enabled by default in Rust v1.88. I don't feel like changing the style of the existing code right now.

Disable uninlined_format_args lint

---

src/ops/conv.rs
src/ops/conv/depthwise.rs

The first commit fixes a panic in the quantized version of the Piper models due to a bug in slicing of the kernel zero point. The second commit reduces the parallelism grain size for depthwise convolution to a single channel. This made testing of the previous fix easier and was also slightly faster in some tests.

Fix panic in quantized depthwise convolution, optimize slightly

---

src/number.rs
src/ops/conv.rs

- Parallelize col2im over output channel
- Replace unpredictable branches in inner loops with adjusted loop bounds.
Reduces time in ConvTranspose ops from ~10ms to ~6ms in Ocrs's text detection model on M3 Pro.

Optimize col2im step in ConvTranspose

---

src/graph.rs

Following ae5d7c814105725497bd333079dc6d42e67a527f, which combined profiling from the main graph and subgraphs into one output, time spent in operators inside subgraphs was double counted: once for the op itself, once as part of the "parent" control flow op. Fix this by skipping timing records for the parent op.

Skip collecting timing records for control flops

---

src/graph.rs
src/graph/capture_env.rs
src/graph/planner.rs
src/ops/conv.rs
src/optimize.rs

When generating the reverse-order execution plan in `GraphOptimizer::apply_fusions`, assume that values captured from parent graphs will be available.
This fixes an issue in the Whisper example where Transpose -> MatMul fusion was not applied for cross-attention
(/model/decoder/layers.0/encoder_attn/Transpose_1), resulting in most of the decoder execution time being spent in that transpose. This is because the transpose input comes from a captured KV-cache input.
The implementation changes the defaults for `PlanOptions` to assume captures are available, as that is true during "normal" execution and only false when running constant propagation, and changes `Graph::execution_plan` to take a `PlanOptions` which is set to the default in `GraphOptimizer::apply_fusions`.

Fix execution planning for subgraphs in optimizer

---

rten-examples/src/whisper.rs
rten-generate/src/generator.rs

By default the KV-cache starts off with an initial capacity of 1 and is doubled in size as needed during inference. For cases where the maximum number of tokens to be generated is known in advance, and that value is not too large, space can be pre-allocated. This avoids the overhead of periodically re-allocating the buffers.

Add option to pre-allocate KV-cache capacity in rten-generate

---

src/ops/transform_inputs.rs

Efficient KV-cache extension in rten-generate relies on the `Concat` operations which extend KV-cache inputs running in-place. This broke in the Whisper example after enabling Transpose -> Concat fusion because the KV-cache concat ops were fused and did not support running in-place afterwards. As a result a new KV-cache buffer was getting allocated for each run.
The fix is to support running `TransformInputs` ops in place, as long as the transforms don't apply to the first/in-place input.

Enable fused Transpose -> Concat operations to run in place

---

src/gemm/prepack.rs
src/ops/slice.rs
src/tensor_pool.rs
src/value.rs

If the `Slice` op can't run in place, return the unused input buffer to the pool.
In the process the `ExtractBuffer` trait was revised so it can be implemented for types where the element type is dynamic.

Return unused input buffer to pool in `Slice` in-place fallback

---

src/graph/builder.rs
src/optimize.rs
src/optimize/fusions.rs
src/value.rs

Add a fusion (or rather, a canonicalization) that converts `ReduceMean(X, axes)` to `ReduceMean<axes>(X)` where `axes` is a constant vector.
Part of https://github.com/robertknight/rten/issues/788.

Add a fusion that converts ReduceMean axes inputs to attributes

---

src/graph/builder.rs
src/ops/matmul.rs
src/ops/mod.rs
src/optimize.rs
src/optimize/fusions.rs
src/slice_cast.rs

Add a fusion for the `Mul(Cast<to=float>(MatMulInteger(a, b)), scale)` graphs produced by dynamic quantization.
For typical transformer models this is a small win for the decoder, where the matmul outputs are vectors, and a larger win for encoders where they are larger matrices.
The fused op currently has two stages: MatMulInteger + fused cast-and-scale. These could just as well be two separate operators. Further improvements are possible in future by pushing the cast down into the matmul kernel. Related to this, quantized ConvInteger would also benefit from a fused cast + scale.
**TODO:**

Add fusion for MatMulInteger + Cast + Mul

---

src/graph.rs
src/graph/node.rs
src/optimize.rs

Move the hash map used for looking up consumers of a value or constant ID from `GraphMutator` down into `Graph`. The immediate motivation for this is to enable fusion visitors to make decisions based on the consumers of an operator. They currently receive a `Graph` rather than a `GraphMutator`. We could pass them an `&GraphMutator` instead, but input ID -> operator ID lookup seems generally useful enough to make it part of the `Graph` struct.
A downside to this change is that it means this hash map is retained after graph optimization is performed, but isn't currently used afterwards.

Move input ID -> operator ID map to `Graph`

---

src/graph/node.rs
src/optimize.rs
src/optimize/fusions.rs

Add a fusion that converts `Slice(Shape(X))` to a constant if the dimensions of X extracted by the `Slice` are all constant values. This enables constant propagation to precompute values that depend on the extracted dimension size, which in turn can enable additional fusions.
The motivating use case is to enable Transpose + FusedMatMul fusion for cross-attention matmuls in the Whisper encoder. As of this PR this now works, provided that shape inference was run on the ONNX model prior to conversion, as this is needed to have sufficient detail about the input to the relevant `Shape` operators.
A similar fusion that would be useful to add in future is `Gather(Shape(X))` where the gather indices are constant.
**TODO:**

Add ShapeSliceToConstant fusion

---

tools/infer-shapes.py

This should probably be done as part of model conversion and quantization in future, so that optimizations which depend on it ([example](https://github.com/robertknight/rten/pull/805#:~:text=provided%20that%20shape%20inference%20was%20run%20on%20the%20ONNX%20model%20prior%20to%20conversion)) work automatically.

Add script for applying shape inference to an ONNX model

---

src/optimize.rs
src/optimize/fusions.rs
src/optimize/pattern_matcher.rs

Make `Pattern` ref counted to make it easier for sub-patterns to be shared between difference branches of a pattern. Then use this to simplify the LayerNormalization fusion.

Support shared sub-patterns in pattern definitions

---

rten-simd/src/arch/aarch64.rs
rten-simd/src/arch/generic.rs
rten-simd/src/arch/wasm32.rs
rten-simd/src/arch/x86_64/avx2.rs
rten-simd/src/arch/x86_64/avx512.rs
rten-simd/src/ops.rs

Add a SIMD op that concatenates the low or high halves of two input vectors.
The initial use case will be for some vector shuffling in the Arm i8mm kernel.

Add Concat SIMD op and implement for i32 vectors

---

Cargo.toml
rten-cli/Cargo.toml
rten-gemm/Cargo.toml
rten-gemm/src/kernels/aarch64.rs
rten-gemm/src/lib.rs
rten-gemm/src/packing/int8.rs
rten-gemm/src/tests.rs
rten-testing/src/lib.rs

Add a new GEMM kernel for int8 matmul that uses [i8mm](https://developer.arm.com/documentation/ddi0602/2025-06/SIMD-FP-Instructions/UMMLA--vector---Unsigned-8-bit-integer-matrix-multiply-accumulate-to-32-bit-integer--vector--?lang=en) instructions.
The current implementation is very slightly slower on M3 Pro than the dotprod kernels. On an AWS Graviton 4 (c8g.xlarge), the i8mm kernel is about 22% faster for int8 matmuls, as tested on a modernbert-base model (with sequence_length 512). The marginal drop on M3 Pro might be due to the different kernel tile shape (8x8 instead of 16x4) rather than compute, but I need to verify.
Because the performance isn't always as good or better than dotprod, this is initially opt-in via an `i8mm` crate feature.
**Summary of changes:**
- Add a new GEMM …

Add i8mm GEMM kernel for i8 x u8 -> i32 matmul

---

Cargo.toml
rten-cli/Cargo.toml
rten-gemm/Cargo.toml
rten-gemm/src/kernels/aarch64.rs
rten-gemm/src/lib.rs

The first commit contains a small tweak to reduce the number of load instructions in the i8mm kernel (2x `ldp` + 4x `ldr` => 4x `ldp`). The second enables i8mm by default. Though it offers no performance advantage over dotprod on some systems (Apple Silicon), it is much better on others. For the sake of simplicity, use it wherever it is supported.

Slightly improve i8mm, enable by default

---

rten-gemm/src/kernels.rs
rten-gemm/src/kernels/aarch64.rs
rten-gemm/src/lib.rs
rten-simd/src/arch/aarch64.rs
rten-simd/src/arch/generic.rs
rten-simd/src/arch/wasm32.rs
rten-simd/src/arch/x86_64/avx2.rs
rten-simd/src/arch/x86_64/avx512.rs
rten-simd/src/elem.rs
rten-simd/src/ops.rs

Replace the existing GEMM kernel for older Arm CPUs which don't support the dotprod extension with one that uses UMLAL/UMLAL2 instructions.
The previous kernel used an instruction sequence which emulated UDOT.  The inner
loop of the new one computes an outer product of 8 elements of A with 8 elements
of B, similar to how the f32 kernels work.
The new kernel still uses the same matrix-vector/GEMV implementation as the old one. Only matrix-matrix products have been improved. Improving that has been left for a follow-up.
---
The new kernel is ~45% faster on a high end CPU (M3 Pro) and approximately 1/4 the speed of the UDOT / I8MM kernels in the microkernel benchmark, which aligns with expectations. On a low end CPU (Raspberry Pi 2 Zero / Arm Cortex A53), the new kernel is about 50% better.

Add int8 GEMM kernel using UMLAL/UMLAL2 instructions

---

.github/workflows/ci.yml
Makefile
rten-gemm/src/lib.rs
rten-simd/src/arch/wasm32.rs

Fix the WASM builds which don't use the default target features (relaxed-simd enabled or simd128 disabled) and overhaul the associated Makefile targets.
- Add missing import for `f32x4_relaxed_madd` in rten-simd
- Add missing `simd128` target feature check in rten-gemm
- Overhaul the WASM-related Makefile targets to make it easier to run tests and benchmarks against different crates and with different WASM features enabled.

Fix WASM relaxed-simd and no-SIMD builds and overhaul targets

---

src/optimize/fusions.rs
src/optimize/tests.rs

`Fusion::output_ids` returned the wrong value for identity fusions. As a result the list of operators to remove after applying the fusion was computed incorrectly in `GraphMutator::apply_fusion`. Consumers of the identity operator's output were still updated, but the identity operator itself was still left in the graph. This could subsequently prevent other fusions from being applied.
For example, given:
```
MatMul(Mul(Transpose(A), 1.0), Mul(Transpose(B), 1.0))
```
The result should be:
```
TransformInputs<MatMul>(A, B)
```
But the MatMul + Transpose did not get fused because the identity `Mul` operator was not properly removed from the graph.

Fix identity fusions not removing old operator from graph

---

rten-gemm/src/lib.rs
rten-gemm/src/prepack.rs

Given the stated rationale for choosing the `kc` block size, it makes sense to choose a 4x larger value for an i8/u8 RHS than f32. This brings the peak flops reported by `bench_gemm_mix` for a single thread closer to the kernel peak reported by `bench_kernel_int8`.
```
$ set -x RAYON_NUM_THREADS 1
$ cargo test -p rten-gemm -r -- --ignored bench_gemm_mix --nocapture
Testing kernel aarch64-u8i8i32-i8mm
m 512 n 512 k 512 iters 512. Duration 402.160ms (0.785ms/iter). GFLOPS 341.8
m 1024 n 1024 k 1024 iters 64. Duration 371.713ms (5.808ms/iter). GFLOPS 369.7
m 128 n 2048 k 512 iters 512. Duration 487.530ms (0.952ms/iter). GFLOPS 281.9
m 2048 n 128 k 512 iters 512. Duration 449.805ms (0.879ms/iter). GFLOPS 305.6
Testing kernel aarch64-u8i8i32-i8mm
m 512 n 512 k 512 iters 512. Duration 378.298ms …
```

Scale K block size with inverse element size

---

rten-convert/rten_convert/converter.py

The model converter already promotes weights from float16 to float32 because RTen doesn't support fp16 yet. Do the same for values and attributes (eg. the target type of the Cast operator).

Support float16 -> float32 dtype promotion for values and attributes

---

rten-convert/rten_convert/converter.py

The `saturate` attribute only applies to FP8 data types, which RTen does not support. Ignore it during model conversion when set to the default value.
Spec: https://onnx.ai/onnx/operators/onnx__Cast.html#attributes

Accept `saturate=1` attribute for Cast op

---

rten-convert/rten_convert/converter.py
rten-convert/rten_convert/schema_generated.py
rten-tensor/src/tensor.rs
rten-tensor/src/tensor/tests.rs
src/model.rs
src/model_builder.rs
src/op_registry.rs
src/ops/conv.rs
src/schema.fbs
src/schema_generated.rs

Support the [`output_padding`](https://onnx.ai/onnx/operators/onnx__ConvTranspose.html#attributes) attribute for ConvTranspose.

Support `output_padding` attribute for ConvTranspose

---

rten-convert/rten_convert/converter.py
rten-convert/rten_convert/schema_generated.py
src/op_registry.rs
src/ops/grid_sample.rs
src/ops/mod.rs
src/schema.fbs
src/schema_generated.rs

Add an initial implementation of the [GridSample](https://onnx.ai/onnx/operators/onnx__GridSample.html) operator, used by models such as [RT-DETR](https://huggingface.co/docs/transformers/en/model_doc/rt_detr).
This initial implementation only supports 4D inputs with default values for attributes: align_corners=0, mode=linear, padding_mode=zeros. The supported attribute values align with PyTorch's defaults for `torch.nn.functional.grid_sample`.

Implement GridSample operator

---

rten-vecmath/src/exp.rs

Compute SiLU as `x / (1 + (-x).exp())` instead of `x * (1 / (1 + (-x).exp()))`.
This is ~3-4% faster.

Slightly improve SiLU impl

---

src/ops/operators.rs
src/ops/pad.rs

Apply the same special-casing for zero that was used in https://github.com/robertknight/rten/pull/872. From a quick test on the Piper example this provided a modest speedup in that operator (~10%).

Optimize padding with zero constant in Pad operator

---

rten-simd/src/arch/aarch64.rs
rten-simd/src/arch/generic.rs
rten-simd/src/arch/wasm32.rs
rten-simd/src/arch/x86_64/avx2.rs
rten-simd/src/arch/x86_64/avx512.rs
rten-simd/src/ops.rs

Add two operations that will be useful for a sine and cosine implementation. Extracted from https://github.com/robertknight/rten/pull/879.

Add round_ties_even, mul_sub_from SIMD ops

---

rten-convert/rten_convert/schema_generated.py
src/op_registry.rs
src/ops/mod.rs
src/ops/unary_elementwise.rs
src/schema.fbs
src/schema_generated.rs

PRelu is technically a binary operator but is usually described as _elementwise_, with a learnable scalar or per-channel parameter, is is grouped with the unary ops.

Implement PRelu operator

---

rten-simd/src/arch/aarch64.rs
rten-simd/src/arch/generic.rs
rten-simd/src/arch/wasm32.rs
rten-simd/src/arch/x86_64/avx2.rs
rten-simd/src/arch/x86_64/avx512.rs
rten-simd/src/ops.rs
rten-simd/src/simd.rs

These replace the existing `Mask::{all_true, all_false}` methods with vectorized alternatives which are suitable for use in kernels rather than just tests.

Add `MaskOps::{any, all}` methods

---

rten-simd/src/dispatch.rs
rten-vecmath/src/erf.rs
rten-vecmath/src/exp.rs
rten-vecmath/src/tanh.rs
src/ops/mod.rs
src/ops/unary_elementwise.rs

Refactor unary op kernels to make the implementation approach more consistent across different operations, and make it easier to support additional data types in future.
Previously some operations were vectorized and parallelized with kernels that operated on slices of input, while others used `Tensor::{map_in, apply}` to apply a scalar operation on a single thread. Now all ops have kernels that apply the operation to a contiguous slice of the input. The kernel is invoked on chunks of the input by a parallel iterator.  This parallelizes the remaining unary ops that don't yet have vectorized implementations. For some ops this will have minimal benefit, since they are memory bound. For others (eg. trig ops) this will be much faster.
Aside from improving performance and consistency, the …

Refactor and parallelize unary op kernels

---

src/graph.rs
src/graph/node.rs
src/graph/tests.rs
src/ops/control_flow.rs
src/ops/mod.rs

This eliminates the unused code from default impls of `Operator::{has_subgraphs, run_subgraphs}` in operators that don't have subgraphs, which turned out to be quite a lot. It also makes checking whether an operator has subgraphs cheaper.
This reduces rten CLI binary size by 145KB (!)

Move subgraph methods into an Operator sub-trait

---

rten-vecmath/src/lib.rs
rten-vecmath/src/relu.rs
src/ops/unary_elementwise.rs

The scalar version is inefficient due to an unpredictable branch. The vectorized version uses masking + bitwise selection. Time spent in LeakyRelu ops in a NeuFlow v2 model went from ~17ms to ~1.5ms.

Vectorize LeakyRelu operator

---

rten-vecmath/src/exp.rs
rten-vecmath/src/lib.rs
rten-vecmath/src/testing.rs
src/ops/unary_elementwise.rs

The vectorized version avoids an unpredictable branch. For inputs where all values are >= 0., the SIMD version is slightly slower (0.8x reference), for random values in [-0.5, 0.5] it is much faster (9x reference).

Vectorize Elu activation

---

rten-tensor/src/iterators.rs
src/ops/gather.rs

Change ScatterElements to iterate over 1D lanes of data/indices/updates in
lock-step and then scatter all updates in that lane. This is much more efficient
than creating, modifying and indexing with dynamically-sized index vectors. It
also mirrors how GatherElements is implemented.
In a SageConv [^1] model, this reduced time in ScatterElements ops from
~55ms to ~12ms.
[^1]: https://huggingface.co/onnxmodelzoo/legacy_models/blob/main/Graph_Machine_Learning/sageconv_Opset16_graph_convolutions/sageconv_Opset16.onnx

Optimize ScatterElements

---

rten-gemm/src/packing/int8.rs
rten-tensor/src/layout.rs
rten-tensor/src/lib.rs
rten-tensor/src/tensor.rs
src/value.rs

Reduce the number of bounds checks when indexing a tensor from N + 1 (where N is the number of dimensions) to N. Previously each index was checked against the corresponding dimension size, then the offset returned by the layout was checked against the storage length. Remove the check against the storage length, but make it subject to the layout implementing an unsafe `TrustedLayout` trait.
Also remove `Layout::try_offset` in favor of making `offset` return an option, which makes `offset`/`offset_unchecked` consistent with eg. `get`/`get_unchecked` for tensors.

Reduce number of bounds checks when indexing a tensor

---

src/optimize.rs
src/optimize/fusions.rs
src/optimize/tests.rs

There was already a fusion to match identity patterns like `Add(x, 0)`.  Extend this to eliminate `Identity(x)` where possible. Identity ops are cheap, but eliminating them can unlock other fusions.

Eliminate Identity operations during graph optimization

---

Cargo.lock
rten-examples/Cargo.toml
rten-examples/src/whisper.rs

Previously the Whisper example used microfft to compute the FFT, which only supports power-of-2 FFT sizes. Whisper however uses an FFT of size 400. This was handled by zero-padding the signal to the nearest power of two (512). This is simple, but distorts the result slightly. Switch to using rustfft instead which can handle non-power-of-2 sizes. From brief testing, this improves accuracy a little.
A downside of rustfft is that it doesn't have a built-in real-to-complex FFT, so we do a complex FFT and discard the unused results. See https://github.com/ejmahler/RustFFT/issues/28.

Handle non-power-of-2 sized FFT more correctly in Whisper example

---

src/model.rs
src/op_registry.rs

Improve error message when loading a model which uses an operator that is unavailable because the rten crate was compiled without a certain feature.
Fixes https://github.com/robertknight/rten/issues/154

Improve errors if crate feature is not enabled

---

src/graph.rs
src/timing.rs

Fix an issue where operator input value names and shapes could be out of sync for commutative operators in verbose log output. This is because operands of commutative operators may be re-ordered in order to put the largest operand
first, enabling the operator to run in-place. The logging in `Graph::print_op_timing` did not account for this and so could end up logging input shapes in the wrong order.
The fix is to record the value node ID and metadata together before running the operator and pass the combined list to `print_op_timing`.
Note that re-ordering is limited to removing one of the operands from the original list and putting it first. The rest of the operands will be in their original order.

Fix operator input logging for commutative ops that run in-place

---

src/ops/random.rs

Fix flakiness introduced in 8517822c579607ec7a9a905d7caf8d1c7ecb14ec when lowering the threshold.
- Use a fixed seed in more tests to get predictable results
- In the one test were we do auto-generate a seed, use the old threshold to avoid a failure if the mean/std-dev are far from expectation by chance.

Fix flakiness in RandomNormal tests

---

rten-tensor/src/lib.rs
rten-tensor/src/storage.rs
rten-tensor/src/tensor.rs
rten-tensor/src/tensor/tests.rs

These are currently immutable once constructed as there are no equivalents of eg. `Arc::get_mut`. To allow for adding these in future, `Arc<[T]>` has been marked as a mutable form of storage (ie. cannot be used with broadcasting layouts).

Add basic support for reference-counted tensors in rten-tensor

---

src/graph/node.rs
src/model.rs
src/model/rten_loader.rs
src/optimize.rs

The preferred backing storage for constant data is either an mmap-ed buffer or a slice of a `Vec<u8>` into which the model file was originally loaded, as these options minimize copying when loading a model. When loading weights from a `.rten` file, weights are usually stored this way.
In cases where these options are not available, unique ownersip is currently used. However this prevents sharing of constants between sub-graphs, which in turn limits constant propagation in sub-graphs. To remedy this, allow constants to use an `ArcTensor<T>` as the backing storage and change existing creation of owned constants to use this where possible.
One place where unique ownership cannot be replaced with shared ownership trivially is after constant propagation. `Graph::partial_run` returns a set of …

Use shared ownership for more constants

---

tools/ort-infer.py

Fix division by zero when invoking ort-infer.py with `--n_evals 0`. Setting `n_evals=0` is useful to test/benchmark only loading the model, not running it.

Don't print timing stats if `--n_evals` is set to zero
