robertknight/rten

src/ops/norm.rs
Support tensors with 3 or more dimensions, instead of only NCHW.
Implemented as part of getting Tacotron2 models to work. See https://github.com/robertknight/xd-tts/tree/rten-inference.
=> Support non-4D tensors in BatchNormalization operator

src/model.rs
The standalone `load_model` function was a holdover from an early version of RTen.
=> Move body of `load_model` into `Model::load_with_ops`

src/gemm.rs
The special code path that was introduced in
11e6c9f557474c94fabd123b2eda1661eb22b759 for vector-matrix products neglected to handle the `bias` argument.
This issue was found by running E2E tests for Ocrs against the main branch of RTen.
=> Include bias for vector-matrix products

src/ops/gather.rs
By assuming that the `updates` and `indices` inputs are likely contiguous, we can avoid creating tensor views in the inner loop and instead just access sub-slices of the element buffers of the `indices`, `updates` and `output` tensors.
This reduces time in ScatterND ops in the Whisper base model from >150ms to ~25ms.
=> Optimize ScatterND

src/ops/layout.rs
The other layout ops are already in-place where possible, but `Unsqueeze` was an exception.
=> Support running Unsqueeze in-place

rten-tensor/src/tensor.rs, src/gemm.rs, src/ops/conv.rs
- Extend the support in `rten-tensor` for working with uninitialized tensors to also support views. To avoid hazards with eg. `TensorBase::non_contiguous_data`, there is a restriction that `TensorBase::assume_init` can only be used with contiguous views/tensors. 
- Avoid zero-initializing buffers that we are going to fully overwrite as part of fused matrix multiplication + bias addition steps
- Defer initialization of output rows in depthwise convolutions until just before we compute the row's content
In a test with Ocrs, this reduced the proportion of main-thread time spent zeroing buffers from 5% to 0.5%.
=> Avoid redundant zeroing of output buffers in conv operations

src/gemm.rs, src/ops/pooling.rs
This addresses a couple of things I noticed testing Ocrs with rten v0.7.0:
- Virtual calls to `Kernel::{mr, nr}` were showing up high in the profile. They don't change during a gemm call, so can be cached
- Avoid redundant zeroing of output in MaxPool op. This is similar to recent changes for convolutions, `MatMul` etc.
=> Avoid redundant zeroing for MaxPool, reduce virtual calls to `Kernel::{mr, nr}`

src/ops/conv.rs
This operation needs a lot of work to be respectably efficient, but at least it is now inefficient in parallel.
=> Parallelize depthwise convolution over chunks of channels

rten-vecmath/src/erf.rs, rten-vecmath/src/exp.rs, rten-vecmath/src/lib.rs, rten-vecmath/src/softmax.rs, rten-vecmath/src/tanh.rs, rten-vecmath/src/testing.rs, src/ops/unary_elementwise.rs
For unary op executions that are not in-place, the output buffer does not need to be zero-initialized.
The softmax implementation was converted to use a possibly-uninitialized output buffer in this PR, although the `Softmax` operator in the `rten` crate doesn't benefit yet, as it copies the input and then runs the in-place implementation.
On the YOLOv8 demo, with the "small" model, this reduces time in `Sigmoid` ops by ~20% on my system (25ms -> 19ms).
=> Avoid redundant zeroing of output buffers for unary ops

src/graph.rs, src/ops/conv.rs, src/ops/resize.rs
This is a collection of small optimizations found while testing the YOLOv8 example in rten-examples:
- During graph execution, don't keep track of reference counts for values that are constants, since we are not going to free these
- Avoid redundant zeroing of output in `Resize` operator
- Avoid prepacking weights in the `Conv` operator if we are only going to use the packed weights in one matmul
=> Minor YOLO optimizations

src/ops/pooling.rs
Convert remaining pooling ops to allocate from the pool and avoid redundant zeroing of the output buffer.
=> Convert remaining pooling ops to use pool and avoid redundant zeroing

rten-examples/src/yolo.rs, src/ops/layout.rs, src/ops/non_max_suppression.rs
See https://github.com/robertknight/rten/issues/109
=> Use pool for NonMaxSuppression, Shape, Size operators

src/ops/rnn.rs
Even though I'm planning to significantly rework the internals of these operators soon [1], converting them to use the pool now allows https://github.com/robertknight/rten/issues/109 to be resolved. Also using the pool now only requires smaller code changes which won't lead to major merge conflicts.
[1] https://github.com/robertknight/rten/issues/85
=> Convert RNN ops to use pool

src/ops/rnn.rs
Reduce the number of matrix multiplications in the LSTM operator from `num_directions * seq_len * 8` to `num_directions * seq_len * 2`, by updating all gates in one matmul instead of a separate matmul per gate.
This benefits from the better compute efficiencies of larger matrix multiplications. Also it means that the 4 gates are updated in parallel. Looking at this code again I realize that the operator inputs are structured in a way that assumes implementations will take this approach.
Part of https://github.com/robertknight/rten/issues/85
=> Combine matmuls for different gates in LSTM op

tools/ort-infer.py
Expose the most interesting knobs as CLI flags for easy experimentation.
=> Add flags to control optimizations and parallelism in ort-infer.py

src/ops/pooling.rs
The count should only be incremented for each spatial position, not each (spatial position, channel).
=> Fix counting of non-padding elements in AveragePool op

rten-imageproc/src/contours.rs
This is more memory-efficient than using i32 elements, and also a more obvious API as the values for on/off elements are encoded in the type.
=> Make argument to `find_contours` a boolean mask.

rten-convert/rten_convert/converter.py
Constant and value nodes need names if they are to be referenced as model or operator inputs or outputs. Operators however do not have to have names, they are merely useful for debugging etc.
This fixes an error when converting ONNX models from Piper - https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/en/en_US/lessac/medium/en_US-lessac-medium.onnx.
=> Allow operator nodes to be unnamed when converting ONNX models

src/model.rs, src/model_builder.rs, src/ops/unary_elementwise.rs
See https://stackoverflow.com/a/29404692/434243
=> Remove unnecessary `extern crate` declarations

src/ops/conv.rs
By swapping the order of the matrix multiplication operands, the output has the
shape `(out_c * k_h * k_w, in_h * in_w)` which actually matches the name
`col2im` (ie. every column is a patch) and the order in which the ONNX `Col2Im`
operator expects its input.
Moreover, this layout is more convenient for fusing the bias addition into
col2im, as the channel dimension is now the outermost one. Also the longer
running loops over X and Y are now innermost, which makes some other
optimizations easier.
=> Transpose matmul operands in ConvTranspose and fuse bias addition

rten-examples/src/piper.rs
The previous suggestion to use an LLM sort-of-worked, but the quality of results was poor compared to using the actual library that Piper uses.
Also apply some clippy fixes noticed while testing this.
=> Add better advice on how to generate phoneme sequences

rten-tensor/src/storage.rs
As noted in the added comments, `as_ptr` and `len` must define a valid range of memory which is correctly aligned for the type.
=> Mark `Storage` trait as unsafe and document requirements

src/ops/non_max_suppression.rs
The existing tests passed because the test cases used the same coordinates for the X and Y dimensions, so an issue where these were mixed up in the implementation went unnoticed.
Fixes https://github.com/robertknight/rten/issues/176
=> Fix mixup of right/bottom coordinates in `NonMaxSuppression` operator

rten-tensor/src/lib.rs, src/iter_util.rs, src/lib.rs, src/tensor_pool.rs
Revise the front page of the rten crate documentation, and also adjust a few exports.
=> Update documentation for rten crate

rten-cli/src/main.rs
Previously automatic sizes for dynamic axes were determined using simple heuristics with a value of 256 as a fallback. This could result in very slow model execution if eg. the batch size was resolved to 256.
Specifying dynamic axis sizes manually was unergonomic because it required specifying the size of every dimension of an input, including the fixed dimensions. Also if there were multiple inputs with the same symbolic axis name, each had to be specified independently.
Change this as follows:
- Default the size to 1 for any dynamic dimension that is not specified manually. This seems more likely to lead to successful and fast model execution, if we're going to pick defaults at all.
- Replace the `--shape` flag with `--size`, which takes `dim_name=size` or `input_name.dim_name=size` …
=> Improve how dynamic input sizes are handled in rten CLI

.github/workflows/ci.yml, Makefile, src/model.rs, src/threading.rs
Correct two broken links in the docs, and build docs as part of CI.
=> Build docs in CI

src/ops/binary_elementwise.rs
Replace the use of `broadcast_iter` for broadcasting + iteration over non-contiguous tensors with a more efficient pattern based on iterating over a statically determined number of inner-most dimensions (4) with nested for-loops, and a variable number of outer dims. This pattern is already used in other places (eg. `rten-tensor/src/copy.rs`).
Also fix an issue where outputs were not allocated from the pool in some cases.
Tested on the [Magika model](https://github.com/google/magika/blob/main/python/magika/models/standard_v1/model.onnx) with a batch size of 100, this reduces time in Mul ops from ~288ms to ~118ms on my system.
Part of https://github.com/robertknight/rten/issues/189.
=> Make binary ops over non-contiguous tensors faster

rten-tensor/src/slice_range.rs
This finishes the changes from 84c8f25f75f15c650969c3a54caed8f841d1f700.
=> Remove last usage of local `div_ceil`

tools/ort-profile-summarize.py
Add an option to show operator typings by input shape, similar to the output when setting `RTEN_TIMING` to `by-shape=1`.
=> Add option to break down timings by shape in ort-profile-summarize.py

src/gemm.rs
`Cow` usage was previously part of a variant of `GemmExecutor::prepack_a` which took an output buffer reference as an argument. This use case has since been replaced by `GemmExecutor::prepack_a_in` which takes an allocator.
=> Remove unnecessary lifetime / Cow usage from `PackedAMatrix`

src/gemm.rs, src/gemm/kernels.rs
- Use `par_chunks_mut` rather than `par_bridge` as this allows Rayon to more cheaply divide up the work between threads.
- Maximize the column block size according to the available parallelism. This reduces coordination overhead, at the cost of reducing work-stealing opportunities if some cores are unavailable, since the individual chunks of work are larger.
- Set the row block size to be small. This reduced L2 cache misses in the kernel significantly according to Instruments.
For unit-stride B, the kernel divides the row blocks into column tiles that are a multiple of the SIMD register width. Using a small row block size makes access to B "more contiguous" as there are fewer steps between reading one piece of a row of B and then reading the next piece of the same row, as part of the next …
=> Tune vector-matrix multiplication

src/ops/gather.rs
This happens often in subgraphs that start with a `Shape` operator, where `Gather` is used to extract a single dimension. There are ~380 such cases in GPT-2 medium for example.
=> Optimize using `Gather` to index vector with scalar

docs/rten-file-format.md, src/lib.rs, src/model.rs, src/ops/mod.rs
Update the rten file format documentation and also make some minor improvements for the docs related to model inputs and outputs and loading errors.
=> Update rten file format documentation

tools/ort-infer.py
Avoid needing to run `tools/ort-infer.py` multiple times to find all the dynamic dimensions that need to have sizes specified.
=> List all missing dynamic dims in one message

src/model.rs
Check model loading fails with expected errors in various scenarios.
=> Add test for loading invalid models

rten-examples/src/qwen2_chat.rs, rten-text/src/tokenizers/bpe.rs
In the GPT-2 model, token IDs are 256 plus the rank of the pair in the merge list that makes up the token. For other tokenizers this is not the case, and for these tokenizers `Bpe::decode` was producing incorrect output.
This commit fixes the BPE tokenizer to use token ID <=> byte sequence mapping from the vocabulary, if provided, when decoding. If no vocabulary is provided, the token IDs are derived from the merge list.
With this change the `qwen2_chat` demo can now be used with [SmolLM](https://huggingface.co/blog/smollm) instruct variants, eg. https://huggingface.co/HuggingFaceTB/SmolLM-360M-Instruct. I found that I needed to use the ONNX models uploaded to Hugging Face rather than ONNX models exported locally via Optimum, as the latter were producing incorrect results for reasons I …
=> Use token IDs from vocabulary when decoding using BPE

src/ops/resize.rs
When the scale is 1, the operator can just copy its inputs. Unlike the general case, this does support tensors that are not 4D, since this is easy to implement.
The initial use case is an identity resize of a 3D tensor in the Segment Anything image encoder.
=> Add fast path for Resize when scale is 1 for all dimensions

src/ops/einsum.rs
When the equation reduces over multiple dimensions, implement this in terms of a matrix multiplication by first flattening the reduced dimensions into a single dimension.
Part of https://github.com/robertknight/rten/issues/298.
=> Use matmul to reduce multiple dimensions in Einsum more efficiently

src/ops/einsum.rs
- For input terms, repeated labels should take the diagonal, but this is yet implemented. In the meantime, at least produce a helpful error. For output terms, repeats are always disallowed.
- For input and output terms, using ASCII ellipses ("...") to control broadcasting is not yet supported. In the meantime, produce a helpful error.
Part of https://github.com/robertknight/rten/issues/298.
=> Error if an Einsum term contains repeated labels or ellipsis

src/ops/einsum.rs
Support using "..." in Einsum equations to control broadcasting, following behavior in [`np.einsum`](https://numpy.org/doc/stable/reference/generated/numpy.einsum.html). Per the [ONNX docs](https://onnx.ai/onnx/operators/onnx__Einsum.html), "..." must stand for the same number of dimensions in each term.
Part of https://github.com/robertknight/rten/issues/298.
=> Support ellipsis for broadcasting in Einsum equations

src/graph.rs, src/model.rs, src/optimize.rs
In preparation for adding support for ONNX control flow operators which have subgraphs as attributes, refactor graph loading and input/output ID storage.
- Make the default input and output node IDs for a graph run properties of the graph. This avoids the need to pass them around separately in various contexts.
- Make node name -> ID lookup functionality part of the `Graph` type.
- Extract graph loading out of `Model::load_impl` into a separate function. This will help with implementing subgraph loading in future.
=> Refactor graph loading in preparation for adding control flow operators

src/model.rs, src/model_builder.rs
In preparation for adding control flow operators which have their own subgraphs that need to be serialized, extract the graph serialization logic out of ModelBuilder into a separate GraphBuilder type.
=> Extract graph serialization code out of ModelBuilder

rten-cli/src/main.rs
This runs the model without producing other output, unless an error occurs.
This is useful to reduce output noise when using the CLI to run a model for debugging or in CI.
=> Add `--quiet` flag to rten-cli

rten-generate/src/generator.rs
Generalize the KV caching in rten-generate to support cross-attention KV-cache inputs used by eg. Optimum-exported decoder models that are part of an encoder-decoder system. In these models there are two kinds of KV-cache input, self-attention KV-caches which are extended on each run and cross-attention KV-caches which are computed on the first run and reused without modification in subsequent runs.
=> Support cross-attention key-value caches in rten-generate

src/graph.rs
Part of https://github.com/robertknight/rten/issues/308
=> Include subgraphs in `Model::total_params` count

src/ops/norm.rs
Fixes https://github.com/robertknight/rten/issues/307
=> Exit early in softmax if lane size is zero

src/ops/reduce.rs
This is used by OpenAI CLIP models for example (https://huggingface.co/openai/clip-vit-base-patch32).
=> Support int tensors in ArgMin and ArgMax ops

src/ops/conv.rs, src/ops/conv/depthwise.rs
Fix an out-of-bounds slice in depthwise convolution if the input is contiguous, but the stride of the H dimension is larger than the size of the W dimension. This is possible if the H dimension has size 1 (see `is_contiguous` function in rten-tensor).
=> Fix out-of-bounds slice in depthwise conv when row stride != row len

src/ops/conv.rs, src/ops/conv/depthwise.rs
Fix two cases where the input and output coordinate ranges for depthwise convolution could be computed incorrectly.
- In the first case the output range for certain kernel positions had start > end.  This could happen when the padding size exceeded the output width.
- In the second case the stride was not accounted for when computing the min output X coordinate to update for a given kernel X coord.
In the process, add some more comments around a slightly tricky piece of code.
The issues were found while testing a port of https://github.com/emotechlab/silero-rs to RTen.
=> Fix incorrect output range calculation in depthwise conv

src/ops/layout.rs
Use `Tensor::remove_axis` to remove 1-sized axes without copying if input is non-contiguous. This also makes the Squeeze implementation mirror Unsqueeze.
=> Avoid copying tensor in in-place `Squeeze` op if non-contiguous

rten-examples/Cargo.toml, rten-examples/README.md, rten-examples/src/rmbg.rs
Add an example that uses the [RMBG](https://huggingface.co/briaai/RMBG-1.4) model to remove the background from an image.
=> Add a background removal example

src/ops/matmul.rs
This is a step towards reusing this for other float types and integer types as well. Currently kernels are only implemented for f32 input/output types.
=> Make MatMul operator body generic over element type

src/gemm.rs, src/ops/matmul.rs
Impl `Default` for `GemmExecutor` for supported combinations of types and use `GemmExecutor<LhsT, RhsT, OutT>: Default` as a bound in various functions which rely on having a matmul implementation available for the types. Then using this, make the `Gemm` operator implementation generic over the element types. It still only supports f32 as kernels aren't available for f16 or bfloat16 yet, but once those kernels are added, it will be a small step to support them in this operator.
=> Make `Gemm` operator implementation generic

src/ops/conv.rs, src/ops/conv/depthwise.rs, src/ops/conv/im2col.rs
This is a step towards supporting other float types and integer types in convolution operations.
=> Make the bulk of the `Conv` implementation generic

src/ops/mod.rs
Make them work with any `TensorBase<S, L>` for which `TensorBase<S, L>` => `Output` conversions exist.
=> Generalize `IntoOpResult` impls

rten-generate/src/generator.rs
Make `GeneratorError::GenerateError` errors easier to debug by adding context.
This helped with debugging an issue while working on https://github.com/robertknight/rten/pull/395 where the `logits` output had an unexpected rank.
=> Add context to token generation errors

rten-examples/src/detr.rs
Modify the DETR example so that it works with other DETR-based examples available on eg. Hugging Face, such as Table Transformer (https://huggingface.co/microsoft/table-transformer-detection).
- Support specifying a custom list of labels
- Support models which use the maximum class index to represent "no object" instead of class 0.
- Support specifying probability threshold for detections
=> Support other DETR-based models in the DETR example

rten-examples/src/bert_qa.rs, rten-examples/src/distilvit.rs, rten-examples/src/gpt2.rs, rten-examples/src/jina_similarity.rs, rten-examples/src/qwen2_chat.rs, rten-examples/src/trocr.rs, rten-examples/src/whisper.rs, rten-text/src/tokenizer.rs, rten-text/tests/reftest.rs
This handles the common use case of reading the file and parsing it in one step.
=> Add `Tokenizer::from_file` convenience method

src/ops/mod.rs
Make `Output` -> `NdTensor` conversions fail with a more helpful error if the `Output` has a different rank than the `NdTensor` type.
This resolves a confusion I had testing a Depth Anything model which returned a 3D (batch, height, width) output instead of 4D (batch, 1, height, width) as expected by the depth_anything example.
=> Improve error if Output conversion fails due to rank mismatch

rten-examples/src/depth_anything.rs
Some Depth Anything variants (eg.
https://huggingface.co/onnx-community/depth-anything-v2-small) output an (N, H, W) tensor rather than (N, 1, H, W).
=> Support Depth Anything variants with 3D output

rten-text/src/models/wordpiece.rs, rten-text/src/normalizers.rs, rten-text/src/tokenizer.rs, rten-text/src/tokenizer/json.rs, rten-text/tests/reftest.rs
Implement all the Unicode normalizers supported in tokenizer.json files.
=> Implement NFC, NFD, NFKC, NFKD normalizers

rten-convert/rten_convert/converter.py, rten-text/src/normalizers.rs, rten-text/src/pre_tokenizers.rs, rten-text/src/tokenizer.rs, rten-text/src/tokenizer/json.rs
These are all the additional normalizers required by CLIP.
=> Implement Lowercase, Replace, Sequence normalizers

src/ops/binary_elementwise.rs
Originally the fast path was faster, as the slow path used tensor iterators (`TensorBase::iter`). Since the fallback path was changed to a pattern where it iterates over slices with a static rank, this has changed.
This was tested with https://huggingface.co/naver-clova-ix/donut-base-finetuned-docvqa where the `Where` operator is used with inputs where `cond` and `y` have the same shape and `x` is a scalar. In this case we could do better by skipping index calculations for `x`.
=> Remove "fast path" for Where that is not actually faster

src/optimize.rs
Support matching and fusing LayerNormalization sub-graphs that do not have a final `Add` operation to add a bias. The LayerNormalization operator already supports this case, so we just have to recognize it in the optimizer.
Tested with the [ModernBERT](https://huggingface.co/answerdotai/ModernBERT-base) ONNX model.
=> Support fusing LayerNormalization without bias

rten-cli/src/main.rs
Report the mean, min, max and standard deviation of run durations. In particular it is useful to get a sense of the variance across runs.
=> Report duration run statistics in CLI

src/gemm.rs
This outputs CSV formatted data which can be used to generate charts.
=> Add benchmark for square GEMMs up to size 512

tools/ort-infer.py
These changes generally align the usage and output of ort-infer.py with rten-cli so it is easier to switch between the two.
- Align handling of dynamic dimensions whose sizes are not specified with rten-cli. This means using `-s`/`--size` as the argument name and defaulting to 1 rather than raising an error if a size is missing.
- Print a summary of model inputs and outputs
- Report min/max/standard deviation duration statistics
=> Improve ort-infer.py script

src/ops/gather.rs
Add a note to explain why this op initializes every element of the output and then remove the redundant zeroing.
=> Avoid redundant zeroing of Gather op output buffer

src/optimize.rs, src/optimize/pattern_matcher.rs
Tweak a few internal APIs for better readability / ergonomics.
=> Refine a few internal APIs in graph optimizer

rten-cli/src/main.rs
This provides progress info when executing a large number of runs.
=> Prefix run timing with run number

src/gemm/kernels/simd_generic.rs, src/gemm/packing.rs
This change means that both packed and unpacked LHS inputs handled by the f32 GEMM kernel have unit column stride, which simplifies indexing calculations when broadcasting elements of A in the main loop. As a result a bunch of `ADD` instructions are eliminated from the hottest loop in the code.
The previous packing code has been kept around to enable comparisons of the earlier approach to packing of the LHS (always pack, column major order) and the new approach (only pack if not unit column stride, row major order). The earlier approach follows the BLIS framework. The newer approach matches what ORT and XNNPACK do.
=> Switch to row major layout for packed blocks of LHS / A

src/gemm.rs
This saves a few lines but also makes the symmetry more apparent. When making changes it should help to avoid cases where the code is updated for one but not the other, which happened a few times during earlier work.
=> Unify implementation of pre-packed A and B matrices

src/constant_storage.rs, src/model.rs
Since there are safety concerns here, it is better to have just one implementation.
=> Refactor duplicated code for casting slices

rten-vecmath/src/softmax.rs
This is a small performance win. On my i5 laptop the AVX-512 version is now ~10x faster than non-vectorized compared to ~9.5x before.
=> Use multiplication-by-reciprocal instead of division in final softmax pass

src/ops/matmul.rs
In the ONNX spec, MatMulInteger allows the `a_zero_point` and `b_zero_point` inputs to be scalars, vectors or batches of vectors. This adds support for the vector case, but not batches of vectors yet.
=> Support vector zero points in MatMulInteger

src/gemm.rs
Refactor the reference GEMM implementation to make it possible to use with other input/output types and make it easier to add new options.
=> Refactor reference GEMM implementation and make it generic

src/gemm.rs
Starting point comparing the optimized AVX2 f32 kernel against the completely unoptimized generic int8 kernel:
```
f32 x f32 -> f32
Testing kernel fma
m 512 n 512 k 512 iters 512. Duration 414.913ms (0.810ms/iter). GFLOPS 331.2
m 1024 n 1024 k 1024 iters 64. Duration 400.034ms (6.251ms/iter). GFLOPS 343.6
m 128 n 2048 k 512 iters 512. Duration 468.977ms (0.916ms/iter). GFLOPS 293.1
m 2048 n 128 k 512 iters 512. Duration 431.327ms (0.842ms/iter). GFLOPS 318.6
m 1 n 4096 k 512 iters 512. Duration 77.115ms (0.151ms/iter). GFLOPS 27.8
m 1 n 4096 k 512 iters 512. Duration 70.398ms (0.137ms/iter). GFLOPS 30.5
u8 x i8 -> i32
Testing kernel generic-i8
m 512 n 512 k 512 iters 512. Duration 2200.817ms (4.298ms/iter). GFLOPS 62.4
m 1024 n 1024 k 1024 iters 64. Duration 2154.494ms (33.664ms/iter). …
```
=> Add a basic benchmark for int8 matmul

src/gemm.rs
Reuse the `all_gemms` utility added for int8 GEMMs to run tests against all supported f32 kernels.
=> Simplify running tests against all supported f32 kernels

tools/ort-infer.py
Resolve an issue encountered while testing [SmolVLM models](https://huggingface.co/HuggingFaceTB/SmolVLM-500M-Instruct/tree/main).
=> Support generating inputs for bool tensors in ort-infer.py

src/gemm/kernels/simd_generic.rs
While iterating over rows K..K+3 in the current column block, fetch data for the same rows in the next column block. f32 GEMV already has the same optimization.
=> Pre-fetch next column block in int8 GEMV

docs/performance.md, docs/quantization.md, src/lib.rs
- Add a quantization guide in `docs/quantization.md`
- Expand the quantization section in the rten crate front matter
- Add a mention of quantization in the performance guide
=> Add documentation on quantization support in rten

src/ops/matmul.rs
Fixes https://github.com/robertknight/rten/issues/419
=> Support vector inputs in MatMulInteger

src/ops/matmul.rs, src/ops/mod.rs
Prepacked weights are currently support for MatMul. Extend this to MatMulInteger.
=> Support prepacking weights for MatMulInteger

src/ops/reduce.rs
Use `map_input` for dispatching to type-specific implementation in reduction ops instead of custom macros, for consistency.
=> Use `map_input` macro for reduction ops

src/gemm/kernels/simd_generic.rs
With this change the safety docs for `simd_int8_gemm` now cover everything that is not guaranteed by either the type system or a runtime check.
=> Add input buffer length sanity checks in `simd_int8_gemm`

rten-convert/rten_convert/schema_generated.py, src/model.rs, src/model_builder.rs, src/op_registry.rs, src/ops/convert.rs, src/ops/mod.rs, src/schema.fbs, src/schema_generated.rs
See https://onnx.ai/onnx/operators/onnx__CastLike.html.
=> Implement `CastLike` operator

src/ops/norm.rs
This brings the improvement from b245b726b3279ae7707b5883595a9a13c164b18c to InstanceNormalization.
=> Unify InstanceNormalization and BatchNormalization outer loops

src/model.rs
Make it easier to debug model load errors that relate to specific nodes by including the name of the node in the error message.
In the process the types of some `ModelLoadError` variants have been erased and replaced with generic `Box<dyn Error>` types. This enables adding new information to these errors in future without a breaking API change. This change is itself technically a breaking change, although it is unlikely anyone was relying on them.
=> Include node name in model load errors where applicable

rten-vecmath/src/normalize.rs
For operations like BatchNormalization which have only per-channel scale and bias, skip the add/multiply with per-element scale/bias.
This could be improved further in future by splitting the normalization kernel into two separate ones that cover the two cases actually used. Each one can then do just the operations it needs.
- Constant scale and bias (BatchNormalization)
- Per element scale and optional per element bias (InstanceNormalization, LayerNormalization, GroupNormalization)
=> Add fast path for normalization with only per-channel scale/bias

rten-vecmath/src/normalize.rs
Add a fast path to the normalization kernel for the case where there are per-element and constant scales, but no bias. This is used by LayerNormalization when there is no bias and also RMS normalization.
This makes LayerNormalization ops ~18% faster in ModernBERT on my M3.
=> Add LayerNormalization kernel fast path for no-bias case

rten-vecmath/src/erf.rs
Speed up `Erf` and `Gelu` by using the reduced-range exp(x) from https://github.com/robertknight/rten/pull/682 in the erf approximation. I re-ran `test_erf_exhaustive` to verify the max error is still within tolerance.
```
cargo test -p rten-vecmath -r -- --ignored --nocapture bench_erf
Before: reference 320510 us vectorized 71221 us. reference / vectorized ratio 4.500
After: reference 335342 us vectorized 61125 us. reference / vectorized ratio 5.486
```
=> Optimize Gelu by using reduced-range exp in erf approximation

src/ops/slice.rs
Validate the lengths of the `starts`, `ends`, `axes` and `steps` attributes.
=> Validate lengths of attributes in Slice op

src/ops/transform_inputs.rs
Also remove some low-value comments.
=> Use `map_input` macro simplify supporting all tensor types

src/ops/norm.rs
The single-threaded case is now decently optimized with vectorization and ILP. Go a step further and add thread parallelism. The change also applies to the RmsNormalization fused op.
Tested with ModernBERT-base on M3, this makes LayerNormalization ~2.3x faster.
Fixes https://github.com/robertknight/rten/issues/334
=> Parallelize LayerNormalization, RmsNormalization

src/ops/unary_elementwise.rs
When a vectorized and parallelized unary operator's `run_in_place` implementation is invoked with a non-contiguous input, fall back to using the non in-place version instead of using a scalar version of the function. This incurs the overhead of first copying the input into a contiguous buffer, but the cost is usually much less than forgoing all parallelism. This can be optimized in future by materializing the contiguous input in cache-sized chunks.
An additional benefit of this change is that the output buffer is nicely contiguous for subsequent operations.
Fixes https://github.com/robertknight/rten/issues/192
=> Handle non-contiguous inputs more efficiently in in-place unary ops

src/gemm/kernels/simd_generic.rs
Simplify the epilogue of `simd_int8_gemm` which writes the accumulator tile of C, in registers, back to the output. This fixes an issue on Arm where the tile was spilled to the stack in the main loop.
Fixes https://github.com/robertknight/rten/issues/701
=> Fix C tile being spilled to stack in Arm int8 GEMM

src/ops/binary_elementwise.rs
Extend the `Pow` operator to support the case where the base and exponent inputs have different types. Initially the only such supported combination is base=i32, exp=f32.
The spec definition allows for the base and exponent to have different types, but doesn't state the semantics. The implementation here is based on what ONNX Runtime does (see comments).
The need for this functionality was encountered with the "/Pow" node in https://huggingface.co/onnx-community/Florence-2-base-ft/blob/main/onnx/vision_encoder.onnx.
=> Support Pow operator with different base and exponent types

src/optimize.rs, src/optimize/pattern_matcher.rs
Make the constructors associated functions, avoiding the need to import them separately. Also remove `unary_op_key` and instead add a `with_name` method that modifies an existing pattern to set the key.  This works for any operators, not just unary ones.
=> Make `Pattern` constructors associated functions

src/ops/pad.rs
Done as a trial of Claude Code for refactoring.
=> Refactor `test_pad_invalid_inputs` test to be table driven

src/ops/reduce.rs
This doubles the line count unfortunately, but it makes changing the body or adding new cases easier.
via Claude Code.
=> Refactor more reduce op tests to be table driven

src/optimize.rs
This fixes an issue observed in ModernBERT where enabling Transpose -> Concat fusion caused a panic because the "Concat" node took the same input multiple times.
=> Fix panic during optimization if a fused operator has duplicate inputs

src/optimize.rs
These operators all copy chunks of their input using functions in rten-tensor that can handled transposed inputs well.
=> Enable Transpose -> {Split, Slice, Concat, Expand} fusion

rten-tensor/src/iterators.rs
Improve the worst-case complexity of advancing iterators by n steps. This is used by `Iterator::nth` and also when Rayon splits iterators using parallel iteration, via `<ParIter<I> as Producer>::split_at`.
=> Optimize `Iterator::nth` impls from O(n_steps) to O(ndim)

rten-cli/src/main.rs
Support passing `-p`/`--profile` flag to CLI multiple times to generate detailed profiling output.
```
rten model.rten -p  # Basic timing
rten model.rten -pp  # Detailed timing
```
=> Output detailed profiling info if `--profile` flag is repeated

rten-cli/src/main.rs
The calculations internally captured the total whole milliseconds for each run, yet displayed results with two decimal places, which was confusing. Capture and report timings with sub-millisecond precision.
=> Avoid flooring durations to nearest millisecond

rten-tensor/src/iterators.rs, rten-tensor/src/layout.rs
Combine axes when creating tensor iterators to maximize the number of iterations that use the fast path for stepping the inner two dimensions.
- Extract logic from `<DynLayout as ResizeLayout>::merge_axes` for reuse and rewrite to use a single buffer for merged shape/strides
- Change `IndexingIterBase::new` to merge axes using extracted `merge_axes` function and avoid duplicated code for constructing `IterPos` items.
See https://github.com/robertknight/rten/issues/11#issuecomment-2909018790
=> Merge axes when constructing tensor iterator

docs/adding-operators.md
- Update the first two sections to have steps in the same order
- Update instructions to reflect changes in the code organization
- Add a section on defining graph fusions
=> Revise the documentation for adding new operators

src/optimize/fusions.rs
Make some very minor corrections to e751b862718f14e2a5093921577ffee6dade4327.
=> Correct PatternFusion docs

src/optimize.rs
Instead of explicitly separating fusions into separate passes in order to combine them, iterate until a fixed point is reached.
The actual number of passes that result in changes will be the same for many models with the current set of fusions (2), but this adds flexibility for the future.
=> Apply fusions in a loop until fixed point is reached

src/ops/norm.rs
The now more widely used LayerNormalization, RmsNormalization ops were parallelized some time ago. Make a similar change for batch and instance norm ops.
=> Parallelize BatchNormalization, InstanceNormalization over channel

src/ops/quantize.rs
On an M3 Pro, this provided a ~2.2x speedup for DynamicQuantizeLinear ops on Whisper medium.
=> Parallelize QuantizeLinear, DynamicQuantizeLinear

src/tensor_pool.rs
This enables potentially re-using a pool across multiple model runs in future. Thread-safety is a requirement for this since `Graph::run` executes the model in a Rayon thread pool which is usually different than the calling thread.
Also add some notes about the rationale for the pool and the performance issues of allocating/de-allocating large buffers.
=> Make `TensorPool` usable across threads

src/optimize.rs, src/optimize/fusions.rs
Part of https://github.com/robertknight/rten/issues/788
=> Add Reciprocal op fusion

src/optimize.rs, src/optimize/fusions.rs
Use shape information for softmax input to check if a positive `axis` attribute value refers to the last dimension.
=> Support fusing Add + Softmax where Softmax axis is positive

src/optimize.rs, src/optimize/fusions.rs
Follow up to https://github.com/robertknight/rten/pull/798.
Improve identity fusion by removing the operator entirely when possible, rather than just replacing with `Identity`. This can enable additional fusions to apply. An exception is that we can't remove the operator if it was connected directly to an output value.
=> Eliminate identity ops entirely in optimizer

src/graph.rs
Tested on a quantized model with ~630M params, this made loading the model about 2x as fast when prepacking is enabled.
=> Parallelize weight prepacking

src/graph/planner.rs
The optimizer does a lot of micro-planning where it computes a plan to run a small subgraph. At the start of planning the planner added the ID of every constant node in the whole graph to the resolved value set, which is wasteful when considering a small subgraph. Fix this by creating a custom struct for the resolved value set, which checks for a node ID being a constant when a lookup is performed.
This makes loading a quantized whisper-v3-large-turbo model about 20% faster, with prepacking and mmap-ing enabled.
=> Don't store constant node IDs explicitly in resolved value set

src/graph.rs, src/graph/tests.rs
Allow an operator to return more outputs than the operator graph node has output IDs. The excess outputs are simply ignored.
Also add tests for more/fewer output IDs than operator outputs and improve the error message if there are fewer outputs than output IDs.
The immediate use case was a model I came across with a Dropout node that had one output in the graph, but Dropout generates two outputs (data, mask). There is another option here specifically for this case, which is to have Dropout check if its optional `mask` output is used and not generate it in that case. That would be more efficient. Dropout doesn't appear that often in models because it is usually removed during export, so this isn't a major priority.
=> Allow operators to return more outputs than are used

rten-convert/rten_convert/converter.py
Warnings about out-of-range values in constants were already silenced for `i64::MIN` as this is used to represent negative infinity in some contexts. Some models however use `-i64::MAX` instead, which is `i64::MIN + 1`.
=> Don't warn about `-i64::MAX` values when converting models

rten-gemm/src/kernels.rs
Add a benchmark that tests int8 matmul kernels with prepacked inputs that fit in the L1 cache.
Initial findings with this are that the i8mm kernel is marginally faster than dotprod on M3 Pro, but significantly faster (~1.6x) on a Neoverse V2 (AWS Graviton 4).
M3 Pro:
```
$ cargo test -p rten-gemm -r -- --ignored bench_kernel_int8 --nocapture
...
arm-int8-udot: 1000000 iters in 0.1455s = 450.51 GFLOPS
arm-int8-i8mm: 1000000 iters in 0.1434s = 457.06 GFLOPS
```
AWS Graviton 4 (c8g.xlarge):
```
arm-int8-udot: 1000000 iters in 0.2546s = 257.40 GFLOPS
arm-int8-i8mm: 1000000 iters in 0.1500s = 436.99 GFLOPS
```
TODO:
=> Add int8 GEMM kernel benchmark

rten-gemm/src/kernels/aarch64.rs, rten-gemm/src/kernels/simd_generic.rs
The int8 GEMM kernels have a different structure for the loop over K depending on the instructions they use, but the epilogue for adjusting the accumulators to reflect the zero points and writing results back to memory can be the same for each.
There is one functional change which is that the kernels using dot product instructions now initialize the accumulators to zero and add the `k * a_zero_point * b_zero_point` term in the epilogue, instead of initializing the accumulators with this term.
=> Use a shared epilogue for int8 GEMM kernels

rten-gemm/src/lib.rs
`TensorBase::slice` has some overhead from supporting the flexibility of `SliceItem` (signed indices, steps etc.). In the GEMV loop around the kernel it is worth using a specialized implementation which only supports unsigned row and column ranges.
=> Use specialized matrix slice in gemv

rten-examples/src/whisper.rs
The encoding, prompt and decoding phases represent quite different workloads, so it is useful to see a breakdown of timings.
=> Report encode, prompt and decode timings in Whisper example

rten-gemm/src/packing/int8.rs
Refactor packing so there are fewer branches in the main loop over full-size panels and tiles. There are more unsafe blocks now, but these are also more narrowly scoped. This is also a step towards vectorizing packing.
On a whisper-v3-large-turbo test, this reduced time spent in int8 LHS packing from 4.4 to 3.3% of total time.
=> Split int8 packing into main/tail loops

src/model.rs
Change ModelOptions to make it cheaply Clone-able and add an example that uses this to limit scope of `unsafe` when using `load_mmap`.
=> Impl Default + Clone for ModelOptions

rten-convert/rten_convert/converter.py
Fix model converter producing empty output models if the input is more than 2GB in size. This happens because `onnx.shape_inference.infer_shapes` silently returns model with an empty graph in this case. The solution is to use `infer_shapes_path` instead to create a temporary new .onnx file with shape info.
Fixes https://github.com/robertknight/rten/issues/851
=> Fix conversion of models > 2GB in size

rten-convert/rten_convert/converter.py, rten-convert/rten_convert/schema_generated.py, src/graph/builder.rs, src/graph/capture_env.rs, src/op_registry.rs, src/ops/control_flow.rs, src/ops/mod.rs, src/schema.fbs, src/schema_generated.rs, src/value.rs
Implement the [`Loop`](https://onnx.ai/onnx/operators/onnx__Loop.html) operator. This runs a subgraph repeatedly until a given iteration count limit is reached or a condition input/output is false.
=> Implement Loop operator

rten-convert/rten_convert/converter.py, rten-convert/rten_convert/schema_generated.py, src/op_registry.rs, src/ops/mod.rs, src/ops/sequence.rs, src/ops/split.rs, src/schema.fbs, src/schema_generated.rs
Implement the [`SplitToSequence`](https://onnx.ai/onnx/operators/onnx__SplitToSequence.html) operator.
=> Implement SplitToSequence operator

rten-convert/rten_convert/schema_generated.py, src/op_registry.rs, src/ops/mod.rs, src/ops/sequence.rs, src/schema.fbs, src/schema_generated.rs, src/value.rs
Implement the [SequenceErase](https://onnx.ai/onnx/operators/onnx__SequenceErase.html) operator. I haven't found a model that uses this yet, but PyTorch does support generating it.
=> Implement SequenceErase operator

src/graph.rs
When errors occur running subgraphs, include in the error message a "stack trace" of the operator nodes that contain the subgraph. This makes it easier to locate the node where the problem occurred in a tool like Netron.
Example output from rten-cli:
```
Failed to load model "/Users/robert/Downloads/dinov3-convnext/model.rten": graph
optimization error: partial evaluation failed: operator "n6_2" subgraph error:
planning error Missing input "val_236" for op "n8"
```
The `operator "n6_2" subgraph error` part is new in this commit.
In the process the `Display` impl for some existing `RunError` variants was changed to use the `Display` rather than `Debug` format for sub-errors.
=> Include ancestor node details when errors occur in subgraphs

rten-simd/src/arch/generic.rs
Add `map`, `map_with` helpers to save boilerplate in unpacking, mapping and re-packing arrays.
=> Add helpers to reduce boilerplate in generic SIMD ops

rten-convert/rten_convert/converter.py
Fix a bug when converting subgraphs where captured values were not added to the capture list in some cases. All operator inputs which do not appear in a graph's inputs or operator outputs should be marked as captures. However this did not happen if the input had an entry in the `value_info` field of the GraphProto.
This is because values were marked as captures only if there was no existing constant or value node with that name. Entries in `value_info` create value nodes however. The fix is to instead test if the value is "available" from the local graph (provided as an input, or is computable from operator outputs).
Fixes https://github.com/robertknight/rten/issues/900
=> Fix operator inputs not being added to captures list

src/graph.rs, src/ops/gather.rs, src/ops/reduce.rs, src/optimize/pattern_matcher.rs
Use let chains from Rust 2024 to write some multi-condition `if`s in a more natural way.
=> Use let chains in conditionals

rten-tensor/src/copy.rs
For operators such as `Split`, using memcpy to copy chunks is worthwhile only if the chunk size is large enough, otherwise the overhead of the function call makes this slower than using the general nested loop.
If for example we have a tensor like `[X, Y, Z, N]` and are creating N splits using the last axis, it is better to use the nested loop. Adding a threshold reduced time in Split operator in NeuFlow v2 from ~21ms to ~4ms.
As noted in commit, the current threshold has been picked on a "seems reasonable" basis. Tuning it with more data might yield better results.
=> Add a minimum size threshold for using memcpy to copy inner lane of tensors

rten-convert/rten_convert/attr_reader.py
Conversion of attribute values with type `onnx.AttributeProto.AttributeType.FLOATS` failed because a mapping was missing in the `_value_fields` dict.
We don't need to implement this mapping ourselves, because there is an `onnx.helper.get_attribute_value` function, so use that instead. There is also a `get_node_attr_value` helper, but that doesn't let us verify that the attribute has the expected type. That helper does however check that there is exactly one attribute of the given name. For consistency, add the same check in `AttributeReader.get_attr`.
This fixes an error when converting a ConvNeXt model exported with:
```
./tools/export-timm-model.py timm/convnext_base.fb_in1k --dynamo
```
=> Support conversion of ONNX attributes with "floats" type

rten-examples/src/imagenet.rs
Allow specifying the various preprocessing parameters separately, instead of just three specific combinations. This makes the example usable with a wider range of models. Also update the docs describing where to get models from to use sources that are more popular in 2025.
=> Update ImageNet example to support more models

src/ops/operators.rs
- Adjust the layout bounds to enable converting `&self` to a TensorView inside the thread pool. Also `TensorBase` no longer requires its layout to impl `MutLayout`.
- Construct the `BufferPool` in the `run_operator` helper.
=> Reduce some boilerplate in Operators trait implementations

rten-examples/src/piper.rs
Simplify audio file generation in the Piper example by generating a WAV file with float samples. This makes the output larger, but that's fine for a demo.
=> Simplify Piper example by generating float WAV file

src/ops/norm.rs
Make these operations parallel over both batch and channel dimensions. Previously they were parallel over channels only.
=> Make BatchNormalization, InstanceNormalization parallel over batch

src/graph.rs
If an operator supports being run in-place, but was not because the in-place input is needed by other operators, then that input would be missing from the profiling record. This happened because the logic to populate the `input_meta` vec didn't properly handle the case where `in_place_input_id` was `Some(_)` but `in_place_input` was None.
The fix is to refactor the code so that `in_place_input` is an `Option<(NodeId, Value)>` for the actually in-placed input and downstream code always handles the ID and value together.
=> Fix missing inputs for some in-place operators in timing records

src/ops/quantize.rs
Refactor DequantizeLinear to make supporting additional integer types easier and add support for i32.
Encountered when testing [this model](https://huggingface.co/pipecat-ai/smart-turn-v3/tree/main).
=> Support i32 inputs in DequantizeLinear

src/model/onnx_loader.rs
Return an error instead of panicking if a graph input or output has an empty name. The panic occurred because the loop which creates values skipped over values with empty names, but we later assumed that nodes would exist in the RTen graph for all inputs and outputs in the ONNX graph.
=> Fix panic in ONNX loader if graph input or output has empty name
